"""Exact backend-neutral algebra for ordered logical point domains."""

from __future__ import annotations

from collections.abc import Callable, Iterator
from dataclasses import dataclass
from math import prod
from typing import Never, overload

from scopecat.compiler.relations.model import CellValue
from scopecat.kernel.value_types import (
    Bool,
    Entity,
    Float,
    Int,
    Scalar,
    String,
    Table,
    TableColumn,
)
from scopecat.kernel.value_types import (
    Quantity as QuantityType,
)
from scopecat.records.parameter import Quantity

type PointDomainPath = tuple[str | int, ...]


def is_point_coordinate_type(value_type: Scalar) -> bool:
    """Return whether a scalar belongs to the dataset coordinate domain."""

    return isinstance(
        value_type.atom,
        Bool | Int | Float | String | QuantityType | Entity,
    )


def point_axis_linear_value(
    center: Quantity,
    span: Quantity,
    count: int,
    index: int,
) -> Quantity:
    """Return one exact value from a fixed-count linear point axis."""

    converted_span = span.to(center.unit)
    start = center.value - converted_span.value / 2
    step = converted_span.value / (count - 1)
    return Quantity(
        value=round(start + index * step, 12),
        unit=center.unit,
    )


@dataclass(frozen=True, slots=True)
class PointUnit:
    """The exact-one empty-row identity for point products."""


@dataclass(frozen=True, slots=True)
class PointAxisValues:
    """One finite axis whose values are known literally."""

    values: tuple[CellValue, ...]


@dataclass(frozen=True, slots=True)
class PointAxisLinear[CenterT]:
    """One fixed-count linear axis around a possibly dynamic center."""

    center: CenterT
    span: Quantity
    count: int

    def __post_init__(self) -> None:
        if self.count < 2:
            msg = "linear point axis count must be at least 2"
            raise ValueError(msg)


type PointAxisSource[CenterT] = PointAxisValues | PointAxisLinear[CenterT]


@dataclass(frozen=True, slots=True)
class PointAxis[CenterT]:
    """One named scalar coordinate generated by an exact axis source."""

    id: str
    value_type: Scalar
    source: PointAxisSource[CenterT]

    def __post_init__(self) -> None:
        TableColumn(self.id, self.value_type)


@dataclass(frozen=True, slots=True)
class PointProduct[CenterT]:
    """A flat declaration-ordered Cartesian product."""

    factors: tuple[PointAxis[CenterT], ...]

    def __post_init__(self) -> None:
        if len(self.factors) < 2:
            msg = "canonical point product requires at least two factors"
            raise ValueError(msg)


type PointDomainExpr[CenterT] = PointUnit | PointAxis[CenterT] | PointProduct[CenterT]

POINT_UNIT = PointUnit()


def point_axis_values(
    axis_id: str,
    value_type: Scalar,
    values: tuple[CellValue, ...],
) -> PointAxis[Never]:
    """Build one exact literal axis."""

    return PointAxis[Never](axis_id, value_type, PointAxisValues(values))


def point_axis_linear[CenterT](
    axis_id: str,
    value_type: Scalar,
    center: CenterT,
    span: Quantity,
    count: int,
) -> PointAxis[CenterT]:
    """Build one exact fixed-count linear axis."""

    return PointAxis(
        axis_id,
        value_type,
        PointAxisLinear(center=center, span=span, count=count),
    )


@overload
def point_product() -> PointUnit: ...


@overload
def point_product(
    first: PointDomainExpr[Never],
    *rest: PointDomainExpr[Never],
) -> PointDomainExpr[Never]: ...


@overload
def point_product[CenterT](
    first: PointDomainExpr[CenterT],
    *rest: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]: ...


def point_product[CenterT](
    first: PointDomainExpr[CenterT] | None = None,
    *rest: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]:
    """Build a canonical flat product without reordering or deduplication."""

    factors = () if first is None else (first, *rest)
    flattened: list[PointAxis[CenterT]] = []
    for factor in factors:
        if isinstance(factor, PointUnit):
            continue
        if isinstance(factor, PointProduct):
            flattened.extend(factor.factors)
        else:
            flattened.append(factor)
    if not flattened:
        return POINT_UNIT
    if len(flattened) == 1:
        return flattened[0]
    return PointProduct(tuple(flattened))


def iter_point_axis_linear[CenterT](
    root: PointDomainExpr[CenterT],
) -> Iterator[tuple[PointDomainPath, PointAxisLinear[CenterT]]]:
    """Yield linear sources and their stable axis paths."""

    if isinstance(root, PointAxis):
        if isinstance(root.source, PointAxisLinear):
            yield (), root.source
        return
    if isinstance(root, PointProduct):
        for index, axis in enumerate(root.factors):
            if isinstance(axis.source, PointAxisLinear):
                yield ("factors", index), axis.source


def map_point_axis_centers[CenterT, MappedCenterT](
    root: PointDomainExpr[CenterT],
    transform: Callable[[CenterT, PointDomainPath], MappedCenterT],
) -> PointDomainExpr[MappedCenterT]:
    """Map linear centers while preserving the flat domain structure."""

    def map_axis(
        axis: PointAxis[CenterT],
        path: PointDomainPath,
    ) -> PointAxis[MappedCenterT]:
        source = axis.source
        mapped_source: PointAxisSource[MappedCenterT]
        if isinstance(source, PointAxisLinear):
            mapped_source = PointAxisLinear(
                center=transform(source.center, path),
                span=source.span,
                count=source.count,
            )
        else:
            mapped_source = source
        return PointAxis(axis.id, axis.value_type, mapped_source)

    if isinstance(root, PointUnit):
        return POINT_UNIT
    if isinstance(root, PointAxis):
        return map_axis(root, ())
    return PointProduct(
        tuple(
            map_axis(axis, ("factors", index))
            for index, axis in enumerate(root.factors)
        )
    )


class PointDomainShapeError(ValueError):
    """A domain has incompatible output columns."""

    def __init__(self, code: str, path: PointDomainPath, message: str) -> None:
        self.code = code
        self.path = path
        self.message = message
        super().__init__(message)


@dataclass(frozen=True, slots=True)
class PointDomainShape:
    """The ordered columns and exact cardinality of one point domain."""

    columns: tuple[TableColumn, ...]
    cardinality: int

    def __post_init__(self) -> None:
        if self.cardinality < 0:
            msg = "point-domain cardinality must be nonnegative"
            raise ValueError(msg)

    @property
    def value_type(self) -> Table:
        """Project the exact shape to the compiler's table type."""

        return Table(
            columns=self.columns,
            min_rows=self.cardinality,
            max_rows=self.cardinality,
        )


def analyze_point_domain[CenterT](
    root: PointDomainExpr[CenterT],
) -> PointDomainShape:
    """Compute exact schema and cardinality from the flat point structure."""

    if isinstance(root, PointUnit):
        return PointDomainShape((), 1)
    axes = (root,) if isinstance(root, PointAxis) else root.factors
    columns = tuple(TableColumn(axis.id, axis.value_type) for axis in axes)
    column_ids = tuple(column.id for column in columns)
    duplicates = tuple(
        sorted(
            {column_id for column_id in column_ids if column_ids.count(column_id) > 1}
        )
    )
    if duplicates:
        raise PointDomainShapeError(
            "point_domain_duplicate_columns",
            (),
            "point-domain composition produces duplicate columns: "
            + ", ".join(duplicates),
        )
    cardinality = prod(
        (
            axis.source.count
            if isinstance(axis.source, PointAxisLinear)
            else len(axis.source.values)
        )
        for axis in axes
    )
    return PointDomainShape(columns, cardinality)
