"""Exact backend-neutral algebra for ordered logical point domains.

Point-domain leaves describe only the finite point sources the compiler knows
how to materialize directly: explicit axes, fixed-count linear axes, and
literal rows.  Cartesian, dependent, and positional composition preserve that
exact cardinality without embedding a general relation language in the point
model.
"""

from __future__ import annotations

from collections.abc import Callable, Iterator, Mapping
from dataclasses import dataclass
from math import prod
from typing import Never, overload

from scopecat.compiler.relations.model import CellValue
from scopecat.kernel.value_types import (
    Bool,
    Entity,
    Float,
    Int,
    Scalar,
    String,
    Table,
    TableColumn,
)
from scopecat.kernel.value_types import (
    Quantity as QuantityType,
)
from scopecat.records.parameter import Quantity

type PointDomainPath = tuple[str | int, ...]


def is_point_coordinate_type(value_type: Scalar) -> bool:
    """Return whether a scalar belongs to the dataset coordinate domain."""

    return isinstance(
        value_type.atom,
        Bool | Int | Float | String | QuantityType | Entity,
    )


def point_axis_linear_value(
    center: Quantity,
    span: Quantity,
    count: int,
    index: int,
) -> Quantity:
    """Return one exact value from a fixed-count linear point axis."""

    converted_span = span.to(center.unit)
    start = center.value - converted_span.value / 2
    step = converted_span.value / (count - 1)
    return Quantity(
        value=round(start + index * step, 12),
        unit=center.unit,
    )


@dataclass(frozen=True, slots=True)
class PointUnit:
    """The exact-one empty-row identity for point products."""


@dataclass(frozen=True, slots=True)
class PointAxisValues:
    """One finite axis whose values are known literally."""

    values: tuple[CellValue, ...]


@dataclass(frozen=True, slots=True)
class PointAxisLinear[CenterT]:
    """One fixed-count linear axis around a possibly dynamic center."""

    center: CenterT
    span: Quantity
    count: int

    def __post_init__(self) -> None:
        if self.count < 2:
            msg = "linear point axis count must be at least 2"
            raise ValueError(msg)


type PointAxisSource[CenterT] = PointAxisValues | PointAxisLinear[CenterT]


@dataclass(frozen=True, slots=True)
class PointAxis[CenterT]:
    """One named scalar coordinate generated by an exact axis source."""

    id: str
    value_type: Scalar
    source: PointAxisSource[CenterT]

    def __post_init__(self) -> None:
        # Reuse the kernel's column-id invariant at the algebra boundary.
        TableColumn(self.id, self.value_type)


@dataclass(frozen=True, slots=True)
class PointRows:
    """Exact literal rows stored positionally in declared column order."""

    columns: tuple[TableColumn, ...]
    rows: tuple[tuple[CellValue, ...], ...]

    def __post_init__(self) -> None:
        width = len(self.columns)
        for index, row in enumerate(self.rows):
            if len(row) != width:
                msg = (
                    f"literal point row {index} has width {len(row)}; expected {width}"
                )
                raise ValueError(msg)

    @property
    def value_type(self) -> Table:
        """Project this exact point leaf to the compiler's table type."""

        count = len(self.rows)
        return Table(columns=self.columns, min_rows=count, max_rows=count)


@dataclass(frozen=True, slots=True)
class PointProduct[CenterT]:
    """Independent Cartesian factors evaluated in one ambient environment."""

    factors: tuple[PointDomainExpr[CenterT], ...]

    def __post_init__(self) -> None:
        if len(self.factors) < 2:
            msg = "canonical point product requires at least two factors"
            raise ValueError(msg)
        if any(isinstance(factor, PointUnit | PointProduct) for factor in self.factors):
            msg = "point product factors must be canonical"
            raise ValueError(msg)


@dataclass(frozen=True, slots=True)
class PointDependentProduct[CenterT]:
    """A product whose right side is evaluated once per left row."""

    left: PointDomainExpr[CenterT]
    right: PointDomainExpr[CenterT]

    def __post_init__(self) -> None:
        if isinstance(self.left, PointUnit) or isinstance(self.right, PointUnit):
            msg = "canonical dependent product cannot contain point unit"
            raise ValueError(msg)


@dataclass(frozen=True, slots=True)
class PointZip[CenterT]:
    """Positional composition of equally long child domains."""

    sources: tuple[PointDomainExpr[CenterT], ...]

    def __post_init__(self) -> None:
        if len(self.sources) < 2:
            msg = "canonical point zip requires at least two sources"
            raise ValueError(msg)
        if any(isinstance(source, PointZip) for source in self.sources):
            msg = "point zip sources must be canonical"
            raise ValueError(msg)


type PointDomainExpr[CenterT] = (
    PointUnit
    | PointAxis[CenterT]
    | PointRows
    | PointProduct[CenterT]
    | PointDependentProduct[CenterT]
    | PointZip[CenterT]
)

POINT_UNIT = PointUnit()


def decompose_product_ordinal(
    ordinal: int,
    factor_counts: tuple[int, ...],
) -> tuple[int, ...]:
    """Map one left-major product ordinal to each factor's local ordinal."""

    return tuple(
        (ordinal // prod(factor_counts[index + 1 :])) % count
        for index, count in enumerate(factor_counts)
    )


def point_axis_values(
    axis_id: str,
    value_type: Scalar,
    values: tuple[CellValue, ...],
) -> PointAxis[Never]:
    """Build one exact literal axis."""

    return PointAxis[Never](axis_id, value_type, PointAxisValues(values))


def point_axis_linear[CenterT](
    axis_id: str,
    value_type: Scalar,
    center: CenterT,
    span: Quantity,
    count: int,
) -> PointAxis[CenterT]:
    """Build one exact fixed-count linear axis."""

    return PointAxis(
        axis_id,
        value_type,
        PointAxisLinear(center=center, span=span, count=count),
    )


def point_literal_rows(
    columns: tuple[TableColumn, ...],
    rows: tuple[tuple[CellValue, ...], ...],
) -> PointRows:
    """Build exact positional literal rows."""

    return PointRows(columns=columns, rows=rows)


@overload
def point_product() -> PointUnit: ...


@overload
def point_product(
    first: PointDomainExpr[Never],
    *rest: PointDomainExpr[Never],
) -> PointDomainExpr[Never]: ...


@overload
def point_product[CenterT](
    first: PointDomainExpr[CenterT],
    *rest: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]: ...


def point_product[CenterT](
    first: PointDomainExpr[CenterT] | None = None,
    *rest: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]:
    """Build a canonical ordered product without reordering or deduplication."""

    factors = () if first is None else (first, *rest)
    flattened: list[PointDomainExpr[CenterT]] = []
    for factor in factors:
        if isinstance(factor, PointUnit):
            continue
        if isinstance(factor, PointProduct):
            flattened.extend(factor.factors)
        else:
            flattened.append(factor)
    if not flattened:
        return POINT_UNIT
    if len(flattened) == 1:
        return flattened[0]
    return PointProduct(tuple(flattened))


@overload
def point_dependent_product(
    left: PointDomainExpr[Never],
    right: PointDomainExpr[Never],
) -> PointDomainExpr[Never]: ...


@overload
def point_dependent_product[CenterT](
    left: PointDomainExpr[CenterT],
    right: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]: ...


def point_dependent_product[CenterT](
    left: PointDomainExpr[CenterT],
    right: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]:
    """Build directional point composition, applying only the Unit laws."""

    if isinstance(left, PointUnit):
        return right
    if isinstance(right, PointUnit):
        return left
    return PointDependentProduct(left, right)


@overload
def point_zip(
    first: PointDomainExpr[Never],
    second: PointDomainExpr[Never],
    *rest: PointDomainExpr[Never],
) -> PointDomainExpr[Never]: ...


@overload
def point_zip[CenterT](
    first: PointDomainExpr[CenterT],
    second: PointDomainExpr[CenterT],
    *rest: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]: ...


def point_zip[CenterT](
    first: PointDomainExpr[CenterT],
    second: PointDomainExpr[CenterT],
    *rest: PointDomainExpr[CenterT],
) -> PointDomainExpr[CenterT]:
    """Build a canonical positional composition.

    Unit is deliberately not an identity for Zip: its one empty row constrains
    every other source to have exactly one materialized row.
    """

    sources = (first, second, *rest)
    flattened: list[PointDomainExpr[CenterT]] = []
    for source in sources:
        if isinstance(source, PointZip):
            flattened.extend(source.sources)
        else:
            flattened.append(source)
    return PointZip(tuple(flattened))


def walk_point_domain[CenterT](
    root: PointDomainExpr[CenterT],
) -> Iterator[tuple[PointDomainPath, PointDomainExpr[CenterT]]]:
    """Walk a canonical domain in deterministic preorder."""

    def visit(
        node: PointDomainExpr[CenterT],
        path: PointDomainPath,
    ) -> Iterator[tuple[PointDomainPath, PointDomainExpr[CenterT]]]:
        yield path, node
        match node:
            case PointUnit() | PointAxis() | PointRows():
                return
            case PointProduct(factors=factors):
                for index, factor in enumerate(factors):
                    yield from visit(factor, (*path, "factors", index))
            case PointDependentProduct(left=left, right=right):
                yield from visit(left, (*path, "left"))
                yield from visit(right, (*path, "right"))
            case PointZip(sources=sources):
                for index, source in enumerate(sources):
                    yield from visit(source, (*path, "sources", index))

    yield from visit(root, ())


def iter_point_axis_linear[CenterT](
    root: PointDomainExpr[CenterT],
) -> Iterator[tuple[PointDomainPath, PointAxisLinear[CenterT]]]:
    """Yield linear axis sources with the path of their owning axis node."""

    for path, node in walk_point_domain(root):
        if isinstance(node, PointAxis) and isinstance(node.source, PointAxisLinear):
            yield path, node.source


def map_point_axis_centers[CenterT, MappedCenterT](
    root: PointDomainExpr[CenterT],
    transform: Callable[[CenterT, PointDomainPath], MappedCenterT],
) -> PointDomainExpr[MappedCenterT]:
    """Map linear-axis centers while preserving the canonical tree and paths."""

    def visit(
        node: PointDomainExpr[CenterT],
        path: PointDomainPath,
    ) -> PointDomainExpr[MappedCenterT]:
        match node:
            case PointUnit():
                return POINT_UNIT
            case PointAxis(id=axis_id, value_type=value_type, source=source):
                mapped_source: PointAxisSource[MappedCenterT]
                if isinstance(source, PointAxisLinear):
                    mapped_source = PointAxisLinear(
                        center=transform(source.center, path),
                        span=source.span,
                        count=source.count,
                    )
                else:
                    mapped_source = source
                return PointAxis(axis_id, value_type, mapped_source)
            case PointRows():
                return node
            case PointProduct(factors=factors):
                return PointProduct(
                    tuple(
                        visit(factor, (*path, "factors", index))
                        for index, factor in enumerate(factors)
                    )
                )
            case PointDependentProduct(left=left, right=right):
                return PointDependentProduct(
                    visit(left, (*path, "left")),
                    visit(right, (*path, "right")),
                )
            case PointZip(sources=sources):
                return PointZip(
                    tuple(
                        visit(source, (*path, "sources", index))
                        for index, source in enumerate(sources)
                    )
                )

    return visit(root, ())


class PointDomainShapeError(ValueError):
    """A domain tree has incompatible schemas or exact cardinalities."""

    def __init__(self, code: str, path: PointDomainPath, message: str) -> None:
        self.code = code
        self.path = path
        self.message = message
        super().__init__(message)


@dataclass(frozen=True, slots=True)
class PointDomainShape:
    """The ordered columns and exact cardinality of one algebra node."""

    columns: tuple[TableColumn, ...]
    cardinality: int

    def __post_init__(self) -> None:
        if self.cardinality < 0:
            msg = "point-domain cardinality must be nonnegative"
            raise ValueError(msg)

    @property
    def value_type(self) -> Table:
        """Project the point shape to the compiler's exact table type."""

        return Table(
            columns=self.columns,
            min_rows=self.cardinality,
            max_rows=self.cardinality,
        )


@dataclass(frozen=True, slots=True)
class PointDomainAnalysis:
    """Root and per-node exact shapes for one canonical domain tree."""

    root: PointDomainShape
    facts: Mapping[PointDomainPath, PointDomainShape]


def analyze_point_domain[CenterT](
    root: PointDomainExpr[CenterT],
) -> PointDomainAnalysis:
    """Compute exact schema and cardinality facts from point structure alone."""

    facts: dict[PointDomainPath, PointDomainShape] = {}

    def analyze(
        node: PointDomainExpr[CenterT],
        path: PointDomainPath,
    ) -> PointDomainShape:
        match node:
            case PointUnit():
                shape = PointDomainShape((), 1)
            case PointAxis(id=axis_id, value_type=value_type, source=source):
                count = (
                    source.count
                    if isinstance(source, PointAxisLinear)
                    else len(source.values)
                )
                shape = PointDomainShape((TableColumn(axis_id, value_type),), count)
            case PointRows(columns=columns, rows=rows):
                shape = PointDomainShape(
                    _merged_columns((columns,), path=path),
                    len(rows),
                )
            case PointProduct(factors=factors):
                children = tuple(
                    analyze(factor, (*path, "factors", index))
                    for index, factor in enumerate(factors)
                )
                shape = _product_shape(children, path=path)
            case PointDependentProduct(left=left, right=right):
                children = (
                    analyze(left, (*path, "left")),
                    analyze(right, (*path, "right")),
                )
                shape = _product_shape(children, path=path)
            case PointZip(sources=sources):
                children = tuple(
                    analyze(source, (*path, "sources", index))
                    for index, source in enumerate(sources)
                )
                shape = _zip_shape(children, path=path)
        facts[path] = shape
        return shape

    root_shape = analyze(root, ())
    return PointDomainAnalysis(
        root=root_shape,
        facts=dict(facts),
    )


def _product_shape(
    children: tuple[PointDomainShape, ...],
    *,
    path: PointDomainPath,
) -> PointDomainShape:
    columns = _merged_columns(tuple(child.columns for child in children), path=path)
    count = prod(child.cardinality for child in children)
    return PointDomainShape(columns, count)


def _zip_shape(
    children: tuple[PointDomainShape, ...],
    *,
    path: PointDomainPath,
) -> PointDomainShape:
    columns = _merged_columns(tuple(child.columns for child in children), path=path)
    counts = tuple(child.cardinality for child in children)
    if len(set(counts)) != 1:
        raise PointDomainShapeError(
            "point_domain_zip_cardinality_mismatch",
            path,
            "point zip sources must have equal exact cardinality",
        )
    count = counts[0]
    return PointDomainShape(columns, count)


def _merged_columns(
    groups: tuple[tuple[TableColumn, ...], ...],
    *,
    path: PointDomainPath,
) -> tuple[TableColumn, ...]:
    columns = tuple(column for group in groups for column in group)
    column_ids = tuple(column.id for column in columns)
    duplicates = tuple(
        sorted(
            {column_id for column_id in column_ids if column_ids.count(column_id) > 1}
        )
    )
    if duplicates:
        raise PointDomainShapeError(
            "point_domain_duplicate_columns",
            path,
            "point-domain composition produces duplicate columns: "
            + ", ".join(duplicates),
        )
    return columns
