repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/tombi-toml/tombi-pre-commit
    rev: 7fd33d1d0a5b52dcc5aaae94c68cc90a9926271e  # frozen: v1.2.10
    hooks:
      - id: tombi-format
        args: ["--offline"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 39d9ac5938dadb73df0564a45f163e25ff9fa6e2  # frozen: v0.16.1
    hooks:
      - id: ruff-check
        args: [--fix]
        types_or: [python, pyi]
      - id: ruff-format
        types_or: [python, pyi, markdown]
