"""Writer-to-reader round-trip for directory-shaped handoff packages.

This candidate composes existing handoff package slices. It writes a package,
previews the generated manifest, opens the generated package through the
read-view wrapper, and returns only local review facts about that compatibility.
"""

from __future__ import annotations

import copy
import json
from pathlib import Path
from typing import Any

from implementation_candidates.handoff_package_contents_preview import (
    build_handoff_package_contents_preview_summary,
)
from implementation_candidates.handoff_package_read_view import open_handoff_package_view
from implementation_candidates.handoff_package_writer import write_handoff_package

_EXPECTED_POLICY = {
    "round_trip_authority": "writer_output_directory_then_read_only_open",
    "package_write": "performed",
    "manifest_preview": "performed",
    "read_view_open": "performed",
    "archive_creation": "not_performed",
    "package_acceptance": "not_performed",
    "storage_import": "not_performed",
    "checksum_validation": "not_performed_after_write",
    "schema_inference": "not_performed",
    "dataframe_adapter": "not_defined",
    "gui_workflow": "not_defined",
    "shared_measurement_schema": "not_defined",
}


def _load_manifest(package_dir: Path) -> dict[str, Any]:
    manifest_path = package_dir / "package-manifest.json"
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError("handoff package round trip requires generated package manifest") from exc
    if not isinstance(manifest, dict):
        raise ValueError("handoff package round trip manifest must be a JSON object")
    return manifest


def _measurement_round_trip(read_measurement: Any) -> dict[str, Any]:
    primary_table = read_measurement.primary_table()
    preview_table = read_measurement.preview_table()
    plot_series = read_measurement.plot_series()
    return {
        "measurement_record_id": read_measurement.measurement_record_id,
        "label": read_measurement.label,
        "primary_package_path": read_measurement.primary_package_path,
        "primary_table": {
            "columns": list(primary_table.columns),
            "row_count": primary_table.row_count,
        },
        "preview_table": {
            "columns": list(preview_table.columns),
            "row_count": preview_table.row_count,
        },
        "plot_series": [
            {
                "x": series.x_name,
                "y": series.y_name,
                "point_count": len(series.points),
            }
            for series in plot_series
        ],
        "linked_context_ids": [item["link_id"] for item in read_measurement.linked_context],
        "finding_codes": [finding["finding"] for finding in read_measurement.findings],
        "integrity_check": read_measurement.integrity_check,
        "classification": "writer_output_opened_for_reader_tasks",
    }


def _attention() -> list[dict[str, str]]:
    return [
        {
            "code": "writer_output_opened_by_read_view",
            "severity": "info",
            "basis": "A package directory generated by the writer was previewed and opened through the read-view wrapper.",
            "does_not_claim": "package_import_or_acceptance",
        },
        {
            "code": "package_integrity_not_revalidated",
            "severity": "review",
            "basis": "The writer preflights source sha256 and size facts; this round trip does not add a receiving-side checksum pass.",
            "does_not_claim": "receiving_side_package_integrity_verified",
        },
        {
            "code": "reader_api_not_final",
            "severity": "review",
            "basis": "Reader-facing table and plot access are implementation-candidate behavior.",
            "does_not_claim": "stable_sdk_or_dataframe_contract",
        },
    ]


def build_handoff_package_round_trip_summary(
    source: dict[str, Any],
    *,
    storage_root: Path,
    package_root: Path,
) -> dict[str, Any]:
    """Write a handoff package and verify it through the read-only reader path."""

    writer_summary = write_handoff_package(
        source,
        storage_root=storage_root,
        package_root=package_root,
    )
    package_id = source["package_identity"]["package_id"]
    package_dir = package_root / package_id
    manifest = _load_manifest(package_dir)
    preview_summary = build_handoff_package_contents_preview_summary(manifest)
    read_view = open_handoff_package_view(package_dir)

    measurement_summaries = [
        _measurement_round_trip(read_view.measurement(measurement_id))
        for measurement_id in read_view.measurement_ids
    ]
    return {
        "artifact_posture": "review_summary",
        "round_trip_policy": copy.deepcopy(_EXPECTED_POLICY),
        "package": {
            "package_id": manifest["package_identity"]["package_id"],
            "display_name": read_view.display_name,
            "preview_classification": preview_summary["package"]["classification"],
        },
        "generated_artifact": {
            "package_directory_name": package_dir.name,
            "manifest_name": "package-manifest.json",
            "package_directory_created": package_dir.is_dir(),
            "manifest_created": (package_dir / "package-manifest.json").is_file(),
        },
        "local_write_receipt": {
            "artifact_posture": writer_summary["artifact_posture"],
            "retained_in_round_trip_summary": True,
        },
        "manifest_preview": {
            "finding_codes": [
                finding["finding"] for finding in preview_summary["preview_findings"]
            ],
            "selected_measurement_count": len(preview_summary["selected_measurements"]),
            "linked_context_count": len(manifest["linked_context"]),
        },
        "read_view": {
            "measurement_ids": list(read_view.measurement_ids),
            "measurements": measurement_summaries,
            "linked_context_ids": [item["link_id"] for item in read_view.linked_context],
            "finding_codes": [finding["finding"] for finding in read_view.findings],
        },
        "attention": _attention(),
    }
