"""Demo quantum lab package used by the Scopecat examples."""

from quantum_lab_demo.fixtures import (
    DEFAULT_READOUT_FREQUENCY_WORKSPACE,
    DEFAULT_READOUT_IQ_WORKSPACE,
    DEFAULT_SAMPLE_TEMPLATES_WORKSPACE,
    DEFAULT_WORKSPACE_ROOT,
    FIXTURES_DIR,
    NOTEBOOK_WORKSPACE_ROOT_ENV,
    READOUT_FREQUENCY_FIXTURE_DIR,
    READOUT_FREQUENCY_VIRTUAL_LAB_PROFILE,
    READOUT_IQ_FIXTURE_DIR,
    READOUT_IQ_VIRTUAL_LAB_PROFILE,
    REPO_ROOT,
    SAMPLE_TEMPLATES_FIXTURE_DIR,
    SAMPLE_TEMPLATES_VIRTUAL_LAB_PROFILE,
    notebook_workspace,
)
from quantum_lab_demo.lab import (
    PathInput,
    readout_frequency_lab,
    readout_iq_lab,
    sample_lab,
)
from quantum_lab_demo.preview import (
    DEFAULT_PREVIEW_WORKSPACE,
    drive_scan,
    format_preview_summary,
    load_preview_config,
    preview_drive_scan,
)
from quantum_lab_demo.sample_workflows import (
    SampleExperimentsResult,
    format_sample_experiments_summary,
    run_cz_rb_experiment,
    run_rabi_experiment,
    run_sample_experiments,
    run_sample_readout_frequency,
    run_sqg_rb_experiment,
)
from quantum_lab_demo.workflows import (
    ReadoutFrequencyWorkflowResult,
    ReadoutIQWorkflowResult,
    format_readout_frequency_summary,
    format_readout_iq_summary,
    run_readout_frequency_workflow,
    run_readout_iq_workflow,
)

__all__ = [
    "DEFAULT_PREVIEW_WORKSPACE",
    "DEFAULT_READOUT_FREQUENCY_WORKSPACE",
    "DEFAULT_READOUT_IQ_WORKSPACE",
    "DEFAULT_SAMPLE_TEMPLATES_WORKSPACE",
    "DEFAULT_WORKSPACE_ROOT",
    "FIXTURES_DIR",
    "NOTEBOOK_WORKSPACE_ROOT_ENV",
    "READOUT_FREQUENCY_FIXTURE_DIR",
    "READOUT_FREQUENCY_VIRTUAL_LAB_PROFILE",
    "READOUT_IQ_FIXTURE_DIR",
    "READOUT_IQ_VIRTUAL_LAB_PROFILE",
    "REPO_ROOT",
    "SAMPLE_TEMPLATES_FIXTURE_DIR",
    "SAMPLE_TEMPLATES_VIRTUAL_LAB_PROFILE",
    "PathInput",
    "ReadoutFrequencyWorkflowResult",
    "ReadoutIQWorkflowResult",
    "SampleExperimentsResult",
    "__version__",
    "drive_scan",
    "format_preview_summary",
    "format_readout_frequency_summary",
    "format_readout_iq_summary",
    "format_sample_experiments_summary",
    "load_preview_config",
    "notebook_workspace",
    "preview_drive_scan",
    "readout_frequency_lab",
    "readout_iq_lab",
    "run_cz_rb_experiment",
    "run_rabi_experiment",
    "run_readout_frequency_workflow",
    "run_readout_iq_workflow",
    "run_sample_experiments",
    "run_sample_readout_frequency",
    "run_sqg_rb_experiment",
    "sample_lab",
]

__version__ = "0.1.0"
