"""Repository-local paths for example Scopecat adoption workflows."""

from __future__ import annotations

import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[5]
FIXTURES_DIR = REPO_ROOT / "fixtures" / "quantum"

READOUT_FREQUENCY_FIXTURE_DIR = FIXTURES_DIR / "readout_frequency_calibration"
READOUT_IQ_FIXTURE_DIR = FIXTURES_DIR / "readout_iq_quality"
SAMPLE_TEMPLATES_FIXTURE_DIR = FIXTURES_DIR / "sample_templates"

READOUT_FREQUENCY_VIRTUAL_LAB_PROFILE = (
    READOUT_FREQUENCY_FIXTURE_DIR / "virtual-lab.json"
)
READOUT_IQ_VIRTUAL_LAB_PROFILE = READOUT_IQ_FIXTURE_DIR / "virtual-lab.json"
SAMPLE_TEMPLATES_VIRTUAL_LAB_PROFILE = SAMPLE_TEMPLATES_FIXTURE_DIR / "virtual-lab.json"

DEFAULT_WORKSPACE_ROOT = REPO_ROOT / ".scopecat-examples"
DEFAULT_READOUT_FREQUENCY_WORKSPACE = DEFAULT_WORKSPACE_ROOT / "readout-frequency"
DEFAULT_READOUT_IQ_WORKSPACE = DEFAULT_WORKSPACE_ROOT / "readout-iq"
DEFAULT_SAMPLE_TEMPLATES_WORKSPACE = DEFAULT_WORKSPACE_ROOT / "sample-experiments"

NOTEBOOK_WORKSPACE_ROOT_ENV = "QUANTUM_LAB_DEMO_NOTEBOOK_WORKSPACE_ROOT"


def notebook_workspace(name: str) -> Path:
    root = Path(os.environ.get(NOTEBOOK_WORKSPACE_ROOT_ENV, DEFAULT_WORKSPACE_ROOT))
    return root / "notebooks" / name


__all__ = [
    "DEFAULT_READOUT_FREQUENCY_WORKSPACE",
    "DEFAULT_READOUT_IQ_WORKSPACE",
    "DEFAULT_SAMPLE_TEMPLATES_WORKSPACE",
    "DEFAULT_WORKSPACE_ROOT",
    "FIXTURES_DIR",
    "NOTEBOOK_WORKSPACE_ROOT_ENV",
    "READOUT_FREQUENCY_FIXTURE_DIR",
    "READOUT_FREQUENCY_VIRTUAL_LAB_PROFILE",
    "READOUT_IQ_FIXTURE_DIR",
    "READOUT_IQ_VIRTUAL_LAB_PROFILE",
    "REPO_ROOT",
    "SAMPLE_TEMPLATES_FIXTURE_DIR",
    "SAMPLE_TEMPLATES_VIRTUAL_LAB_PROFILE",
    "notebook_workspace",
]
