"""Exact backend-neutral model for ordered logical point domains."""

from __future__ import annotations

from collections.abc import Callable, Iterator
from dataclasses import dataclass
from math import prod
from typing import Generic, Never, TypeVar

from scopecat.graph.relations.model import CellValue
from scopecat.kernel.quantity import Quantity
from scopecat.kernel.value_types import (
    Bool,
    Entity,
    Float,
    Int,
    Scalar,
    String,
    Table,
    TableColumn,
)
from scopecat.kernel.value_types import (
    Quantity as QuantityType,
)

type PointDomainPath = tuple[str | int, ...]

CenterT_co = TypeVar("CenterT_co", covariant=True)


def is_point_coordinate_type(value_type: Scalar) -> bool:
    """Return whether a scalar belongs to the dataset coordinate domain."""

    return isinstance(
        value_type.atom,
        Bool | Int | Float | String | QuantityType | Entity,
    )


def point_axis_linear_value(
    center: Quantity,
    span: Quantity,
    count: int,
    index: int,
) -> Quantity:
    """Return one exact value from a fixed-count linear point axis."""

    converted_span = span.to(center.unit)
    start = center.value - converted_span.value / 2
    step = converted_span.value / (count - 1)
    return Quantity(
        value=round(start + index * step, 12),
        unit=center.unit,
    )


@dataclass(frozen=True, slots=True)
class PointAxisValues:
    """One finite axis whose values are known literally."""

    values: tuple[CellValue, ...]


@dataclass(frozen=True, slots=True)
class PointAxisLinear(Generic[CenterT_co]):
    """One fixed-count linear axis around a possibly dynamic center."""

    center: CenterT_co
    span: Quantity
    count: int

    def __post_init__(self) -> None:
        if self.count < 2:
            msg = "linear point axis count must be at least 2"
            raise ValueError(msg)


type PointAxisSource[CenterT] = PointAxisValues | PointAxisLinear[CenterT]


@dataclass(frozen=True, slots=True)
class PointAxis(Generic[CenterT_co]):
    """One named scalar coordinate generated by an exact axis source."""

    id: str
    value_type: Scalar
    source: PointAxisSource[CenterT_co]

    def __post_init__(self) -> None:
        TableColumn(self.id, self.value_type)


type PointAxes[CenterT] = tuple[PointAxis[CenterT], ...]


def point_axis_values(
    axis_id: str,
    value_type: Scalar,
    values: tuple[CellValue, ...],
) -> PointAxis[Never]:
    """Build one exact literal axis."""

    return PointAxis[Never](axis_id, value_type, PointAxisValues(values))


def point_axis_linear[CenterT](
    axis_id: str,
    value_type: Scalar,
    center: CenterT,
    span: Quantity,
    count: int,
) -> PointAxis[CenterT]:
    """Build one exact fixed-count linear axis."""

    return PointAxis(
        axis_id,
        value_type,
        PointAxisLinear(center=center, span=span, count=count),
    )


def iter_point_axis_linear[CenterT](
    axes: PointAxes[CenterT],
) -> Iterator[tuple[PointDomainPath, PointAxisLinear[CenterT]]]:
    """Yield linear sources and their stable axis paths."""

    for index, axis in enumerate(axes):
        if isinstance(axis.source, PointAxisLinear):
            yield ("axes", index), axis.source


def map_point_axis_centers[CenterT, MappedCenterT](
    axes: PointAxes[CenterT],
    transform: Callable[[CenterT, PointDomainPath], MappedCenterT],
) -> PointAxes[MappedCenterT]:
    """Map linear centers while preserving the flat domain structure."""

    def map_axis(
        axis: PointAxis[CenterT],
        path: PointDomainPath,
    ) -> PointAxis[MappedCenterT]:
        source = axis.source
        mapped_source: PointAxisSource[MappedCenterT]
        if isinstance(source, PointAxisLinear):
            mapped_source = PointAxisLinear(
                center=transform(source.center, path),
                span=source.span,
                count=source.count,
            )
        else:
            mapped_source = source
        return PointAxis(axis.id, axis.value_type, mapped_source)

    return tuple(map_axis(axis, ("axes", index)) for index, axis in enumerate(axes))


class PointDomainShapeError(ValueError):
    """A domain has incompatible output columns."""

    def __init__(self, code: str, path: PointDomainPath, message: str) -> None:
        self.code = code
        self.path = path
        self.message = message
        super().__init__(message)


@dataclass(frozen=True, slots=True)
class PointDomainShape:
    """The ordered columns and exact cardinality of one point domain."""

    columns: tuple[TableColumn, ...]
    cardinality: int

    def __post_init__(self) -> None:
        if self.cardinality < 0:
            msg = "point-domain cardinality must be nonnegative"
            raise ValueError(msg)

    @property
    def value_type(self) -> Table:
        """Project the columns to the compiler's table type."""

        return Table(columns=self.columns)


def analyze_point_domain[CenterT](
    axes: PointAxes[CenterT],
) -> PointDomainShape:
    """Compute exact schema and cardinality from ordered point axes."""

    columns = tuple(TableColumn(axis.id, axis.value_type) for axis in axes)
    column_ids = tuple(column.id for column in columns)
    duplicates = tuple(
        sorted(
            {column_id for column_id in column_ids if column_ids.count(column_id) > 1}
        )
    )
    if duplicates:
        raise PointDomainShapeError(
            "point_domain_duplicate_columns",
            (),
            "point-domain composition produces duplicate columns: "
            + ", ".join(duplicates),
        )
    cardinality = prod(
        (
            axis.source.count
            if isinstance(axis.source, PointAxisLinear)
            else len(axis.source.values)
        )
        for axis in axes
    )
    return PointDomainShape(columns, cardinality)
