# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Vendor-neutral interface factories generated from Python declarations."""

from __future__ import annotations

from scopecat.sdk.instruments import InterfaceSpec

_CATALOG_PROJECTION_SPEC_JSON = (
    '{"id":"test.generated_catalog_projection'
    '/v1","label":null,"description":null,"pr'
    'operties":[{"id":"enabled","label":null,'
    '"description":null,"access":"read_write"'
    ',"capture":true,"restore":true,"value_ty'
    'pe":{"type":"bool"}},{"id":"status","lab'
    'el":null,"description":null,"access":"re'
    'ad_only","capture":true,"restore":false,'
    '"value_type":{"type":"string","choices":'
    'null}}],"operations":[],"acquisitions":['
    '],"components":[]}'
)


def catalog_projection_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_CATALOG_PROJECTION_SPEC_JSON)


_SHARED_PROPERTY_FIRST_SPEC_JSON = (
    '{"id":"test.generated_shared_property_fi'
    'rst/v1","label":null,"description":null,'
    '"properties":[{"id":"enabled","label":nu'
    'll,"description":null,"access":"read_wri'
    'te","capture":true,"restore":true,"value'
    '_type":{"type":"bool"}}],"operations":[]'
    ',"acquisitions":[],"components":[]}'
)


def shared_property_first_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_SHARED_PROPERTY_FIRST_SPEC_JSON)


_SHARED_PROPERTY_SECOND_SPEC_JSON = (
    '{"id":"test.generated_shared_property_se'
    'cond/v1","label":null,"description":null'
    ',"properties":[{"id":"enabled","label":n'
    'ull,"description":null,"access":"read_wr'
    'ite","capture":true,"restore":true,"valu'
    'e_type":{"type":"bool"}}],"operations":['
    '],"acquisitions":[],"components":[]}'
)


def shared_property_second_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_SHARED_PROPERTY_SECOND_SPEC_JSON)


_SCALAR_OPERATION_SPEC_JSON = (
    '{"id":"test.generated_scalar_operation/v'
    '1","label":null,"description":null,"prop'
    'erties":[],"operations":[{"id":"emit_pul'
    'se","label":null,"description":null,"arg'
    'uments":[{"id":"pulse_count","label":nul'
    'l,"description":null,"value_type":{"type'
    '":"int","minimum":-9007199254740991,"max'
    'imum":9007199254740991}},{"id":"pulse_wi'
    'dth","label":null,"description":null,"va'
    'lue_type":{"type":"quantity","dimension"'
    ':null,"unit":"s","minimum":null,"maximum'
    '":null,"finite":true}},{"id":"pulse_labe'
    'l","label":null,"description":null,"valu'
    'e_type":{"type":"string","choices":null}'
    '}],"invalidates":[]}],"acquisitions":[],'
    '"components":[]}'
)


def scalar_operation_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_SCALAR_OPERATION_SPEC_JSON)


_LITERAL_OPERATION_SPEC_JSON = (
    '{"id":"test.generated_literal_operation/'
    'v1","label":null,"description":null,"pro'
    'perties":[],"operations":[{"id":"select"'
    ',"label":null,"description":null,"argume'
    'nts":[{"id":"mode","label":null,"descrip'
    'tion":null,"value_type":{"type":"string"'
    ',"choices":["left","right"]}}],"invalida'
    'tes":[]}],"acquisitions":[],"components"'
    ":[]}"
)


def literal_operation_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_LITERAL_OPERATION_SPEC_JSON)


_PAYLOAD_OPERATION_SPEC_JSON = (
    '{"id":"test.generated_payload_operation/'
    'v1","label":null,"description":null,"pro'
    'perties":[],"operations":[{"id":"upload"'
    ',"label":null,"description":null,"argume'
    'nts":[{"id":"payload","label":null,"desc'
    'ription":null,"value_type":{"type":"payl'
    'oad","schema_id":"test.payload/v1"}}],"i'
    'nvalidates":[]}],"acquisitions":[],"comp'
    'onents":[]}'
)


def payload_operation_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_PAYLOAD_OPERATION_SPEC_JSON)


_DRIVER_FIXED_ACQUISITION_SPEC_JSON = (
    '{"id":"test.generated_driver_fixed_acqui'
    'sition/v1","label":null,"description":nu'
    'll,"properties":[],"operations":[],"acqu'
    'isitions":[{"id":"acquire","label":null,'
    '"description":null,"preconditions":[],"r'
    'esults":[{"id":"signal","label":null,"de'
    'scription":null,"role":"observable","dty'
    'pe":"complex128","unit":"ratio","axes":['
    '{"id":"sample","label":null,"description'
    '":null,"kind":"sample","size":2,"unit":n'
    'ull}]}]}],"components":[]}'
)


def driver_fixed_acquisition_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DRIVER_FIXED_ACQUISITION_SPEC_JSON)


_DRIVER_SOURCE_SPEC_JSON = (
    '{"id":"test.generated_driver_source/v1",'
    '"label":null,"description":null,"propert'
    'ies":[{"id":"enabled","label":null,"desc'
    'ription":null,"access":"read_write","cap'
    'ture":true,"restore":true,"value_type":{'
    '"type":"bool"}},{"id":"level","label":nu'
    'll,"description":null,"access":"read_wri'
    'te","capture":true,"restore":true,"value'
    '_type":{"type":"int","minimum":-90071992'
    '54740991,"maximum":9007199254740991}}],"'
    'operations":[],"acquisitions":[],"compon'
    'ents":[]}'
)


def driver_source_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DRIVER_SOURCE_SPEC_JSON)


_DRIVER_MONITOR_SPEC_JSON = (
    '{"id":"test.generated_driver_monitor/v1"'
    ',"label":null,"description":null,"proper'
    'ties":[{"id":"enabled","label":null,"des'
    'cription":null,"access":"read_write","ca'
    'pture":true,"restore":true,"value_type":'
    '{"type":"bool"}}],"operations":[],"acqui'
    'sitions":[{"id":"monitor","label":null,"'
    'description":null,"preconditions":[],"re'
    'sults":[{"id":"left_value","label":null,'
    '"description":null,"role":"observable","'
    'dtype":"float64","unit":null,"axes":[]},'
    '{"id":"right_value","label":null,"descri'
    'ption":null,"role":"observable","dtype":'
    '"float64","unit":null,"axes":[]}]}],"com'
    'ponents":[]}'
)


def driver_monitor_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DRIVER_MONITOR_SPEC_JSON)


__all__ = [
    "catalog_projection_interface",
    "driver_fixed_acquisition_interface",
    "driver_monitor_interface",
    "driver_source_interface",
    "literal_operation_interface",
    "payload_operation_interface",
    "scalar_operation_interface",
    "shared_property_first_interface",
    "shared_property_second_interface",
]
