# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver adapters generated from instrument interfaces."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Literal, cast

from pydantic import JsonValue
from scopecat.kernel.quantity import Quantity
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import (
    AcquisitionResultRef,
    DriverAcquisition,
    DriverOperation,
    DriverOutcome,
    DriverPayload,
    DriverReadback,
    DriverRejected,
    DriverScalar,
    DriverState,
    DriverStatePatch,
    DriverSuccess,
    PropertyRef,
)
from scopecat.sdk.problems import ProblemPhase, model_location, problem

from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    DriverMonitorState,
    DriverSourceState,
)
from scopecat_testkit.instrument_codegen_fixtures.generated_driver_states import (
    DriverMonitorDriverPatch,
    DriverSourceDriverPatch,
    decode_driver_monitor_patch,
    decode_driver_source_patch,
    encode_driver_monitor_state,
    encode_driver_source_state,
    encode_driver_state,
)
from scopecat_testkit.instrument_codegen_fixtures.generated_members import (
    DRIVER_FIXED_ACQUISITION_ACQUIRE,
    DRIVER_FIXED_ACQUISITION_RESPONSE_RESULT,
    DRIVER_MONITOR_ACQUISITION,
    DRIVER_MONITOR_LEFT_RESULT,
    DRIVER_MONITOR_RIGHT_RESULT,
    LITERAL_OPERATION_SELECT,
    PAYLOAD_OPERATION_UPLOAD,
    SCALAR_OPERATION_EMIT_PULSE,
)


def _unsupported_driver_request(
    instrument_id: str,
    kind: str,
    member_id: str,
) -> DriverRejected:
    return DriverRejected(
        problems=(
            problem(
                f"instrument_{kind}_not_implemented",
                f"{instrument_id} does not implement {member_id}",
                phase=ProblemPhase.EXECUTION,
                location=model_location(f"driver_{kind}", member_id),
            ),
        )
    )


@dataclass(frozen=True, slots=True)
class DriverFixedAcquisitionAcquireDriverReadback:
    response: MeasurementValue
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DriverMonitorMonitorDriverReadback:
    left: MeasurementValue
    right: MeasurementValue
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class ScalarOperationDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def handle_emit(
        self,
        count: int,
        /,
        width: Quantity,
        *,
        label: str,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        return encode_driver_state()

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        del request
        return _unsupported_driver_request(self.instrument_id, "state", "state")

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        if request.target == SCALAR_OPERATION_EMIT_PULSE:
            arguments = request.arguments
            outcome = self.handle_emit(
                cast("int", arguments["pulse_count"]),
                cast("Quantity", arguments["pulse_width"]),
                label=cast("str", arguments["pulse_label"]),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


class LiteralOperationDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def handle_select(
        self,
        mode: Literal["left", "right"],
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        return encode_driver_state()

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        del request
        return _unsupported_driver_request(self.instrument_id, "state", "state")

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        if request.target == LITERAL_OPERATION_SELECT:
            arguments = request.arguments
            outcome = self.handle_select(
                cast('Literal["left", "right"]', arguments["mode"]),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


class PayloadOperationDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def handle_upload(
        self,
        payload: bytes,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        return encode_driver_state()

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        del request
        return _unsupported_driver_request(self.instrument_id, "state", "state")

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        if request.target == PAYLOAD_OPERATION_UPLOAD:
            arguments = request.arguments
            outcome = self.handle_upload(
                cast("bytes", cast("DriverPayload", arguments["payload"]).value),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


class DriverFixedAcquisitionDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def handle_acquire(
        self,
    ) -> DriverOutcome[DriverFixedAcquisitionAcquireDriverReadback]: ...

    def read_state(self) -> DriverState:
        return encode_driver_state()

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        del request
        return _unsupported_driver_request(self.instrument_id, "state", "state")

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == DRIVER_FIXED_ACQUISITION_ACQUIRE:
            for result in request.results:
                if result not in (DRIVER_FIXED_ACQUISITION_RESPONSE_RESULT,):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_acquire = self.handle_acquire()
            if not isinstance(outcome_acquire, DriverSuccess):
                return outcome_acquire
            readback_acquire = outcome_acquire.value
            values_acquire: dict[AcquisitionResultRef, MeasurementValue] = {}
            if DRIVER_FIXED_ACQUISITION_RESPONSE_RESULT in request.results:
                values_acquire[DRIVER_FIXED_ACQUISITION_RESPONSE_RESULT] = (
                    readback_acquire.response
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_acquire,
                    metadata=readback_acquire.metadata,
                ),
                metadata=outcome_acquire.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class DriverSourceDriverSnapshot:
    state: DriverSourceState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class DriverSourceDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_driver_source_state(self) -> DriverSourceDriverSnapshot: ...

    @abstractmethod
    def apply_driver_source_state(
        self,
        patch: DriverSourceDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_driver_source_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_driver_source_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        driver_source_patch = decode_driver_source_patch(request)
        outcome = self.apply_driver_source_state(driver_source_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class MonitorCompositeDriverSnapshot:
    driver_source: DriverSourceState
    driver_monitor: DriverMonitorState | None
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class MonitorCompositeDriverPatch:
    driver_source: DriverSourceDriverPatch
    driver_monitor: DriverMonitorDriverPatch


class MonitorCompositeDriverAdapter(ABC):
    instrument_id: str

    def __init__(self, *, monitor: bool) -> None:
        self._driver_monitor_enabled = monitor

    @abstractmethod
    def read_monitor_composite_state(self) -> MonitorCompositeDriverSnapshot: ...

    @abstractmethod
    def apply_monitor_composite_state(
        self,
        patch: MonitorCompositeDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_monitor(
        self,
    ) -> DriverOutcome[DriverMonitorMonitorDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_monitor_composite_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_driver_source_state(snapshot.driver_source))
        if self._driver_monitor_enabled and snapshot.driver_monitor is not None:
            encoded.append(encode_driver_monitor_state(snapshot.driver_monitor))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        driver_source_patch = decode_driver_source_patch(request)
        driver_monitor_patch = decode_driver_monitor_patch(request)
        if driver_monitor_patch and not self._driver_monitor_enabled:
            return _unsupported_driver_request(
                self.instrument_id, "state", "test.generated_driver_monitor/v1"
            )
        outcome = self.apply_monitor_composite_state(
            MonitorCompositeDriverPatch(
                driver_source=driver_source_patch,
                driver_monitor=driver_monitor_patch,
            )
        )
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if (
            request.target == DRIVER_MONITOR_ACQUISITION
            and self._driver_monitor_enabled
        ):
            for result in request.results:
                if result not in (
                    DRIVER_MONITOR_LEFT_RESULT,
                    DRIVER_MONITOR_RIGHT_RESULT,
                ):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_monitor = self.handle_monitor()
            if not isinstance(outcome_monitor, DriverSuccess):
                return outcome_monitor
            readback_monitor = outcome_monitor.value
            values_monitor: dict[AcquisitionResultRef, MeasurementValue] = {}
            if DRIVER_MONITOR_LEFT_RESULT in request.results:
                values_monitor[DRIVER_MONITOR_LEFT_RESULT] = readback_monitor.left
            if DRIVER_MONITOR_RIGHT_RESULT in request.results:
                values_monitor[DRIVER_MONITOR_RIGHT_RESULT] = readback_monitor.right
            return DriverSuccess(
                DriverReadback(
                    values=values_monitor,
                    metadata=readback_monitor.metadata,
                ),
                metadata=outcome_monitor.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


__all__ = [
    "DriverFixedAcquisitionAcquireDriverReadback",
    "DriverFixedAcquisitionDriverAdapter",
    "DriverMonitorMonitorDriverReadback",
    "DriverSourceDriverAdapter",
    "DriverSourceDriverSnapshot",
    "LiteralOperationDriverAdapter",
    "MonitorCompositeDriverAdapter",
    "MonitorCompositeDriverPatch",
    "MonitorCompositeDriverSnapshot",
    "PayloadOperationDriverAdapter",
    "ScalarOperationDriverAdapter",
]
