# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed member projections generated from instrument interfaces."""

from __future__ import annotations

from scopecat.authoring import PerEntity, Symbolic
from scopecat.sdk.instruments.declarations import (
    MemberProjectionField,
    MemberProjectionLayout,
    instrument_member_projection,
    member_projection_field,
)

from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    CatalogProjectionInterface as CatalogProjectionInterface,
)
from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    DriverMonitorInterface as DriverMonitorInterface,
)
from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    DriverSourceInterface as DriverSourceInterface,
)
from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    SharedPropertyFirstInterface as SharedPropertyFirstInterface,
)
from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    SharedPropertySecondInterface as SharedPropertySecondInterface,
)
from scopecat_testkit.instrument_codegen_fixtures.generated_members import (
    CATALOG_PROJECTION_ENABLED,
    DRIVER_MONITOR_ENABLED,
    DRIVER_SOURCE_ENABLED,
    DRIVER_SOURCE_LEVEL,
    SHARED_PROPERTY_FIRST_ENABLED,
    SHARED_PROPERTY_SECOND_ENABLED,
)

_CATALOG_PROJECTION_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(MemberProjectionField("enabled", CATALOG_PROJECTION_ENABLED),),
)


@instrument_member_projection(_CATALOG_PROJECTION_MEMBER_LAYOUT)
class CatalogProjectionPatch:
    enabled: bool = member_projection_field()


@instrument_member_projection(_CATALOG_PROJECTION_MEMBER_LAYOUT)
class CatalogProjectionTarget:
    enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_CATALOG_PROJECTION_MEMBER_LAYOUT)
class CatalogProjectionGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = member_projection_field()


_SHARED_PROPERTY_FIRST_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(MemberProjectionField("enabled", SHARED_PROPERTY_FIRST_ENABLED),),
)


@instrument_member_projection(_SHARED_PROPERTY_FIRST_MEMBER_LAYOUT)
class SharedPropertyFirstPatch:
    enabled: bool = member_projection_field()


@instrument_member_projection(_SHARED_PROPERTY_FIRST_MEMBER_LAYOUT)
class SharedPropertyFirstTarget:
    enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_SHARED_PROPERTY_FIRST_MEMBER_LAYOUT)
class SharedPropertyFirstGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = member_projection_field()


_SHARED_PROPERTY_SECOND_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(MemberProjectionField("enabled", SHARED_PROPERTY_SECOND_ENABLED),),
)


@instrument_member_projection(_SHARED_PROPERTY_SECOND_MEMBER_LAYOUT)
class SharedPropertySecondPatch:
    enabled: bool = member_projection_field()


@instrument_member_projection(_SHARED_PROPERTY_SECOND_MEMBER_LAYOUT)
class SharedPropertySecondTarget:
    enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_SHARED_PROPERTY_SECOND_MEMBER_LAYOUT)
class SharedPropertySecondGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = member_projection_field()


_DRIVER_SOURCE_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("enabled", DRIVER_SOURCE_ENABLED),
        MemberProjectionField("level", DRIVER_SOURCE_LEVEL),
    ),
)


@instrument_member_projection(_DRIVER_SOURCE_MEMBER_LAYOUT)
class DriverSourcePatch:
    enabled: bool = member_projection_field()
    level: int = member_projection_field()


@instrument_member_projection(_DRIVER_SOURCE_MEMBER_LAYOUT)
class DriverSourceTarget:
    enabled: Symbolic[bool] = member_projection_field()
    level: Symbolic[int] = member_projection_field()


@instrument_member_projection(_DRIVER_SOURCE_MEMBER_LAYOUT)
class DriverSourceGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = member_projection_field()
    level: Symbolic[int] | PerEntity[Symbolic[int]] = member_projection_field()


_DRIVER_MONITOR_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(MemberProjectionField("enabled", DRIVER_MONITOR_ENABLED),),
)


@instrument_member_projection(_DRIVER_MONITOR_MEMBER_LAYOUT)
class DriverMonitorPatch:
    enabled: bool = member_projection_field()


@instrument_member_projection(_DRIVER_MONITOR_MEMBER_LAYOUT)
class DriverMonitorTarget:
    enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_DRIVER_MONITOR_MEMBER_LAYOUT)
class DriverMonitorGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = member_projection_field()


_MONITOR_COMPOSITE_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("source_enabled", DRIVER_SOURCE_ENABLED),
        MemberProjectionField("level", DRIVER_SOURCE_LEVEL),
        MemberProjectionField("monitor_enabled", DRIVER_MONITOR_ENABLED),
    ),
)


@instrument_member_projection(_MONITOR_COMPOSITE_MEMBER_LAYOUT)
class MonitorCompositePatch:
    source_enabled: bool = member_projection_field()
    level: int = member_projection_field()
    monitor_enabled: bool = member_projection_field()


@instrument_member_projection(_MONITOR_COMPOSITE_MEMBER_LAYOUT)
class MonitorCompositeTarget:
    source_enabled: Symbolic[bool] = member_projection_field()
    level: Symbolic[int] = member_projection_field()
    monitor_enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_MONITOR_COMPOSITE_MEMBER_LAYOUT)
class MonitorCompositeGroupTarget:
    source_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )
    level: Symbolic[int] | PerEntity[Symbolic[int]] = member_projection_field()
    monitor_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )


__all__ = [
    "CatalogProjectionGroupTarget",
    "CatalogProjectionInterface",
    "CatalogProjectionPatch",
    "CatalogProjectionTarget",
    "DriverMonitorGroupTarget",
    "DriverMonitorInterface",
    "DriverMonitorPatch",
    "DriverMonitorTarget",
    "DriverSourceGroupTarget",
    "DriverSourceInterface",
    "DriverSourcePatch",
    "DriverSourceTarget",
    "MonitorCompositeGroupTarget",
    "MonitorCompositePatch",
    "MonitorCompositeTarget",
    "SharedPropertyFirstGroupTarget",
    "SharedPropertyFirstInterface",
    "SharedPropertyFirstPatch",
    "SharedPropertyFirstTarget",
    "SharedPropertySecondGroupTarget",
    "SharedPropertySecondInterface",
    "SharedPropertySecondPatch",
    "SharedPropertySecondTarget",
]
