# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver state codecs generated from instrument interfaces."""

from __future__ import annotations

from collections.abc import Mapping
from typing import TypedDict, cast

from pydantic import JsonValue
from scopecat.sdk.instruments import (
    DriverScalar,
    DriverState,
    DriverStatePatch,
    PropertyRef,
)

from scopecat_testkit.instrument_codegen_fixtures.declarations import (
    CatalogProjectionState,
    DriverMonitorState,
    DriverSourceState,
    SharedFixtureState,
)
from scopecat_testkit.instrument_codegen_fixtures.generated_members import (
    CATALOG_PROJECTION_ENABLED,
    CATALOG_PROJECTION_STATUS,
    DRIVER_MONITOR_ENABLED,
    DRIVER_SOURCE_ENABLED,
    DRIVER_SOURCE_LEVEL,
    SHARED_STATE_FIRST_ENABLED,
    SHARED_STATE_SECOND_ENABLED,
)


class CatalogProjectionDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_catalog_projection_patch(
    request: DriverStatePatch, /
) -> CatalogProjectionDriverPatch:
    decoded: CatalogProjectionDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if CATALOG_PROJECTION_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[CATALOG_PROJECTION_ENABLED],
        )
    return decoded


def encode_catalog_projection_state(
    state: CatalogProjectionState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        CATALOG_PROJECTION_ENABLED: state.enabled,
        CATALOG_PROJECTION_STATUS: state.status,
    }


class SharedStateFirstDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_shared_state_first_patch(
    request: DriverStatePatch, /
) -> SharedStateFirstDriverPatch:
    decoded: SharedStateFirstDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if SHARED_STATE_FIRST_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[SHARED_STATE_FIRST_ENABLED],
        )
    return decoded


def encode_shared_state_first_state(
    state: SharedFixtureState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        SHARED_STATE_FIRST_ENABLED: state.enabled,
    }


class SharedStateSecondDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_shared_state_second_patch(
    request: DriverStatePatch, /
) -> SharedStateSecondDriverPatch:
    decoded: SharedStateSecondDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if SHARED_STATE_SECOND_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[SHARED_STATE_SECOND_ENABLED],
        )
    return decoded


def encode_shared_state_second_state(
    state: SharedFixtureState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        SHARED_STATE_SECOND_ENABLED: state.enabled,
    }


class DriverSourceDriverPatch(TypedDict, total=False):
    enabled: bool
    level: int


def decode_driver_source_patch(request: DriverStatePatch, /) -> DriverSourceDriverPatch:
    decoded: DriverSourceDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if DRIVER_SOURCE_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[DRIVER_SOURCE_ENABLED],
        )
    if DRIVER_SOURCE_LEVEL in values:
        decoded["level"] = cast(
            "int",
            values[DRIVER_SOURCE_LEVEL],
        )
    return decoded


def encode_driver_source_state(
    state: DriverSourceState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        DRIVER_SOURCE_ENABLED: state.enabled,
        DRIVER_SOURCE_LEVEL: state.level,
    }


class DriverMonitorDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_driver_monitor_patch(
    request: DriverStatePatch, /
) -> DriverMonitorDriverPatch:
    decoded: DriverMonitorDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if DRIVER_MONITOR_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[DRIVER_MONITOR_ENABLED],
        )
    return decoded


def encode_driver_monitor_state(
    state: DriverMonitorState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        DRIVER_MONITOR_ENABLED: state.enabled,
    }


def encode_driver_state(
    *states: Mapping[PropertyRef, DriverScalar],
    metadata: dict[str, JsonValue] | None = None,
) -> DriverState:
    values: dict[PropertyRef, DriverScalar] = {}
    for state in states:
        values.update(state)
    return DriverState(
        values=values,
        metadata={} if metadata is None else metadata,
    )


__all__ = [
    "CatalogProjectionDriverPatch",
    "DriverMonitorDriverPatch",
    "DriverSourceDriverPatch",
    "SharedStateFirstDriverPatch",
    "SharedStateSecondDriverPatch",
    "decode_catalog_projection_patch",
    "decode_driver_monitor_patch",
    "decode_driver_source_patch",
    "decode_shared_state_first_patch",
    "decode_shared_state_second_patch",
    "encode_catalog_projection_state",
    "encode_driver_monitor_state",
    "encode_driver_source_state",
    "encode_driver_state",
    "encode_shared_state_first_state",
    "encode_shared_state_second_state",
]
