/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type ContentHash = string;
export type DatasetRole = string | null;
export type Filename = string | null;
export type Id = string;
export type Kind = string;
export type MediaType = string | null;
export type ProducedBy = string | null;
export type Role = "artifact" | "dataset" | "record";
export type Schema = {
  [k: string]: unknown;
} | null;
export type Title = string | null;
export type RunId = string;
export type SchemaVersion = "scopecat.run_artifact_json_view.v1";
export type Content1 = string;
export type RunId1 = string;
export type SchemaVersion1 = "scopecat.run_artifact_text_view.v1";
export type SchemaVersion2 = "scopecat.attention_resolution_command.v1";
export type Description = string | null;
export type SchemaVersion3 = "scopecat.registered_experiment.v1";
export type Tags = string[];
export type Experiments = RegisteredExperimentDescriptor[];
export type SchemaVersion4 = "scopecat.experiment_catalog.v1";
export type DatasetId = string;
export type Records = unknown[];
export type DatasetId1 = string;
export type DatasetRole1 = "raw" | "derived";
export type Id1 = string;
export type Kind1 = string;
export type Label = string | null;
export type Size = number | null;
export type Unit = string | null;
export type Dimensions = MeasurementDimension[];
export type PrimaryCoordinates = string[];
export type PrimaryObservables = string[];
export type RecordSchema = string;
export type SchemaVersion5 = string;
export type AllowedUnits = string[];
export type Dims = string[];
export type Dtype = "float64" | "int64" | "complex128" | "bool" | "string";
export type Id2 = string;
export type Label1 = string | null;
export type MaskOf = string | null;
export type Role1 = "coordinate" | "observable" | "auxiliary" | "uncertainty" | "status" | "mask";
export type Shape = number[];
export type StatusOf = string | null;
export type UncertaintyOf = string | null;
export type Unit1 = string | null;
export type UnitPolicy = "uniform" | "per_record";
export type Variables = MeasurementVariable[];
export type Rows = {
  [k: string]: unknown;
}[];
export type Dtype1 = "float64" | "int64" | "bool" | "string";
export type Id3 = string;
export type Label2 = string | null;
export type Role2 =
  "identifier" | "coordinate" | "observable" | "auxiliary" | "uncertainty" | "status" | "mask" | "metadata";
export type Unit2 = string | null;
export type Columns = DataColumn[];
export type PrimaryKey = string[];
export type SchemaVersion6 = string;
export type SchemaVersion7 = string;
export type Id4 = string;
export type Kind2 = string;
export type Label3 = string | null;
export type Size1 = number;
export type Unit3 = string | null;
export type Dimensions1 = DataArrayDimension[];
export type PrimaryVariables = string[];
export type SchemaVersion8 = string;
export type Dims1 = string[];
export type Dtype2 = "float64" | "int64" | "bool" | "string";
export type Id5 = string;
export type Label4 = string | null;
export type MaskOf1 = string | null;
export type Role3 =
  "identifier" | "coordinate" | "observable" | "auxiliary" | "uncertainty" | "status" | "mask" | "metadata";
export type Shape1 = number[];
export type StatusOf1 = string | null;
export type UncertaintyOf1 = string | null;
export type Unit4 = string | null;
export type Variables1 = DataArrayVariable[];
export type SchemaVersion9 = string;
export type RunId2 = string;
export type SchemaVersion10 = "scopecat.run_dataset_content_view.v1";
export type EventId = number;
export type Kind3 = string;
export type OccurredAt = string;
export type RunId3 = string | null;
export type Items = DurableEvent[];
export type NextCursor = number | null;
export type ProjectId = string;
export type ProjectName = string;
export type ProjectRoot = string;
export type SchemaVersion11 = "scopecat.daemon_health.v2";
export type Status = "ok" | "degraded";
export type Items1 = unknown[];
export type NextOffset = number | null;
export type SchemaVersion12 = "scopecat.measurement_page.v1";
export type RunId4 = string;
export type SchemaVersion13 = "scopecat.run_record_json_view.v1";
export type Kind4 = "artifact" | "dataset" | "uri";
export type Role4 = string;
export type Target = string;
export type Title1 = string | null;
export type Inputs = AnalysisRecordInput[];
export type Key = string | null;
export type Kind5 = "note" | "table" | "array" | "figure" | "artifact" | "parameter_change_proposal";
export type Title2 = string;
export type Outputs = AnalysisRecordOutput[];
export type RunId5 = string;
export type SchemaVersion14 = "scopecat.analysis.v3";
export type StepId = string | null;
export type Title3 = string;
export type RunId6 = string;
export type SchemaVersion15 = "scopecat.run_analysis_view.v1";
export type Items2 = RunAnalysisView[];
export type RunId7 = string;
export type SchemaVersion16 = "scopecat.run_analysis_list_view.v1";
export type AdmittedAt = string;
export type ExperimentId = string;
export type Id6 = string;
export type ResourceClaims = ResourceKey[];
export type RunId8 = string;
export type SchemaVersion17 = "scopecat.run_admission.v1";
export type SubmissionId = string;
export type AttentionReason = string | null;
export type Certainty = "known" | "indeterminate";
export type FinishedAt = string;
/**
 * Stable machine-oriented classification independent of presentation.
 */
export type ProblemCategory =
  | "invalid_input"
  | "not_found"
  | "conflict"
  | "data_integrity"
  | "storage"
  | "provider_contract"
  | "unavailable"
  | "operation"
  | "external_failure"
  | "interrupted";
export type Code = string;
/**
 * Whether a problem only informs the caller or prevents an operation.
 */
export type ProblemImpact = "advisory" | "blocking";
export type Kind6 = "model";
export type Path = (string | number)[];
export type Root = string;
export type Kind7 = "storage";
export type Path1 = (string | number)[];
export type Ref = string | null;
export type RunId9 = string | null;
export type Column = number | string | null;
export type Kind8 = "external";
export type Path2 = (string | number)[];
export type Row = number | null;
export type Sheet = string | null;
export type Uri = string;
export type InstrumentId = string | null;
export type Kind9 = "runtime";
export type OperationId = string | null;
export type PointIndex = number | null;
export type RunId10 = string | null;
export type Message = string;
export type OccurrenceId = string | null;
/**
 * Pipeline boundary at which a problem was established.
 */
export type ProblemPhase =
  | "definition"
  | "authoring"
  | "configuration"
  | "planning"
  | "provider_preflight"
  | "execution"
  | "persistence"
  | "analysis"
  | "importing";
export type RelatedLocations = (ModelLocation | StorageLocation | ExternalLocation | RuntimeLocation)[];
export type SchemaVersion18 = "scopecat.problem.v1";
export type Problems = Problem[];
export type Result = "succeeded" | "failed" | "cancelled";
export type RunId11 = string;
export type SchemaVersion19 = "scopecat.run_outcome.v1";
export type TerminationReason = "completed" | "blocking_problem" | "effect_outcome_unknown" | "interrupted";
export type Sequence = number;
export type StateVersion = number;
export type UpdatedAt = string;
export type ConfigRef = string;
export type EntryId = string;
export type Kind10 = "config_registry";
export type RegistryGeneration = number | null;
export type SchemaVersion20 = "scopecat.config_registry_run_source.v1";
export type Selector = string;
/**
 * @minItems 1
 */
export type AnalysisRecordIds = [string, ...string[]];
export type Kind11 = "analysis_candidate";
/**
 * @minItems 1
 */
export type ProposalIds = [string, ...string[]];
export type SchemaVersion21 = "scopecat.analysis_candidate_run_source.v1";
export type SourceRunId = string;
export type Contents = RunContentEntry[];
export type CreatedAt = string;
export type Lifecycle = "accepted" | "running" | "terminal";
export type RunId12 = string;
export type SchemaVersion22 = "scopecat.run_manifest.v11";
export type ExpiresAt = string | null;
export type Status1 = "required" | "active" | "quarantined" | "released";
export type Resources = RunResourceView[];
export type SchemaVersion23 = "scopecat.run_detail.v1";
export type Items3 = ControlRun[];
export type NextCursor1 = number | null;
export type PreviousCursor = number | null;

export interface DaemonUiApi {
  artifactJson: RunArtifactJsonView;
  artifactText: RunArtifactTextView;
  attentionCommand: AttentionResolutionCommand;
  catalog: ExperimentCatalog;
  datasetContent: RunDatasetContentView;
  eventPage: EventPage;
  health: DaemonHealth;
  measurements: MeasurementPage;
  recordJson: RunRecordJsonView;
  runAnalyses: RunAnalysisListView;
  runDetail: RunDetail;
  runPage: RunPage;
}
export interface RunArtifactJsonView {
  artifact: RunContentEntry;
  content: Content;
  run_id: RunId;
  schema_version?: SchemaVersion;
}
/**
 * One content-addressable run-local manifest entry.
 */
export interface RunContentEntry {
  content_hash: ContentHash;
  dataset_role?: DatasetRole;
  filename?: Filename;
  id: Id;
  kind: Kind;
  media_type?: MediaType;
  metadata?: JsonMetadataOutput;
  produced_by?: ProducedBy;
  role: Role;
  schema?: Schema;
  title?: Title;
}
export interface JsonMetadataOutput {
  [k: string]: unknown;
}
export interface Content {
  [k: string]: unknown;
}
export interface RunArtifactTextView {
  artifact: RunContentEntry;
  content: Content1;
  run_id: RunId1;
  schema_version?: SchemaVersion1;
}
/**
 * Explicit operator decision for a quarantined run.
 */
export interface AttentionResolutionCommand {
  action: "release" | "requeue" | "abort";
  run_id: string;
  schema_version?: SchemaVersion2;
}
/**
 * A complete catalog snapshot addressable by an opaque revision.
 */
export interface ExperimentCatalog {
  experiments?: Experiments;
  revision: string;
  schema_version?: SchemaVersion4;
}
/**
 * Public catalog metadata for one explicitly versioned registration.
 */
export interface RegisteredExperimentDescriptor {
  description?: Description;
  experiment_kind: string;
  id: string;
  input_schema?: InputSchema;
  schema_version?: SchemaVersion3;
  tags?: Tags;
  title?: string | null;
  version: string;
}
export interface InputSchema {
  [k: string]: unknown;
}
export interface RunDatasetContentView {
  content: MeasurementDataset | DataTableArtifact | DataArrayArtifact;
  dataset: RunContentEntry;
  run_id: RunId2;
  schema_version?: SchemaVersion10;
}
export interface MeasurementDataset {
  dataset_id: DatasetId;
  metadata?: JsonMetadataOutput;
  records: Records;
  schema: MeasurementDatasetSchema;
}
export interface MeasurementDatasetSchema {
  dataset_id: DatasetId1;
  dataset_role: DatasetRole1;
  dimensions?: Dimensions;
  metadata?: JsonMetadataOutput;
  primary_coordinates?: PrimaryCoordinates;
  primary_observables?: PrimaryObservables;
  record_schema?: RecordSchema;
  schema_version?: SchemaVersion5;
  variables?: Variables;
}
export interface MeasurementDimension {
  id: Id1;
  kind: Kind1;
  label?: Label;
  metadata?: JsonMetadataOutput;
  size?: Size;
  unit?: Unit;
}
export interface MeasurementVariable {
  allowed_units?: AllowedUnits;
  dims?: Dims;
  dtype: Dtype;
  id: Id2;
  label?: Label1;
  mask_of?: MaskOf;
  metadata?: JsonMetadataOutput;
  role: Role1;
  shape?: Shape;
  status_of?: StatusOf;
  uncertainty_of?: UncertaintyOf;
  unit?: Unit1;
  unit_policy?: UnitPolicy;
}
export interface DataTableArtifact {
  rows: Rows;
  schema: DataTableSchema;
  schema_version?: SchemaVersion7;
}
export interface DataTableSchema {
  columns: Columns;
  metadata?: JsonMetadataOutput;
  primary_key?: PrimaryKey;
  schema_version?: SchemaVersion6;
}
export interface DataColumn {
  dtype: Dtype1;
  id: Id3;
  label?: Label2;
  metadata?: JsonMetadataOutput;
  role: Role2;
  unit?: Unit2;
}
export interface DataArrayArtifact {
  schema: DataArraySchema;
  schema_version?: SchemaVersion9;
  variables: Variables2;
}
export interface DataArraySchema {
  dimensions: Dimensions1;
  metadata?: JsonMetadataOutput;
  primary_variables?: PrimaryVariables;
  schema_version?: SchemaVersion8;
  variables: Variables1;
}
export interface DataArrayDimension {
  id: Id4;
  kind: Kind2;
  label?: Label3;
  metadata?: JsonMetadataOutput;
  size: Size1;
  unit?: Unit3;
}
export interface DataArrayVariable {
  dims?: Dims1;
  dtype: Dtype2;
  id: Id5;
  label?: Label4;
  mask_of?: MaskOf1;
  metadata?: JsonMetadataOutput;
  role: Role3;
  shape?: Shape1;
  status_of?: StatusOf1;
  uncertainty_of?: UncertaintyOf1;
  unit?: Unit4;
}
export interface Variables2 {
  [k: string]: unknown;
}
export interface EventPage {
  items: Items;
  next_cursor?: NextCursor;
  minItems?: 0;
}
export interface DurableEvent {
  event_id: EventId;
  kind: Kind3;
  occurred_at?: OccurredAt;
  payload?: Payload;
  run_id?: RunId3;
}
export interface Payload {
  [k: string]: unknown;
}
/**
 * Daemon readiness and the one project owned by this process.
 */
export interface DaemonHealth {
  project_id: ProjectId;
  project_name: ProjectName;
  project_root: ProjectRoot;
  schema_version?: SchemaVersion11;
  status: Status;
}
/**
 * Bounded raw-record preview for interactive browsing.
 */
export interface MeasurementPage {
  items?: Items1;
  next_offset?: NextOffset;
  schema_version?: SchemaVersion12;
  minItems?: 0;
}
export interface RunRecordJsonView {
  content: Content2;
  record: RunContentEntry;
  run_id: RunId4;
  schema_version?: SchemaVersion13;
}
export interface Content2 {
  [k: string]: unknown;
}
export interface RunAnalysisListView {
  items?: Items2;
  run_id: RunId7;
  schema_version?: SchemaVersion16;
  minItems?: 0;
}
/**
 * One persisted analysis record and its manifest identity.
 */
export interface RunAnalysisView {
  analysis: AnalysisRecord;
  entry: RunContentEntry;
  run_id: RunId6;
  schema_version?: SchemaVersion15;
}
export interface AnalysisRecord {
  inputs?: Inputs;
  key?: Key;
  outputs: Outputs;
  run_id: RunId5;
  schema_version?: SchemaVersion14;
  step_id?: StepId;
  title: Title3;
}
export interface AnalysisRecordInput {
  kind: Kind4;
  metadata?: JsonMetadataOutput | null;
  role: Role4;
  target: Target;
  title?: Title1;
}
export interface AnalysisRecordOutput {
  content: Content3;
  kind: Kind5;
  metadata?: JsonMetadataOutput;
  title: Title2;
}
export interface Content3 {
  [k: string]: unknown;
}
/**
 * Control and content state read from the same daemon.
 */
export interface RunDetail {
  control: ControlRun;
  manifest: RunManifest;
  resources?: Resources;
  schema_version?: SchemaVersion23;
}
/**
 * Current scheduler state plus the immutable admission record.
 */
export interface ControlRun {
  admission: RunAdmissionRecord;
  attention_reason?: AttentionReason;
  outcome?: RunOutcome | null;
  sequence: Sequence;
  state: "accepted" | "running" | "terminal" | "attention_required";
  state_version: StateVersion;
  updated_at: UpdatedAt;
}
/**
 * Inputs that must become durable before an executor can touch hardware.
 */
export interface RunAdmissionRecord {
  admitted_at?: AdmittedAt;
  config_content_hash: string;
  execution_mode: "managed" | "delegated";
  experiment_id: ExperimentId;
  plan_summary?: PlanSummary;
  request?: unknown;
  resource_claims?: ResourceClaims;
  run_id: RunId8;
  schema_version?: SchemaVersion17;
  submission_id: SubmissionId;
}
export interface PlanSummary {
  [k: string]: unknown;
}
/**
 * Canonical exclusive resource identity used by the scheduler.
 */
export interface ResourceKey {
  id: Id6;
  kind?: "target" | "instrument" | "channel" | "group";
}
/**
 * Immutable durable outcome established when one run becomes terminal.
 */
export interface RunOutcome {
  certainty: Certainty;
  finished_at?: FinishedAt;
  problems?: Problems;
  result: Result;
  run_id: RunId11;
  schema_version?: SchemaVersion19;
  termination_reason: TerminationReason;
}
/**
 * One expected, structured finding without presentation policy.
 */
export interface Problem {
  category: ProblemCategory;
  code: Code;
  details?: Details;
  impact: ProblemImpact;
  location?: (ModelLocation | StorageLocation | ExternalLocation | RuntimeLocation) | null;
  message: Message;
  occurrence_id?: OccurrenceId;
  phase: ProblemPhase;
  related_locations?: RelatedLocations;
  schema_version?: SchemaVersion18;
}
export interface Details {
  [k: string]: unknown;
}
/**
 * A path within a public model or transient compiler structure.
 */
export interface ModelLocation {
  kind?: Kind6;
  path?: Path;
  root: Root;
}
/**
 * A location in workspace storage or one durable run namespace.
 */
export interface StorageLocation {
  kind?: Kind7;
  path?: Path1;
  ref?: Ref;
  run_id?: RunId9;
}
/**
 * A location in an imported document or other external source.
 */
export interface ExternalLocation {
  column?: Column;
  kind?: Kind8;
  path?: Path2;
  row?: Row;
  sheet?: Sheet;
  uri: Uri;
}
/**
 * A location in a live or durably recorded run operation.
 */
export interface RuntimeLocation {
  instrument_id?: InstrumentId;
  kind?: Kind9;
  operation_id?: OperationId;
  point_index?: PointIndex;
  run_id?: RunId10;
}
export interface RunManifest {
  config_content_hash: string;
  config_source?: (ConfigRegistryRunConfigSource | AnalysisCandidateRunConfigSource) | null;
  contents?: Contents;
  created_at?: CreatedAt;
  lifecycle: Lifecycle;
  outcome?: RunOutcome | null;
  run_id: RunId12;
  schema_version?: SchemaVersion22;
}
export interface ConfigRegistryRunConfigSource {
  config_ref: ConfigRef;
  content_hash: string;
  entry_id: EntryId;
  kind?: Kind10;
  registry_generation?: RegistryGeneration;
  schema_version?: SchemaVersion20;
  selector: Selector;
}
/**
 * Analysis candidate resolved for one run without becoming the default.
 */
export interface AnalysisCandidateRunConfigSource {
  analysis_record_ids: AnalysisRecordIds;
  base_config_content_hash: string;
  content_hash: string;
  kind?: Kind11;
  proposal_ids: ProposalIds;
  schema_version?: SchemaVersion21;
  source_run_id: SourceRunId;
}
/**
 * Resource state without exposing an executor's authority token.
 */
export interface RunResourceView {
  expires_at?: ExpiresAt;
  resource: ResourceKey;
  status: Status1;
}
export interface RunPage {
  items: Items3;
  next_cursor?: NextCursor1;
  previous_cursor?: PreviousCursor;
  minItems?: 0;
}
