# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver state codecs generated from instrument interfaces."""

from __future__ import annotations

from collections.abc import Mapping
from typing import TypedDict, cast

from pydantic import JsonValue
from scopecat.sdk.instruments import (
    DriverScalar,
    DriverState,
    DriverStatePatch,
    PropertyRef,
)

from client_codegen_fixture_declarations import (
    CatalogProjectionObservation,
    CatalogProjectionState,
)
from generated_member_catalog_fixture import (
    CATALOG_PROJECTION_ENABLED,
    CATALOG_PROJECTION_STATUS,
)


class CatalogProjectionDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_catalog_projection_patch(
    request: DriverStatePatch, /
) -> CatalogProjectionDriverPatch:
    decoded: CatalogProjectionDriverPatch = {}
    values = request.values
    if CATALOG_PROJECTION_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[CATALOG_PROJECTION_ENABLED],
        )
    return decoded


def encode_catalog_projection_state(
    state: CatalogProjectionState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        CATALOG_PROJECTION_ENABLED: state.enabled,
    }


def encode_catalog_projection_observation(
    state: CatalogProjectionObservation, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        CATALOG_PROJECTION_STATUS: state.status,
    }


def encode_driver_state(
    *states: Mapping[PropertyRef, DriverScalar],
    metadata: dict[str, JsonValue] | None = None,
) -> DriverState:
    values: dict[PropertyRef, DriverScalar] = {}
    for state in states:
        values.update(state)
    return DriverState(
        values=values,
        metadata={} if metadata is None else metadata,
    )


__all__ = [
    "CatalogProjectionDriverPatch",
    "decode_catalog_projection_patch",
    "encode_catalog_projection_observation",
    "encode_catalog_projection_state",
    "encode_driver_state",
]
