# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed state projections generated from instrument interfaces."""

from __future__ import annotations

from scopecat.authoring import PerEntity, Symbolic
from scopecat.sdk.instruments.declarations import (
    StateProjectionField,
    StateProjectionLayout,
    instrument_state_projection,
    state_projection_field,
)

from client_codegen_fixture_declarations import (
    CatalogProjectionState as CatalogProjectionState,
)
from client_codegen_fixture_declarations import (
    DriverMonitorState as DriverMonitorState,
)
from client_codegen_fixture_declarations import (
    DriverSourceState as DriverSourceState,
)
from client_codegen_fixture_declarations import (
    SharedFixtureState as SharedFixtureState,
)
from generated_member_catalog_fixture import (
    CATALOG_PROJECTION_ENABLED,
    DRIVER_MONITOR_ENABLED,
    DRIVER_SOURCE_ENABLED,
    DRIVER_SOURCE_LEVEL,
    SHARED_STATE_FIRST_ENABLED,
    SHARED_STATE_SECOND_ENABLED,
)

_CATALOG_PROJECTION_STATE_LAYOUT = StateProjectionLayout(
    fields=(StateProjectionField("enabled", CATALOG_PROJECTION_ENABLED),),
)


@instrument_state_projection(_CATALOG_PROJECTION_STATE_LAYOUT)
class CatalogProjectionPatch:
    enabled: bool = state_projection_field()


@instrument_state_projection(_CATALOG_PROJECTION_STATE_LAYOUT)
class CatalogProjectionTarget:
    enabled: Symbolic[bool] = state_projection_field()


@instrument_state_projection(_CATALOG_PROJECTION_STATE_LAYOUT)
class CatalogProjectionGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = state_projection_field()


_SHARED_STATE_FIRST_STATE_LAYOUT = StateProjectionLayout(
    fields=(StateProjectionField("enabled", SHARED_STATE_FIRST_ENABLED),),
)


@instrument_state_projection(_SHARED_STATE_FIRST_STATE_LAYOUT)
class SharedStateFirstPatch:
    enabled: bool = state_projection_field()


@instrument_state_projection(_SHARED_STATE_FIRST_STATE_LAYOUT)
class SharedStateFirstTarget:
    enabled: Symbolic[bool] = state_projection_field()


@instrument_state_projection(_SHARED_STATE_FIRST_STATE_LAYOUT)
class SharedStateFirstGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = state_projection_field()


_SHARED_STATE_SECOND_STATE_LAYOUT = StateProjectionLayout(
    fields=(StateProjectionField("enabled", SHARED_STATE_SECOND_ENABLED),),
)


@instrument_state_projection(_SHARED_STATE_SECOND_STATE_LAYOUT)
class SharedStateSecondPatch:
    enabled: bool = state_projection_field()


@instrument_state_projection(_SHARED_STATE_SECOND_STATE_LAYOUT)
class SharedStateSecondTarget:
    enabled: Symbolic[bool] = state_projection_field()


@instrument_state_projection(_SHARED_STATE_SECOND_STATE_LAYOUT)
class SharedStateSecondGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = state_projection_field()


_DRIVER_SOURCE_STATE_LAYOUT = StateProjectionLayout(
    fields=(
        StateProjectionField("enabled", DRIVER_SOURCE_ENABLED),
        StateProjectionField("level", DRIVER_SOURCE_LEVEL),
    ),
)


@instrument_state_projection(_DRIVER_SOURCE_STATE_LAYOUT)
class DriverSourcePatch:
    enabled: bool = state_projection_field()
    level: int = state_projection_field()


@instrument_state_projection(_DRIVER_SOURCE_STATE_LAYOUT)
class DriverSourceTarget:
    enabled: Symbolic[bool] = state_projection_field()
    level: Symbolic[int] = state_projection_field()


@instrument_state_projection(_DRIVER_SOURCE_STATE_LAYOUT)
class DriverSourceGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = state_projection_field()
    level: Symbolic[int] | PerEntity[Symbolic[int]] = state_projection_field()


_DRIVER_MONITOR_STATE_LAYOUT = StateProjectionLayout(
    fields=(StateProjectionField("enabled", DRIVER_MONITOR_ENABLED),),
)


@instrument_state_projection(_DRIVER_MONITOR_STATE_LAYOUT)
class DriverMonitorPatch:
    enabled: bool = state_projection_field()


@instrument_state_projection(_DRIVER_MONITOR_STATE_LAYOUT)
class DriverMonitorTarget:
    enabled: Symbolic[bool] = state_projection_field()


@instrument_state_projection(_DRIVER_MONITOR_STATE_LAYOUT)
class DriverMonitorGroupTarget:
    enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = state_projection_field()


__all__ = [
    "CatalogProjectionGroupTarget",
    "CatalogProjectionPatch",
    "CatalogProjectionState",
    "CatalogProjectionTarget",
    "DriverMonitorGroupTarget",
    "DriverMonitorPatch",
    "DriverMonitorState",
    "DriverMonitorTarget",
    "DriverSourceGroupTarget",
    "DriverSourcePatch",
    "DriverSourceState",
    "DriverSourceTarget",
    "SharedFixtureState",
    "SharedStateFirstGroupTarget",
    "SharedStateFirstPatch",
    "SharedStateFirstTarget",
    "SharedStateSecondGroupTarget",
    "SharedStateSecondPatch",
    "SharedStateSecondTarget",
]
