# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver state codecs generated from instrument interfaces."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal, TypedDict, cast

from pydantic import JsonValue
from scopecat.sdk.instruments import (
    DriverScalar,
    DriverState,
    DriverStatePatch,
    PropertyRef,
)

from client_codegen_fixture_declarations import (
    CatalogProjectionState,
    DriverMonitorState,
    DriverSourceLeftState,
    DriverSourceRightState,
    SharedFixtureState,
)
from generated_member_catalog_fixture import (
    CATALOG_PROJECTION_ENABLED,
    CATALOG_PROJECTION_STATUS,
    DRIVER_MONITOR_ENABLED,
    DRIVER_SOURCE_ENABLED,
    DRIVER_SOURCE_LEFT_LEVEL,
    DRIVER_SOURCE_MODE,
    DRIVER_SOURCE_RIGHT_LEVEL,
    SHARED_STATE_FIRST_ENABLED,
    SHARED_STATE_SECOND_ENABLED,
)


class CatalogProjectionDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_catalog_projection_patch(
    request: DriverStatePatch, /
) -> CatalogProjectionDriverPatch:
    decoded: CatalogProjectionDriverPatch = {}
    values = request.values
    if CATALOG_PROJECTION_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[CATALOG_PROJECTION_ENABLED],
        )
    return decoded


def encode_catalog_projection_state(
    state: CatalogProjectionState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        CATALOG_PROJECTION_ENABLED: state.enabled,
        CATALOG_PROJECTION_STATUS: state.status,
    }


class SharedStateFirstDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_shared_state_first_patch(
    request: DriverStatePatch, /
) -> SharedStateFirstDriverPatch:
    decoded: SharedStateFirstDriverPatch = {}
    values = request.values
    if SHARED_STATE_FIRST_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[SHARED_STATE_FIRST_ENABLED],
        )
    return decoded


def encode_shared_state_first_state(
    state: SharedFixtureState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        SHARED_STATE_FIRST_ENABLED: state.enabled,
    }


class SharedStateSecondDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_shared_state_second_patch(
    request: DriverStatePatch, /
) -> SharedStateSecondDriverPatch:
    decoded: SharedStateSecondDriverPatch = {}
    values = request.values
    if SHARED_STATE_SECOND_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[SHARED_STATE_SECOND_ENABLED],
        )
    return decoded


def encode_shared_state_second_state(
    state: SharedFixtureState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        SHARED_STATE_SECOND_ENABLED: state.enabled,
    }


class DriverSourceDriverPatch(TypedDict, total=False):
    mode: Literal["left", "right"]
    enabled: bool
    left_level: int
    right_level: int


def decode_driver_source_patch(request: DriverStatePatch, /) -> DriverSourceDriverPatch:
    decoded: DriverSourceDriverPatch = {}
    values = request.values
    if DRIVER_SOURCE_MODE in values:
        decoded["mode"] = cast(
            'Literal["left", "right"]',
            values[DRIVER_SOURCE_MODE],
        )
    if DRIVER_SOURCE_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[DRIVER_SOURCE_ENABLED],
        )
    if DRIVER_SOURCE_LEFT_LEVEL in values:
        decoded["left_level"] = cast(
            "int",
            values[DRIVER_SOURCE_LEFT_LEVEL],
        )
    if DRIVER_SOURCE_RIGHT_LEVEL in values:
        decoded["right_level"] = cast(
            "int",
            values[DRIVER_SOURCE_RIGHT_LEVEL],
        )
    return decoded


def encode_driver_source_left_state(
    state: DriverSourceLeftState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        DRIVER_SOURCE_MODE: "left",
        DRIVER_SOURCE_ENABLED: state.enabled,
        DRIVER_SOURCE_LEFT_LEVEL: state.level,
    }


def encode_driver_source_right_state(
    state: DriverSourceRightState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        DRIVER_SOURCE_MODE: "right",
        DRIVER_SOURCE_ENABLED: state.enabled,
        DRIVER_SOURCE_RIGHT_LEVEL: state.level,
    }


class DriverMonitorDriverPatch(TypedDict, total=False):
    enabled: bool


def decode_driver_monitor_patch(
    request: DriverStatePatch, /
) -> DriverMonitorDriverPatch:
    decoded: DriverMonitorDriverPatch = {}
    values = request.values
    if DRIVER_MONITOR_ENABLED in values:
        decoded["enabled"] = cast(
            "bool",
            values[DRIVER_MONITOR_ENABLED],
        )
    return decoded


def encode_driver_monitor_state(
    state: DriverMonitorState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        DRIVER_MONITOR_ENABLED: state.enabled,
    }


def encode_driver_state(
    *states: Mapping[PropertyRef, DriverScalar],
    metadata: dict[str, JsonValue] | None = None,
) -> DriverState:
    values: dict[PropertyRef, DriverScalar] = {}
    for state in states:
        values.update(state)
    return DriverState(
        values=values,
        metadata={} if metadata is None else metadata,
    )


__all__ = [
    "CatalogProjectionDriverPatch",
    "DriverMonitorDriverPatch",
    "DriverSourceDriverPatch",
    "SharedStateFirstDriverPatch",
    "SharedStateSecondDriverPatch",
    "decode_catalog_projection_patch",
    "decode_driver_monitor_patch",
    "decode_driver_source_patch",
    "decode_shared_state_first_patch",
    "decode_shared_state_second_patch",
    "encode_catalog_projection_state",
    "encode_driver_monitor_state",
    "encode_driver_source_left_state",
    "encode_driver_source_right_state",
    "encode_driver_state",
    "encode_shared_state_first_state",
    "encode_shared_state_second_state",
]
