# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed live and symbolic clients generated from interface declarations."""

from __future__ import annotations

from scopecat.authoring import EachEntity, OneEntity, PerEntity, ValueRef
from scopecat.kernel.quantity import Quantity
from scopecat.sdk.instruments import InvokeReceipt
from scopecat.sdk.instruments.declarations import declared_interface_layout

from client_codegen_fixture_declarations import COMPONENT_OPERATION_DECLARATION
from scopecat_instruments._client_runtime import (
    InstrumentClientBase,
    InstrumentComponentClientBase,
)
from scopecat_instruments._family_runtime import InstrumentFamily
from scopecat_instruments._symbolic_runtime import (
    SymbolicInstrumentClientBase,
    SymbolicInstrumentComponentClientBase,
    SymbolicInstrumentComponentGroupBase,
    SymbolicInstrumentGroupBase,
    SymbolicInstrumentRecorder,
)

_COMPONENT_OPERATION_LAYOUT = declared_interface_layout(COMPONENT_OPERATION_DECLARATION)
_COMPONENT_OPERATION_OUTPUT_TRIGGER_EMIT_DECLARATION = (
    _COMPONENT_OPERATION_LAYOUT.root.components[0].components[0].operations[0]
)


class ComponentOperationOutputTriggerClient(InstrumentComponentClientBase):
    def emit(
        self,
        count: int,
        /,
        width: Quantity,
        *,
        label: str,
    ) -> InvokeReceipt:
        return self._invoke_declared(
            _COMPONENT_OPERATION_OUTPUT_TRIGGER_EMIT_DECLARATION,
            count,
            width,
            label=label,
        )


class ComponentOperationOutputClient(InstrumentComponentClientBase):
    @property
    def trigger(self) -> ComponentOperationOutputTriggerClient:
        return ComponentOperationOutputTriggerClient(self._owner)


class ComponentOperationClient(InstrumentClientBase):
    @property
    def output(self) -> ComponentOperationOutputClient:
        return ComponentOperationOutputClient(self)


class SymbolicComponentOperationOutputTriggerClient(
    SymbolicInstrumentComponentClientBase
):
    __slots__ = ()

    def emit(
        self,
        count: int | ValueRef,
        /,
        width: Quantity | ValueRef,
        *,
        label: str | ValueRef,
        effect_id: str | None = None,
    ) -> None:
        self._invoke_declared(
            _COMPONENT_OPERATION_OUTPUT_TRIGGER_EMIT_DECLARATION,
            effect_id,
            count,
            width,
            label=label,
        )


class SymbolicComponentOperationOutputClient(SymbolicInstrumentComponentClientBase):
    __slots__ = ()

    @property
    def trigger(self) -> SymbolicComponentOperationOutputTriggerClient:
        return SymbolicComponentOperationOutputTriggerClient(self._owner)


class SymbolicComponentOperationClient(SymbolicInstrumentClientBase):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(COMPONENT_OPERATION_DECLARATION.ref,),
            for_=for_,
        )

    @property
    def output(self) -> SymbolicComponentOperationOutputClient:
        return SymbolicComponentOperationOutputClient(self)


class SymbolicComponentOperationOutputTriggerGroup(
    SymbolicInstrumentComponentGroupBase[SymbolicComponentOperationOutputTriggerClient]
):
    __slots__ = ()

    def emit(
        self,
        count: int | ValueRef | PerEntity[int | ValueRef],
        /,
        width: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        *,
        label: str | ValueRef | PerEntity[str | ValueRef],
        effect_id: str | None = None,
    ) -> None:
        _count_by_entity = self._align(count)
        _width_by_entity = self._align(width)
        _label_by_entity = self._align(label)
        for entity in self._entities:
            self._clients[entity].emit(
                _count_by_entity[entity],
                _width_by_entity[entity],
                label=_label_by_entity[entity],
                effect_id=effect_id,
            )


class SymbolicComponentOperationOutputGroup(
    SymbolicInstrumentComponentGroupBase[SymbolicComponentOperationOutputClient]
):
    __slots__ = ()

    @property
    def trigger(self) -> SymbolicComponentOperationOutputTriggerGroup:
        return SymbolicComponentOperationOutputTriggerGroup(
            self._entities,
            self._clients.map(lambda client: client.trigger),
        )


class SymbolicComponentOperationGroup(
    SymbolicInstrumentGroupBase[SymbolicComponentOperationClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicComponentOperationClient,
        )

    @property
    def output(self) -> SymbolicComponentOperationOutputGroup:
        return SymbolicComponentOperationOutputGroup(
            self._entities,
            self._clients.map(lambda client: client.output),
        )


component_operation: InstrumentFamily[
    ComponentOperationClient,
    SymbolicComponentOperationClient,
    SymbolicComponentOperationGroup,
] = InstrumentFamily(
    ComponentOperationClient,
    SymbolicComponentOperationClient,
    SymbolicComponentOperationGroup,
    requires=(COMPONENT_OPERATION_DECLARATION.ref,),
)

__all__ = [
    "ComponentOperationClient",
    "ComponentOperationOutputClient",
    "ComponentOperationOutputTriggerClient",
    "SymbolicComponentOperationClient",
    "SymbolicComponentOperationGroup",
    "SymbolicComponentOperationOutputClient",
    "SymbolicComponentOperationOutputGroup",
    "SymbolicComponentOperationOutputTriggerClient",
    "SymbolicComponentOperationOutputTriggerGroup",
    "component_operation",
]
