# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Vendor-neutral interface factories generated from Python declarations."""

from __future__ import annotations

from scopecat.sdk.instruments import InterfaceSpec
from scopecat.sdk.instruments.declarations import compile_interface

from client_codegen_fixture_declarations import CatalogProjectionInterface


def catalog_projection_interface() -> InterfaceSpec:
    return compile_interface(CatalogProjectionInterface).fresh_spec()


__all__ = [
    "catalog_projection_interface",
]
