# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Vendor-neutral interface factories generated from Python declarations."""

from __future__ import annotations

from scopecat.sdk.instruments import InterfaceSpec

_CATALOG_PROJECTION_SPEC_JSON = (
    '{"id":"test.generated_catalog_projection'
    '/v1","label":null,"description":null,"pr'
    'operties":[{"id":"enabled","label":null,'
    '"description":null,"access":"read_write"'
    ',"value_type":{"type":"bool"}},{"id":"st'
    'atus","label":null,"description":null,"a'
    'ccess":"read_only","value_type":{"type":'
    '"string","choices":null}}],"operations":'
    '[],"acquisitions":[],"components":[]}'
)


def catalog_projection_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_CATALOG_PROJECTION_SPEC_JSON)


_SHARED_STATE_FIRST_SPEC_JSON = (
    '{"id":"test.generated_shared_state_first'
    '/v1","label":null,"description":null,"pr'
    'operties":[{"id":"enabled","label":null,'
    '"description":null,"access":"read_write"'
    ',"value_type":{"type":"bool"}}],"operati'
    'ons":[],"acquisitions":[],"components":['
    "]}"
)


def shared_state_first_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_SHARED_STATE_FIRST_SPEC_JSON)


_SHARED_STATE_SECOND_SPEC_JSON = (
    '{"id":"test.generated_shared_state_secon'
    'd/v1","label":null,"description":null,"p'
    'roperties":[{"id":"enabled","label":null'
    ',"description":null,"access":"read_write'
    '","value_type":{"type":"bool"}}],"operat'
    'ions":[],"acquisitions":[],"components":'
    "[]}"
)


def shared_state_second_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_SHARED_STATE_SECOND_SPEC_JSON)


_SCALAR_OPERATION_SPEC_JSON = (
    '{"id":"test.generated_scalar_operation/v'
    '1","label":null,"description":null,"prop'
    'erties":[],"operations":[{"id":"emit_pul'
    'se","label":null,"description":null,"arg'
    'uments":[{"id":"pulse_count","label":nul'
    'l,"description":null,"value_type":{"type'
    '":"int","minimum":-9007199254740991,"max'
    'imum":9007199254740991}},{"id":"pulse_wi'
    'dth","label":null,"description":null,"va'
    'lue_type":{"type":"quantity","dimension"'
    ':null,"unit":"s","minimum":null,"maximum'
    '":null,"finite":true}},{"id":"pulse_labe'
    'l","label":null,"description":null,"valu'
    'e_type":{"type":"string","choices":null}'
    '}]}],"acquisitions":[],"components":[]}'
)


def scalar_operation_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_SCALAR_OPERATION_SPEC_JSON)


_LITERAL_OPERATION_SPEC_JSON = (
    '{"id":"test.generated_literal_operation/'
    'v1","label":null,"description":null,"pro'
    'perties":[],"operations":[{"id":"select"'
    ',"label":null,"description":null,"argume'
    'nts":[{"id":"mode","label":null,"descrip'
    'tion":null,"value_type":{"type":"string"'
    ',"choices":["left","right"]}}]}],"acquis'
    'itions":[],"components":[]}'
)


def literal_operation_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_LITERAL_OPERATION_SPEC_JSON)


_PAYLOAD_OPERATION_SPEC_JSON = (
    '{"id":"test.generated_payload_operation/'
    'v1","label":null,"description":null,"pro'
    'perties":[],"operations":[{"id":"upload"'
    ',"label":null,"description":null,"argume'
    'nts":[{"id":"payload","label":null,"desc'
    'ription":null,"value_type":{"type":"payl'
    'oad","schema_id":"test.payload/v1"}}]}],'
    '"acquisitions":[],"components":[]}'
)


def payload_operation_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_PAYLOAD_OPERATION_SPEC_JSON)


_DRIVER_FIXED_ACQUISITION_SPEC_JSON = (
    '{"id":"test.generated_driver_fixed_acqui'
    'sition/v1","label":null,"description":nu'
    'll,"properties":[],"operations":[],"acqu'
    'isitions":[{"id":"acquire","label":null,'
    '"description":null,"preconditions":[],"r'
    'esults":[{"id":"signal","label":null,"de'
    'scription":null,"role":"observable","dty'
    'pe":"complex128","unit":"ratio","axes":['
    '{"id":"sample","label":null,"description'
    '":null,"kind":"sample","size":2,"unit":n'
    'ull}]}]}],"components":[]}'
)


def driver_fixed_acquisition_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DRIVER_FIXED_ACQUISITION_SPEC_JSON)


_DRIVER_SOURCE_SPEC_JSON = (
    '{"id":"test.generated_driver_source/v1",'
    '"label":null,"description":null,"propert'
    'ies":[{"id":"enabled","label":null,"desc'
    'ription":null,"access":"read_write","val'
    'ue_type":{"type":"bool"}},{"id":"level",'
    '"label":null,"description":null,"access"'
    ':"read_write","value_type":{"type":"int"'
    ',"minimum":-9007199254740991,"maximum":9'
    '007199254740991}}],"operations":[],"acqu'
    'isitions":[],"components":[]}'
)


def driver_source_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DRIVER_SOURCE_SPEC_JSON)


_DRIVER_MONITOR_SPEC_JSON = (
    '{"id":"test.generated_driver_monitor/v1"'
    ',"label":null,"description":null,"proper'
    'ties":[{"id":"enabled","label":null,"des'
    'cription":null,"access":"read_write","va'
    'lue_type":{"type":"bool"}}],"operations"'
    ':[],"acquisitions":[{"id":"monitor","lab'
    'el":null,"description":null,"preconditio'
    'ns":[],"results":[{"id":"left_value","la'
    'bel":null,"description":null,"role":"obs'
    'ervable","dtype":"float64","unit":null,"'
    'axes":[]},{"id":"right_value","label":nu'
    'll,"description":null,"role":"observable'
    '","dtype":"float64","unit":null,"axes":['
    ']}]}],"components":[]}'
)


def driver_monitor_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DRIVER_MONITOR_SPEC_JSON)


__all__ = [
    "catalog_projection_interface",
    "driver_fixed_acquisition_interface",
    "driver_monitor_interface",
    "driver_source_interface",
    "literal_operation_interface",
    "payload_operation_interface",
    "scalar_operation_interface",
    "shared_state_first_interface",
    "shared_state_second_interface",
]
