"""Generate typed first-party instrument clients from declared interfaces."""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from importlib import import_module
from pathlib import Path
from typing import cast, get_args, get_origin

from scopecat.sdk.instruments.declarations import (
    CompiledInterface,
    DeclaredAcquisition,
    declared_interface_layout,
)

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
OUTPUT = (
    REPOSITORY_ROOT
    / "packages"
    / "scopecat-instruments"
    / "src"
    / "scopecat_instruments"
    / "_generated_clients.py"
)


@dataclass(frozen=True, slots=True)
class ClientGenerationPolicy:
    """Non-structural inputs that a Python interface declaration cannot carry."""

    declaration_module: str
    declaration_symbol: str
    public_name_overrides: tuple[tuple[str, str], ...] = ()


class _Options(argparse.Namespace):
    check: bool = False


_POLICIES = (
    ClientGenerationPolicy(
        declaration_module="scopecat_instruments.interface_declarations",
        declaration_symbol="TEMPERATURE_READOUT_DECLARATION",
        public_name_overrides=(("sample.readback", "TemperatureReadback"),),
    ),
)


@dataclass(frozen=True, slots=True)
class _AcquisitionModel:
    index: int
    method_name: str
    descriptor_name: str
    result_type_name: str
    result_type_arguments: int
    readback_name: str
    products_name: str


@dataclass(frozen=True, slots=True)
class _InterfaceModel:
    declaration_module: str
    declaration_symbol: str
    constant_prefix: str
    interface_name: str
    stem: str
    factory_name: str
    observation_type_name: str
    acquisitions: tuple[_AcquisitionModel, ...]

    @property
    def live_client_name(self) -> str:
        return f"{self.stem}Client"

    @property
    def symbolic_client_name(self) -> str:
        return f"Symbolic{self.stem}Client"

    @property
    def symbolic_group_name(self) -> str:
        return f"Symbolic{self.stem}Group"


def render_generated_clients() -> str:
    """Render the complete deterministic generated client module."""

    models = tuple(_interface_model(policy) for policy in _POLICIES)
    declaration_imports = sorted(
        {
            symbol
            for model in models
            for symbol in (
                model.declaration_symbol,
                model.observation_type_name,
                *(item.result_type_name for item in model.acquisitions),
            )
        }
    )
    if len({model.declaration_module for model in models}) != 1:
        raise ValueError("the first generated slice requires one declaration module")
    declaration_module = models[0].declaration_module

    sections = [
        "# This file was auto-generated by scripts/generate_instrument_clients.py.\n"
        "# Do not make direct changes to the file.\n"
        '"""Typed live and symbolic clients generated from interface declarations."""\n'
        "\n"
        "from __future__ import annotations\n"
        "\n"
        "from dataclasses import dataclass, field\n"
        "from typing import cast\n"
        "\n"
        "from scopecat.authoring import EachEntity, OneEntity, PerEntity, ProductRef\n"
        "from scopecat.records.measurement import MeasurementValue\n"
        "from scopecat.sdk.instruments import CollectReceipt\n"
        "from scopecat.sdk.instruments.declarations import (\n"
        "    DeclaredObservedState,\n"
        "    declared_interface_layout,\n"
        ")\n"
        "\n"
        "from scopecat_instruments._client_runtime import InstrumentClientBase\n"
        "from scopecat_instruments._family_runtime import InstrumentFamily\n"
        "from scopecat_instruments._symbolic_runtime import (\n"
        "    SymbolicInstrumentClientBase,\n"
        "    SymbolicInstrumentGroupBase,\n"
        "    SymbolicInstrumentRecorder,\n"
        ")\n"
        f"from {declaration_module} import (\n"
        + "".join(f"    {symbol},\n" for symbol in declaration_imports)
        + ")\n"
    ]
    for model in models:
        sections.extend(
            (
                _render_descriptors(model),
                _render_result_types(model),
                _render_live_client(model),
                _render_symbolic_client(model),
                _render_symbolic_group(model),
                _render_family(model),
            )
        )

    exports = sorted(
        {
            name
            for model in models
            for name in (
                model.factory_name,
                model.live_client_name,
                model.observation_type_name,
                model.symbolic_client_name,
                model.symbolic_group_name,
                *(item.products_name for item in model.acquisitions),
                *(item.readback_name for item in model.acquisitions),
            )
        }
    )
    sections.append(
        "\n__all__ = [\n" + "".join(f'    "{name}",\n' for name in exports) + "]\n"
    )
    return "".join(sections)


def _interface_model(policy: ClientGenerationPolicy) -> _InterfaceModel:
    module = import_module(policy.declaration_module)
    compiled = cast(
        "CompiledInterface[object]",
        getattr(module, policy.declaration_symbol),
    )
    layout = declared_interface_layout(compiled)
    interface_name = compiled.interface_type.__name__
    stem = interface_name.removesuffix("Interface")
    overrides = dict(policy.public_name_overrides)
    assert layout.observed_state is not None
    observation = layout.observed_state.state_type
    acquisitions = tuple(
        _acquisition_model(
            acquisition,
            index=index,
            constant_prefix=policy.declaration_symbol.removesuffix("_DECLARATION"),
            overrides=overrides,
        )
        for index, acquisition in enumerate(layout.root.acquisitions)
    )
    return _InterfaceModel(
        declaration_module=policy.declaration_module,
        declaration_symbol=policy.declaration_symbol,
        constant_prefix=policy.declaration_symbol.removesuffix("_DECLARATION"),
        interface_name=interface_name,
        stem=stem,
        factory_name=overrides.get("factory", _snake_case(stem)),
        observation_type_name=observation.__name__,
        acquisitions=acquisitions,
    )


def _acquisition_model(
    acquisition: DeclaredAcquisition[object],
    *,
    index: int,
    constant_prefix: str,
    overrides: dict[str, str],
) -> _AcquisitionModel:
    result_alias = acquisition.layouts[0].result_type
    result_type = cast("type[object]", get_origin(result_alias) or result_alias)
    result_type_name = result_type.__name__
    result_stem = result_type_name.removesuffix("Results")
    method_name = acquisition.method_name
    return _AcquisitionModel(
        index=index,
        method_name=method_name,
        descriptor_name=f"_{constant_prefix}_{method_name.upper()}_DECLARATION",
        result_type_name=result_type_name,
        result_type_arguments=len(get_args(result_alias)),
        readback_name=overrides.get(
            f"{method_name}.readback",
            f"{result_stem}Readback",
        ),
        products_name=overrides.get(
            f"{method_name}.products",
            f"{result_stem}Products",
        ),
    )


def _render_descriptors(model: _InterfaceModel) -> str:
    layout_name = f"_{model.constant_prefix}_LAYOUT"
    observation_name = f"_{model.constant_prefix}_OBSERVATION_DECLARATION"
    acquisitions = "".join(
        f"{item.descriptor_name} = {layout_name}.root.acquisitions[\n"
        f"    {item.index}\n"
        "]\n"
        for item in model.acquisitions
    )
    return (
        "\n"
        f"{layout_name} = declared_interface_layout({model.declaration_symbol})\n"
        f"{observation_name} = cast(\n"
        f'    "DeclaredObservedState[{model.observation_type_name}]",\n'
        f"    {layout_name}.observed_state,\n"
        ")\n"
        f"{acquisitions}"
    )


def _render_result_types(model: _InterfaceModel) -> str:
    sections: list[str] = []
    for item in model.acquisitions:
        live_arguments = _type_arguments(
            "MeasurementValue | None",
            count=item.result_type_arguments,
        )
        product_arguments = _type_arguments(
            "ProductRef",
            count=item.result_type_arguments,
        )
        sections.append(
            "\n\n"
            "@dataclass(frozen=True, slots=True)\n"
            f"class {item.readback_name}({item.result_type_name}{live_arguments}):\n"
            f'    """Named {item.method_name} results plus their effect receipt."""\n'
            "\n"
            "    receipt: CollectReceipt = field(repr=False)\n"
            "\n\n"
            "@dataclass(frozen=True, slots=True)\n"
            f"class {item.products_name}({item.result_type_name}{product_arguments}):\n"
            f'    """Typed logical products produced by {item.method_name}."""\n'
        )
    return "".join(sections)


def _render_live_client(model: _InterfaceModel) -> str:
    observation_name = f"_{model.constant_prefix}_OBSERVATION_DECLARATION"
    acquisitions = "".join(
        "\n"
        f"    def {item.method_name}(self) -> {item.readback_name}:\n"
        "        return self._collect_declared(\n"
        f"            {item.descriptor_name},\n"
        f"            {item.readback_name},\n"
        "        )\n"
        for item in model.acquisitions
    )
    return (
        "\n\n"
        f"class {model.live_client_name}(InstrumentClientBase):\n"
        f"    def observation(self) -> {model.observation_type_name}:\n"
        f"        return {observation_name}.decode(\n"
        "            self._session.observed_state(self.instrument_id)\n"
        "        )\n"
        "\n"
        f"    def refresh_observation(self) -> {model.observation_type_name}:\n"
        f"        return {observation_name}.decode(\n"
        "            self._session.read_state(self.instrument_id)\n"
        "        )\n"
        f"{acquisitions}"
    )


def _render_symbolic_client(model: _InterfaceModel) -> str:
    acquisitions = "".join(
        "\n"
        f"    def {item.method_name}(\n"
        "        self,\n"
        "        *,\n"
        "        id: str | None = None,\n"
        f"    ) -> {item.products_name}:\n"
        "        return self._acquire_declared(\n"
        f"            {item.descriptor_name},\n"
        f"            {item.products_name},\n"
        "            id=id,\n"
        "        )\n"
        for item in model.acquisitions
    )
    return (
        "\n\n"
        f"class {model.symbolic_client_name}(SymbolicInstrumentClientBase):\n"
        "    __slots__ = ()\n"
        "\n"
        "    def __init__(\n"
        "        self,\n"
        "        recorder: SymbolicInstrumentRecorder,\n"
        "        resource_id: str,\n"
        "        *,\n"
        "        for_: OneEntity | None = None,\n"
        "    ) -> None:\n"
        "        super().__init__(\n"
        "            recorder,\n"
        "            resource_id,\n"
        f"            requires=({model.declaration_symbol}.ref,),\n"
        "            for_=for_,\n"
        "        )\n"
        f"{acquisitions}"
    )


def _render_symbolic_group(model: _InterfaceModel) -> str:
    acquisitions = "".join(
        "\n"
        f"    def {item.method_name}(\n"
        "        self,\n"
        "        *,\n"
        "        id: str | None = None,\n"
        f"    ) -> PerEntity[{item.products_name}]:\n"
        "        return self._clients.map("
        f"lambda client: client.{item.method_name}(id=id))\n"
        for item in model.acquisitions
    )
    return (
        "\n\n"
        f"class {model.symbolic_group_name}(\n"
        f"    SymbolicInstrumentGroupBase[{model.symbolic_client_name}]\n"
        "):\n"
        "    __slots__ = ()\n"
        "\n"
        "    def __init__(\n"
        "        self,\n"
        "        recorder: SymbolicInstrumentRecorder,\n"
        "        resource_id: str,\n"
        "        *,\n"
        "        for_: EachEntity,\n"
        "    ) -> None:\n"
        "        super().__init__(\n"
        "            recorder,\n"
        "            resource_id,\n"
        "            for_=for_,\n"
        f"            client_factory={model.symbolic_client_name},\n"
        "        )\n"
        f"{acquisitions}"
    )


def _render_family(model: _InterfaceModel) -> str:
    return (
        "\n\n"
        f"{model.factory_name}: InstrumentFamily[\n"
        f"    {model.live_client_name},\n"
        f"    {model.symbolic_client_name},\n"
        f"    {model.symbolic_group_name},\n"
        "] = InstrumentFamily(\n"
        f"    {model.live_client_name},\n"
        f"    {model.symbolic_client_name},\n"
        f"    {model.symbolic_group_name},\n"
        f"    requires=({model.declaration_symbol}.ref,),\n"
        ")\n"
    )


def _type_arguments(annotation: str, *, count: int) -> str:
    if count == 0:
        return ""
    return f"[{', '.join(annotation for _ in range(count))}]"


def _snake_case(name: str) -> str:
    words = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", words).lower()


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the committed generated source is stale",
    )
    options = _Options()
    parser.parse_args(argv, namespace=options)
    source = render_generated_clients()
    if options.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if existing != source:
            print(
                "generated instrument clients are stale; run "
                "`uv run python scripts/generate_instrument_clients.py`",
                file=sys.stderr,
            )
            raise SystemExit(1)
        return
    OUTPUT.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    main()
