# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
# ruff: noqa: F401
# pyright: reportUnusedImport=false, reportUnsupportedDunderAll=false
"""Generated typed and lazy instrument package facade."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from scopecat_instruments.clients import (
        DCBiasClient,
        DCBiasReadbackProducts,
        DCBiasReadbackReadback,
        DCMonitorClient,
        DCMonitorCurrentProducts,
        DCMonitorCurrentReadback,
        DCMonitorVoltageProducts,
        DCMonitorVoltageReadback,
        DCSourceClient,
        DCSourceMonitorClient,
        NetworkSweepClient,
        NetworkSweepProducts,
        NetworkSweepReadback,
        RFOutputClient,
        SymbolicDCBiasClient,
        SymbolicDCBiasGroup,
        SymbolicDCMonitorClient,
        SymbolicDCMonitorGroup,
        SymbolicDCSourceClient,
        SymbolicDCSourceGroup,
        SymbolicDCSourceMonitorClient,
        SymbolicDCSourceMonitorGroup,
        SymbolicNetworkSweepClient,
        SymbolicNetworkSweepGroup,
        SymbolicRFOutputClient,
        SymbolicRFOutputGroup,
        SymbolicTemperatureReadoutClient,
        SymbolicTemperatureReadoutGroup,
        TemperatureReadback,
        TemperatureReadoutClient,
        TemperatureSampleProducts,
        dc_bias,
        dc_monitor,
        dc_source,
        dc_source_monitor,
        network_sweep,
        rf_output,
        temperature_readout,
    )
    from scopecat_instruments.projections import (
        DCBiasGroupTarget,
        DCBiasInterface,
        DCBiasPatch,
        DCBiasTarget,
        DCMonitorGroupTarget,
        DCMonitorInterface,
        DCMonitorPatch,
        DCMonitorTarget,
        DCSourceGroupTarget,
        DCSourceInterface,
        DCSourcePatch,
        DCSourceTarget,
        NetworkSweepGroupTarget,
        NetworkSweepInterface,
        NetworkSweepPatch,
        NetworkSweepTarget,
        ReferenceSource,
        RFOutputGroupTarget,
        RFOutputInterface,
        RFOutputPatch,
        RFOutputTarget,
        SParameter,
        TemperatureReadoutInterface,
    )
    from scopecat_instruments.provider import ConfiguredInstrumentProvider


_PUBLIC_EXPORT_MODULES: dict[str, str] = {
    "ConfiguredInstrumentProvider": "scopecat_instruments.provider",
    "DCBiasClient": "scopecat_instruments.clients",
    "DCBiasGroupTarget": "scopecat_instruments.projections",
    "DCBiasInterface": "scopecat_instruments.projections",
    "DCBiasPatch": "scopecat_instruments.projections",
    "DCBiasReadbackProducts": "scopecat_instruments.clients",
    "DCBiasReadbackReadback": "scopecat_instruments.clients",
    "DCBiasTarget": "scopecat_instruments.projections",
    "DCMonitorClient": "scopecat_instruments.clients",
    "DCMonitorCurrentProducts": "scopecat_instruments.clients",
    "DCMonitorCurrentReadback": "scopecat_instruments.clients",
    "DCMonitorGroupTarget": "scopecat_instruments.projections",
    "DCMonitorInterface": "scopecat_instruments.projections",
    "DCMonitorPatch": "scopecat_instruments.projections",
    "DCMonitorTarget": "scopecat_instruments.projections",
    "DCMonitorVoltageProducts": "scopecat_instruments.clients",
    "DCMonitorVoltageReadback": "scopecat_instruments.clients",
    "DCSourceClient": "scopecat_instruments.clients",
    "DCSourceGroupTarget": "scopecat_instruments.projections",
    "DCSourceInterface": "scopecat_instruments.projections",
    "DCSourceMonitorClient": "scopecat_instruments.clients",
    "DCSourcePatch": "scopecat_instruments.projections",
    "DCSourceTarget": "scopecat_instruments.projections",
    "NetworkSweepClient": "scopecat_instruments.clients",
    "NetworkSweepGroupTarget": "scopecat_instruments.projections",
    "NetworkSweepInterface": "scopecat_instruments.projections",
    "NetworkSweepPatch": "scopecat_instruments.projections",
    "NetworkSweepProducts": "scopecat_instruments.clients",
    "NetworkSweepReadback": "scopecat_instruments.clients",
    "NetworkSweepTarget": "scopecat_instruments.projections",
    "RFOutputClient": "scopecat_instruments.clients",
    "RFOutputGroupTarget": "scopecat_instruments.projections",
    "RFOutputInterface": "scopecat_instruments.projections",
    "RFOutputPatch": "scopecat_instruments.projections",
    "RFOutputTarget": "scopecat_instruments.projections",
    "ReferenceSource": "scopecat_instruments.projections",
    "SParameter": "scopecat_instruments.projections",
    "SymbolicDCBiasClient": "scopecat_instruments.clients",
    "SymbolicDCBiasGroup": "scopecat_instruments.clients",
    "SymbolicDCMonitorClient": "scopecat_instruments.clients",
    "SymbolicDCMonitorGroup": "scopecat_instruments.clients",
    "SymbolicDCSourceClient": "scopecat_instruments.clients",
    "SymbolicDCSourceGroup": "scopecat_instruments.clients",
    "SymbolicDCSourceMonitorClient": "scopecat_instruments.clients",
    "SymbolicDCSourceMonitorGroup": "scopecat_instruments.clients",
    "SymbolicNetworkSweepClient": "scopecat_instruments.clients",
    "SymbolicNetworkSweepGroup": "scopecat_instruments.clients",
    "SymbolicRFOutputClient": "scopecat_instruments.clients",
    "SymbolicRFOutputGroup": "scopecat_instruments.clients",
    "SymbolicTemperatureReadoutClient": "scopecat_instruments.clients",
    "SymbolicTemperatureReadoutGroup": "scopecat_instruments.clients",
    "TemperatureReadback": "scopecat_instruments.clients",
    "TemperatureReadoutClient": "scopecat_instruments.clients",
    "TemperatureReadoutInterface": "scopecat_instruments.projections",
    "TemperatureSampleProducts": "scopecat_instruments.clients",
    "dc_bias": "scopecat_instruments.clients",
    "dc_monitor": "scopecat_instruments.clients",
    "dc_source": "scopecat_instruments.clients",
    "dc_source_monitor": "scopecat_instruments.clients",
    "network_sweep": "scopecat_instruments.clients",
    "rf_output": "scopecat_instruments.clients",
    "temperature_readout": "scopecat_instruments.clients",
}


def __getattr__(name: str) -> object:
    module = _PUBLIC_EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = cast("object", getattr(import_module(module), name))
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *_PUBLIC_EXPORT_MODULES})


__all__ = sorted(_PUBLIC_EXPORT_MODULES)
