# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
# ruff: noqa: F401
# pyright: reportUnusedImport=false, reportUnsupportedDunderAll=false
"""Generated typed and lazy instrument package facade."""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from scopecat_instruments.clients import (
        DCMonitorCurrentProducts,
        DCMonitorCurrentReadback,
        DCMonitorVoltageProducts,
        DCMonitorVoltageReadback,
        DCSourceClient,
        DCSourceMonitorClient,
        NetworkSweepClient,
        NetworkSweepProducts,
        NetworkSweepReadback,
        RFOutputClient,
        SymbolicDCSourceClient,
        SymbolicDCSourceGroup,
        SymbolicDCSourceMonitorClient,
        SymbolicDCSourceMonitorGroup,
        SymbolicInstrumentRecorder,
        SymbolicNetworkSweepClient,
        SymbolicNetworkSweepGroup,
        SymbolicRFOutputClient,
        SymbolicRFOutputGroup,
        SymbolicTemperatureReadoutClient,
        SymbolicTemperatureReadoutGroup,
        TemperatureReadback,
        TemperatureReadoutClient,
        TemperatureSampleProducts,
        dc_source,
        network_sweep,
        rf_output,
        temperature_readout,
    )
    from scopecat_instruments.provider import ConfiguredInstrumentProvider
    from scopecat_instruments.states import (
        DCMonitorGroupTarget,
        DCMonitorPatch,
        DCMonitorTarget,
        DCSourceGroupTarget,
        DCSourceObservation,
        DCSourcePatch,
        DCSourceTarget,
        NetworkSweepGroupTarget,
        NetworkSweepPatch,
        NetworkSweepTarget,
        ReferenceSource,
        RFOutputGroupTarget,
        RFOutputPatch,
        RFOutputTarget,
        SParameter,
        TemperatureReadoutObservation,
    )


_PUBLIC_EXPORT_MODULES: dict[str, str] = {
    "ConfiguredInstrumentProvider": "scopecat_instruments.provider",
    "DCMonitorCurrentProducts": "scopecat_instruments.clients",
    "DCMonitorCurrentReadback": "scopecat_instruments.clients",
    "DCMonitorGroupTarget": "scopecat_instruments.states",
    "DCMonitorPatch": "scopecat_instruments.states",
    "DCMonitorTarget": "scopecat_instruments.states",
    "DCMonitorVoltageProducts": "scopecat_instruments.clients",
    "DCMonitorVoltageReadback": "scopecat_instruments.clients",
    "DCSourceClient": "scopecat_instruments.clients",
    "DCSourceGroupTarget": "scopecat_instruments.states",
    "DCSourceMonitorClient": "scopecat_instruments.clients",
    "DCSourceObservation": "scopecat_instruments.states",
    "DCSourcePatch": "scopecat_instruments.states",
    "DCSourceTarget": "scopecat_instruments.states",
    "NetworkSweepClient": "scopecat_instruments.clients",
    "NetworkSweepGroupTarget": "scopecat_instruments.states",
    "NetworkSweepPatch": "scopecat_instruments.states",
    "NetworkSweepProducts": "scopecat_instruments.clients",
    "NetworkSweepReadback": "scopecat_instruments.clients",
    "NetworkSweepTarget": "scopecat_instruments.states",
    "RFOutputClient": "scopecat_instruments.clients",
    "RFOutputGroupTarget": "scopecat_instruments.states",
    "RFOutputPatch": "scopecat_instruments.states",
    "RFOutputTarget": "scopecat_instruments.states",
    "ReferenceSource": "scopecat_instruments.states",
    "SParameter": "scopecat_instruments.states",
    "SymbolicDCSourceClient": "scopecat_instruments.clients",
    "SymbolicDCSourceGroup": "scopecat_instruments.clients",
    "SymbolicDCSourceMonitorClient": "scopecat_instruments.clients",
    "SymbolicDCSourceMonitorGroup": "scopecat_instruments.clients",
    "SymbolicInstrumentRecorder": "scopecat_instruments.clients",
    "SymbolicNetworkSweepClient": "scopecat_instruments.clients",
    "SymbolicNetworkSweepGroup": "scopecat_instruments.clients",
    "SymbolicRFOutputClient": "scopecat_instruments.clients",
    "SymbolicRFOutputGroup": "scopecat_instruments.clients",
    "SymbolicTemperatureReadoutClient": "scopecat_instruments.clients",
    "SymbolicTemperatureReadoutGroup": "scopecat_instruments.clients",
    "TemperatureReadback": "scopecat_instruments.clients",
    "TemperatureReadoutClient": "scopecat_instruments.clients",
    "TemperatureReadoutObservation": "scopecat_instruments.states",
    "TemperatureSampleProducts": "scopecat_instruments.clients",
    "dc_source": "scopecat_instruments.clients",
    "network_sweep": "scopecat_instruments.clients",
    "rf_output": "scopecat_instruments.clients",
    "temperature_readout": "scopecat_instruments.clients",
}


def __getattr__(name: str) -> object:
    module = _PUBLIC_EXPORT_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    value = cast("object", getattr(import_module(module), name))
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *_PUBLIC_EXPORT_MODULES})


__all__ = sorted(_PUBLIC_EXPORT_MODULES)
