# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed live and symbolic clients generated from interface declarations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import cast

from scopecat.authoring import EachEntity, OneEntity, PerEntity, ProductRef
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import CollectReceipt
from scopecat.sdk.instruments.declarations import (
    DeclaredObservedState,
    declared_interface_layout,
)

from scopecat_instruments._client_runtime import (
    DeclaredStateClientBase,
    InstrumentClientBase,
)
from scopecat_instruments._family_runtime import InstrumentFamily
from scopecat_instruments._symbolic_runtime import (
    DeclaredStateSymbolicClientBase,
    DeclaredStateSymbolicGroupBase,
    SymbolicInstrumentClientBase,
    SymbolicInstrumentGroupBase,
    SymbolicInstrumentRecorder,
)
from scopecat_instruments.interface_declarations import (
    DC_SOURCE_DECLARATION,
    NETWORK_SWEEP_DECLARATION,
    RF_OUTPUT_DECLARATION,
    TEMPERATURE_READOUT_DECLARATION,
    DCSourceCurrent,
    DCSourceState,
    DCSourceVoltage,
    NetworkSweepResults,
    NetworkSweepState,
    RFOutputState,
    TemperatureReadoutObservation,
    TemperatureSampleResults,
)

_TEMPERATURE_READOUT_LAYOUT = declared_interface_layout(TEMPERATURE_READOUT_DECLARATION)
_TEMPERATURE_READOUT_OBSERVATION_DECLARATION = cast(
    "DeclaredObservedState[TemperatureReadoutObservation]",
    _TEMPERATURE_READOUT_LAYOUT.observed_state,
)
_TEMPERATURE_READOUT_SAMPLE_DECLARATION = _TEMPERATURE_READOUT_LAYOUT.root.acquisitions[
    0
]


@dataclass(frozen=True, slots=True)
class TemperatureReadback(TemperatureSampleResults[MeasurementValue | None]):
    """Named sample results plus their effect receipt."""

    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class TemperatureSampleProducts(TemperatureSampleResults[ProductRef]):
    """Typed logical products produced by sample."""


class TemperatureReadoutClient(InstrumentClientBase):
    def observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.observed_state(self.instrument_id)
        )

    def refresh_observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.read_state(self.instrument_id)
        )

    def sample(self) -> TemperatureReadback:
        return self._collect_declared(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureReadback,
        )


class SymbolicTemperatureReadoutClient(SymbolicInstrumentClientBase):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(TEMPERATURE_READOUT_DECLARATION.ref,),
            for_=for_,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> TemperatureSampleProducts:
        return self._acquire_declared(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureSampleProducts,
            id=id,
        )


class SymbolicTemperatureReadoutGroup(
    SymbolicInstrumentGroupBase[SymbolicTemperatureReadoutClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicTemperatureReadoutClient,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[TemperatureSampleProducts]:
        return self._clients.map(lambda client: client.sample(id=id))


temperature_readout: InstrumentFamily[
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
] = InstrumentFamily(
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
    requires=(TEMPERATURE_READOUT_DECLARATION.ref,),
)


class RFOutputClient(DeclaredStateClientBase[RFOutputState]):
    pass


class SymbolicRFOutputClient(DeclaredStateSymbolicClientBase[RFOutputState]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(RF_OUTPUT_DECLARATION.ref,),
            for_=for_,
        )


class SymbolicRFOutputGroup(
    DeclaredStateSymbolicGroupBase[RFOutputState, SymbolicRFOutputClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicRFOutputClient,
        )


rf_output: InstrumentFamily[
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
] = InstrumentFamily(
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
    requires=(RF_OUTPUT_DECLARATION.ref,),
)

type _DCSourceState = DCSourceState | DCSourceVoltage | DCSourceCurrent


class DCSourceClient(DeclaredStateClientBase[_DCSourceState]):
    pass


class SymbolicDCSourceClient(DeclaredStateSymbolicClientBase[_DCSourceState]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(DC_SOURCE_DECLARATION.ref,),
            for_=for_,
        )


class SymbolicDCSourceGroup(
    DeclaredStateSymbolicGroupBase[_DCSourceState, SymbolicDCSourceClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicDCSourceClient,
        )


_NETWORK_SWEEP_LAYOUT = declared_interface_layout(NETWORK_SWEEP_DECLARATION)
_NETWORK_SWEEP_SWEEP_DECLARATION = _NETWORK_SWEEP_LAYOUT.root.acquisitions[0]


@dataclass(frozen=True, slots=True)
class NetworkSweepReadback(
    NetworkSweepResults[MeasurementValue | None, MeasurementValue | None]
):
    """Named sweep results plus their effect receipt."""

    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class NetworkSweepProducts(NetworkSweepResults[ProductRef, ProductRef]):
    """Typed logical products produced by sweep."""


class NetworkSweepClient(DeclaredStateClientBase[NetworkSweepState]):
    def sweep(self) -> NetworkSweepReadback:
        return self._collect_declared(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepReadback,
        )


class SymbolicNetworkSweepClient(DeclaredStateSymbolicClientBase[NetworkSweepState]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(NETWORK_SWEEP_DECLARATION.ref,),
            for_=for_,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> NetworkSweepProducts:
        return self._acquire_declared(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepProducts,
            id=id,
        )


class SymbolicNetworkSweepGroup(
    DeclaredStateSymbolicGroupBase[NetworkSweepState, SymbolicNetworkSweepClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicNetworkSweepClient,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[NetworkSweepProducts]:
        return self._clients.map(lambda client: client.sweep(id=id))


network_sweep: InstrumentFamily[
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
] = InstrumentFamily(
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
    requires=(NETWORK_SWEEP_DECLARATION.ref,),
)

__all__ = [
    "DCSourceClient",
    "NetworkSweepClient",
    "NetworkSweepProducts",
    "NetworkSweepReadback",
    "RFOutputClient",
    "SymbolicDCSourceClient",
    "SymbolicDCSourceGroup",
    "SymbolicNetworkSweepClient",
    "SymbolicNetworkSweepGroup",
    "SymbolicRFOutputClient",
    "SymbolicRFOutputGroup",
    "SymbolicTemperatureReadoutClient",
    "SymbolicTemperatureReadoutGroup",
    "TemperatureReadback",
    "TemperatureReadoutClient",
    "TemperatureReadoutObservation",
    "TemperatureSampleProducts",
    "network_sweep",
    "rf_output",
    "temperature_readout",
]
