# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed live and symbolic clients generated from interface declarations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import cast

from scopecat.authoring import EachEntity, OneEntity, PerEntity, ProductRef
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import CollectReceipt
from scopecat.sdk.instruments.declarations import (
    DeclaredObservedState,
    declared_interface_layout,
)

from scopecat_instruments._client_runtime import InstrumentClientBase
from scopecat_instruments._family_runtime import InstrumentFamily
from scopecat_instruments._symbolic_runtime import (
    SymbolicInstrumentClientBase,
    SymbolicInstrumentGroupBase,
    SymbolicInstrumentRecorder,
)
from scopecat_instruments.interface_declarations import (
    TEMPERATURE_READOUT_DECLARATION,
    TemperatureReadoutObservation,
    TemperatureSampleResults,
)

_TEMPERATURE_READOUT_LAYOUT = declared_interface_layout(TEMPERATURE_READOUT_DECLARATION)
_TEMPERATURE_READOUT_OBSERVATION_DECLARATION = cast(
    "DeclaredObservedState[TemperatureReadoutObservation]",
    _TEMPERATURE_READOUT_LAYOUT.observed_state,
)
_TEMPERATURE_READOUT_SAMPLE_DECLARATION = _TEMPERATURE_READOUT_LAYOUT.root.acquisitions[
    0
]


@dataclass(frozen=True, slots=True)
class TemperatureReadback(TemperatureSampleResults[MeasurementValue | None]):
    """Named sample results plus their effect receipt."""

    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class TemperatureSampleProducts(TemperatureSampleResults[ProductRef]):
    """Typed logical products produced by sample."""


class TemperatureReadoutClient(InstrumentClientBase):
    def observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.observed_state(self.instrument_id)
        )

    def refresh_observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.read_state(self.instrument_id)
        )

    def sample(self) -> TemperatureReadback:
        return self._collect_declared(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureReadback,
        )


class SymbolicTemperatureReadoutClient(SymbolicInstrumentClientBase):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(TEMPERATURE_READOUT_DECLARATION.ref,),
            for_=for_,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> TemperatureSampleProducts:
        return self._acquire_declared(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureSampleProducts,
            id=id,
        )


class SymbolicTemperatureReadoutGroup(
    SymbolicInstrumentGroupBase[SymbolicTemperatureReadoutClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicTemperatureReadoutClient,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[TemperatureSampleProducts]:
        return self._clients.map(lambda client: client.sample(id=id))


temperature_readout: InstrumentFamily[
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
] = InstrumentFamily(
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
    requires=(TEMPERATURE_READOUT_DECLARATION.ref,),
)

__all__ = [
    "SymbolicTemperatureReadoutClient",
    "SymbolicTemperatureReadoutGroup",
    "TemperatureReadback",
    "TemperatureReadoutClient",
    "TemperatureReadoutObservation",
    "TemperatureSampleProducts",
    "temperature_readout",
]
