# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed live and symbolic clients generated from interface declarations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, overload, override

from scopecat.api._instruments import InstrumentRef, instrument
from scopecat.authoring import (
    EachEntity,
    EntitySelection,
    OneEntity,
    PerEntity,
    ProductRef,
    ValueRef,
)
from scopecat.kernel.quantity import Quantity
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import ApplyReceipt, CollectReceipt, InterfaceRef

from scopecat_instruments._client_runtime import (
    ClientAcquisition,
    ClientAcquisitionAxis,
    ClientAcquisitionLayout,
    ClientAcquisitionResult,
    ClientObservedField,
    ClientObservedState,
    DeclaredStateClientBase,
    InstrumentClientBase,
    client_property_value_type,
)
from scopecat_instruments._family_runtime import InstrumentFamily
from scopecat_instruments._symbolic_runtime import (
    DeclaredStateSymbolicClientBase,
    DeclaredStateSymbolicGroupBase,
    SymbolicInstrumentClientBase,
    SymbolicInstrumentGroupBase,
    SymbolicInstrumentRecorder,
)
from scopecat_instruments.interface_declarations import (
    DCMonitorResults,
    NetworkSweepResults,
    TemperatureReadoutObservation,
    TemperatureSampleResults,
)
from scopecat_instruments.states import (
    DCMonitorGroupTarget,
    DCMonitorPatch,
    DCMonitorTarget,
    DCSourceCurrentGroupTarget,
    DCSourceCurrentPatch,
    DCSourceCurrentTarget,
    DCSourceGroupTarget,
    DCSourcePatch,
    DCSourceTarget,
    DCSourceVoltageGroupTarget,
    DCSourceVoltagePatch,
    DCSourceVoltageTarget,
    NetworkSweepGroupTarget,
    NetworkSweepPatch,
    NetworkSweepTarget,
    RFOutputGroupTarget,
    RFOutputPatch,
    RFOutputTarget,
)

_TEMPERATURE_READOUT_REF = InterfaceRef("scopecat.temperature_readout/v1")

_RF_OUTPUT_REF = InterfaceRef("scopecat.rf_output/v1")

_DC_SOURCE_REF = InterfaceRef("scopecat.dc_source/v2")

_DC_MONITOR_REF = InterfaceRef("scopecat.dc_monitor/v3")

_NETWORK_SWEEP_REF = InterfaceRef("scopecat.network_sweep/v1")

_TEMPERATURE_READOUT_OBSERVATION_DECLARATION = ClientObservedState(
    TemperatureReadoutObservation,
    fields=(
        ClientObservedField(
            "scan_channel",
            InterfaceRef("scopecat.temperature_readout/v1").property("scan_channel"),
            client_property_value_type('{"type":"int","minimum":1,"maximum":16}'),
        ),
        ClientObservedField(
            "autoscan_enabled",
            InterfaceRef("scopecat.temperature_readout/v1").property(
                "autoscan_enabled"
            ),
            client_property_value_type('{"type":"bool"}'),
        ),
    ),
)

_TEMPERATURE_READOUT_SAMPLE_DECLARATION = ClientAcquisition(
    ref=_TEMPERATURE_READOUT_REF.acquisition("sample"),
    discriminator=None,
    layouts=(
        ClientAcquisitionLayout(
            case_value=None,
            fields=(
                ClientAcquisitionResult(
                    "temperature",
                    _TEMPERATURE_READOUT_REF.acquisition("sample").result(
                        "temperature"
                    ),
                    dtype="float64",
                    unit="K",
                    axes=(),
                ),
                ClientAcquisitionResult(
                    "resistance",
                    _TEMPERATURE_READOUT_REF.acquisition("sample").result("resistance"),
                    dtype="float64",
                    unit="Ohm",
                    axes=(),
                ),
            ),
        ),
    ),
)

_DC_MONITOR_MONITOR_DECLARATION = ClientAcquisition(
    ref=_DC_MONITOR_REF.acquisition("monitor"),
    discriminator=InterfaceRef("scopecat.dc_source/v2").property("source_mode"),
    layouts=(
        ClientAcquisitionLayout(
            case_value="voltage",
            fields=(
                ClientAcquisitionResult(
                    "current",
                    _DC_MONITOR_REF.acquisition("monitor").result("monitored_current"),
                    dtype="float64",
                    unit="A",
                    axes=(),
                ),
            ),
        ),
        ClientAcquisitionLayout(
            case_value="current",
            fields=(
                ClientAcquisitionResult(
                    "voltage",
                    _DC_MONITOR_REF.acquisition("monitor").result("monitored_voltage"),
                    dtype="float64",
                    unit="V",
                    axes=(),
                ),
            ),
        ),
    ),
)

_NETWORK_SWEEP_SWEEP_DECLARATION = ClientAcquisition(
    ref=_NETWORK_SWEEP_REF.acquisition("sweep"),
    discriminator=None,
    layouts=(
        ClientAcquisitionLayout(
            case_value=None,
            fields=(
                ClientAcquisitionResult(
                    "frequency",
                    _NETWORK_SWEEP_REF.acquisition("sweep").result("frequency"),
                    dtype="float64",
                    unit="Hz",
                    axes=(
                        ClientAcquisitionAxis(
                            id="frequency",
                            size=InterfaceRef("scopecat.network_sweep/v1").property(
                                "points"
                            ),
                            kind="frequency",
                            unit="Hz",
                        ),
                    ),
                ),
                ClientAcquisitionResult(
                    "s_parameter",
                    _NETWORK_SWEEP_REF.acquisition("sweep").result("s_parameter"),
                    dtype="complex128",
                    unit="ratio",
                    axes=(
                        ClientAcquisitionAxis(
                            id="frequency",
                            size=InterfaceRef("scopecat.network_sweep/v1").property(
                                "points"
                            ),
                            kind="frequency",
                            unit="Hz",
                        ),
                    ),
                ),
            ),
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class TemperatureReadback(TemperatureSampleResults[MeasurementValue | None]):
    """Named sample results plus their effect receipt."""

    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class TemperatureSampleProducts(TemperatureSampleResults[ProductRef]):
    """Typed logical products produced by sample."""


class TemperatureReadoutClient(InstrumentClientBase):
    def observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.observed_state(self.instrument_id)
        )

    def refresh_observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.read_state(self.instrument_id)
        )

    def sample(self) -> TemperatureReadback:
        return self._collect(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureReadback,
        )


class SymbolicTemperatureReadoutClient(SymbolicInstrumentClientBase):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_TEMPERATURE_READOUT_REF,),
            for_=for_,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> TemperatureSampleProducts:
        return self._acquire(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureSampleProducts,
            id=id,
        )


class SymbolicTemperatureReadoutGroup(
    SymbolicInstrumentGroupBase[SymbolicTemperatureReadoutClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicTemperatureReadoutClient,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[TemperatureSampleProducts]:
        return self._clients.map(lambda client: client.sample(id=id))


temperature_readout: InstrumentFamily[
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
] = InstrumentFamily(
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
    requires=(_TEMPERATURE_READOUT_REF,),
)


class RFOutputClient(DeclaredStateClientBase[RFOutputPatch]):
    @overload
    def apply(
        self,
        patch: RFOutputPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        frequency: Quantity = ...,
        power: Quantity = ...,
        output_enabled: bool = ...,
        reference_source: Literal["internal", "external"] = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: RFOutputPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            RFOutputPatch,
            fields,
        )


class SymbolicRFOutputClient(DeclaredStateSymbolicClientBase[RFOutputTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_RF_OUTPUT_REF,),
            for_=for_,
        )

    @overload
    def ensure(
        self,
        state: RFOutputTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        frequency: Quantity | ValueRef = ...,
        power: Quantity | ValueRef = ...,
        output_enabled: bool | ValueRef = ...,
        reference_source: Literal["internal", "external"] | ValueRef = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: RFOutputTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            RFOutputTarget,
            fields,
        )


class SymbolicRFOutputGroup(
    DeclaredStateSymbolicGroupBase[
        RFOutputTarget, RFOutputGroupTarget, SymbolicRFOutputClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicRFOutputClient,
        )

    @overload
    def ensure(
        self,
        state: RFOutputGroupTarget | PerEntity[RFOutputTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = ...,
        reference_source: (
            Literal["internal", "external"]
            | ValueRef
            | PerEntity[Literal["internal", "external"] | ValueRef]
        ) = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: RFOutputGroupTarget | PerEntity[RFOutputTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            RFOutputGroupTarget,
            fields,
        )


rf_output: InstrumentFamily[
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
] = InstrumentFamily(
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
    requires=(_RF_OUTPUT_REF,),
)


type _DCSourcePatch = DCSourcePatch | DCSourceVoltagePatch | DCSourceCurrentPatch


type _DCSourceTarget = DCSourceTarget | DCSourceVoltageTarget | DCSourceCurrentTarget


type _DCSourceGroupTarget = (
    DCSourceGroupTarget | DCSourceVoltageGroupTarget | DCSourceCurrentGroupTarget
)


class DCSourceClient(DeclaredStateClientBase[_DCSourcePatch]):
    pass


class SymbolicDCSourceClient(DeclaredStateSymbolicClientBase[_DCSourceTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_DC_SOURCE_REF,),
            for_=for_,
        )


class SymbolicDCSourceGroup(
    DeclaredStateSymbolicGroupBase[
        _DCSourceTarget, _DCSourceGroupTarget, SymbolicDCSourceClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicDCSourceClient,
        )


type _DCSourceMonitorPatch = (
    DCSourcePatch | DCSourceVoltagePatch | DCSourceCurrentPatch | DCMonitorPatch
)


type _DCSourceMonitorTarget = (
    DCSourceTarget | DCSourceVoltageTarget | DCSourceCurrentTarget | DCMonitorTarget
)


type _DCSourceMonitorGroupTarget = (
    DCSourceGroupTarget
    | DCSourceVoltageGroupTarget
    | DCSourceCurrentGroupTarget
    | DCMonitorGroupTarget
)


@dataclass(frozen=True, slots=True)
class DCMonitorReadback(DCMonitorResults[MeasurementValue | None]):
    """Named monitor results plus their effect receipt."""

    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class DCMonitorProducts(DCMonitorResults[ProductRef]):
    """Typed logical products produced by monitor."""


class DCSourceMonitorClient(DeclaredStateClientBase[_DCSourceMonitorPatch]):
    def monitor(self) -> DCMonitorReadback:
        return self._collect(
            _DC_MONITOR_MONITOR_DECLARATION,
            DCMonitorReadback,
        )


class SymbolicDCSourceMonitorClient(
    DeclaredStateSymbolicClientBase[_DCSourceMonitorTarget]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_DC_SOURCE_REF, _DC_MONITOR_REF),
            for_=for_,
        )

    def monitor(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorProducts:
        return self._acquire(
            _DC_MONITOR_MONITOR_DECLARATION,
            DCMonitorProducts,
            id=id,
        )


class SymbolicDCSourceMonitorGroup(
    DeclaredStateSymbolicGroupBase[
        _DCSourceMonitorTarget,
        _DCSourceMonitorGroupTarget,
        SymbolicDCSourceMonitorClient,
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicDCSourceMonitorClient,
        )

    def monitor(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorProducts]:
        return self._clients.map(lambda client: client.monitor(id=id))


@dataclass(frozen=True, slots=True)
class NetworkSweepReadback(
    NetworkSweepResults[MeasurementValue | None, MeasurementValue | None]
):
    """Named sweep results plus their effect receipt."""

    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class NetworkSweepProducts(NetworkSweepResults[ProductRef, ProductRef]):
    """Typed logical products produced by sweep."""


class NetworkSweepClient(DeclaredStateClientBase[NetworkSweepPatch]):
    @overload
    def apply(
        self,
        patch: NetworkSweepPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        start_frequency: Quantity = ...,
        stop_frequency: Quantity = ...,
        points: int = ...,
        if_bandwidth: Quantity = ...,
        source_power: Quantity = ...,
        s_parameter: Literal["S11", "S21", "S12", "S22"] = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: NetworkSweepPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            NetworkSweepPatch,
            fields,
        )

    def sweep(self) -> NetworkSweepReadback:
        return self._collect(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepReadback,
        )


class SymbolicNetworkSweepClient(DeclaredStateSymbolicClientBase[NetworkSweepTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_NETWORK_SWEEP_REF,),
            for_=for_,
        )

    @overload
    def ensure(
        self,
        state: NetworkSweepTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        start_frequency: Quantity | ValueRef = ...,
        stop_frequency: Quantity | ValueRef = ...,
        points: int | ValueRef = ...,
        if_bandwidth: Quantity | ValueRef = ...,
        source_power: Quantity | ValueRef = ...,
        s_parameter: Literal["S11", "S21", "S12", "S22"] | ValueRef = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: NetworkSweepTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            NetworkSweepTarget,
            fields,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> NetworkSweepProducts:
        return self._acquire(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepProducts,
            id=id,
        )


class SymbolicNetworkSweepGroup(
    DeclaredStateSymbolicGroupBase[
        NetworkSweepTarget, NetworkSweepGroupTarget, SymbolicNetworkSweepClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicNetworkSweepClient,
        )

    @overload
    def ensure(
        self,
        state: NetworkSweepGroupTarget | PerEntity[NetworkSweepTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        start_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        stop_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        points: int | ValueRef | PerEntity[int | ValueRef] = ...,
        if_bandwidth: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        source_power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        s_parameter: (
            Literal["S11", "S21", "S12", "S22"]
            | ValueRef
            | PerEntity[Literal["S11", "S21", "S12", "S22"] | ValueRef]
        ) = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: NetworkSweepGroupTarget | PerEntity[NetworkSweepTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            NetworkSweepGroupTarget,
            fields,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[NetworkSweepProducts]:
        return self._clients.map(lambda client: client.sweep(id=id))


network_sweep: InstrumentFamily[
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
] = InstrumentFamily(
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
    requires=(_NETWORK_SWEEP_REF,),
)


@overload
def dc_source(
    instrument_id: str,
    *,
    monitor: Literal[False] = False,
) -> InstrumentRef[DCSourceClient]: ...


@overload
def dc_source(
    instrument_id: str,
    *,
    monitor: Literal[True],
) -> InstrumentRef[DCSourceMonitorClient]: ...


@overload
def dc_source(
    instrument_id: str,
    *,
    monitor: bool,
) -> InstrumentRef[DCSourceClient] | InstrumentRef[DCSourceMonitorClient]: ...


@overload
def dc_source(
    instrument_id: SymbolicInstrumentRecorder,
    resource_id: str,
    *,
    for_: EachEntity,
    monitor: Literal[False] = False,
) -> SymbolicDCSourceGroup: ...


@overload
def dc_source(
    instrument_id: SymbolicInstrumentRecorder,
    resource_id: str,
    *,
    for_: EachEntity,
    monitor: Literal[True],
) -> SymbolicDCSourceMonitorGroup: ...


@overload
def dc_source(
    instrument_id: SymbolicInstrumentRecorder,
    resource_id: str,
    *,
    for_: EachEntity,
    monitor: bool,
) -> SymbolicDCSourceGroup | SymbolicDCSourceMonitorGroup: ...


@overload
def dc_source(
    instrument_id: SymbolicInstrumentRecorder,
    resource_id: str,
    *,
    for_: OneEntity | None = None,
    monitor: Literal[False] = False,
) -> SymbolicDCSourceClient: ...


@overload
def dc_source(
    instrument_id: SymbolicInstrumentRecorder,
    resource_id: str,
    *,
    for_: OneEntity | None = None,
    monitor: Literal[True],
) -> SymbolicDCSourceMonitorClient: ...


@overload
def dc_source(
    instrument_id: SymbolicInstrumentRecorder,
    resource_id: str,
    *,
    for_: OneEntity | None = None,
    monitor: bool,
) -> SymbolicDCSourceClient | SymbolicDCSourceMonitorClient: ...


def dc_source(
    instrument_id: str | SymbolicInstrumentRecorder,
    resource_id: str | None = None,
    *,
    for_: EntitySelection | None = None,
    monitor: bool = False,
) -> (
    InstrumentRef[DCSourceClient]
    | InstrumentRef[DCSourceMonitorClient]
    | SymbolicDCSourceClient
    | SymbolicDCSourceGroup
    | SymbolicDCSourceMonitorClient
    | SymbolicDCSourceMonitorGroup
):
    if isinstance(instrument_id, str):
        if resource_id is not None or for_ is not None:
            raise TypeError("live instrument clients only accept an instrument id")
        if monitor:
            return instrument(
                instrument_id,
                DCSourceMonitorClient,
                requires=(_DC_SOURCE_REF, _DC_MONITOR_REF),
            )
        return instrument(
            instrument_id,
            DCSourceClient,
            requires=(_DC_SOURCE_REF,),
        )
    if resource_id is None:
        raise TypeError("symbolic instrument clients require a logical resource id")
    if isinstance(for_, EachEntity):
        if monitor:
            return SymbolicDCSourceMonitorGroup(
                instrument_id,
                resource_id,
                for_=for_,
            )
        return SymbolicDCSourceGroup(
            instrument_id,
            resource_id,
            for_=for_,
        )
    if monitor:
        return SymbolicDCSourceMonitorClient(
            instrument_id,
            resource_id,
            for_=for_,
        )
    return SymbolicDCSourceClient(
        instrument_id,
        resource_id,
        for_=for_,
    )


__all__ = [
    "DCMonitorProducts",
    "DCMonitorReadback",
    "DCSourceClient",
    "DCSourceMonitorClient",
    "NetworkSweepClient",
    "NetworkSweepProducts",
    "NetworkSweepReadback",
    "RFOutputClient",
    "SymbolicDCSourceClient",
    "SymbolicDCSourceGroup",
    "SymbolicDCSourceMonitorClient",
    "SymbolicDCSourceMonitorGroup",
    "SymbolicInstrumentRecorder",
    "SymbolicNetworkSweepClient",
    "SymbolicNetworkSweepGroup",
    "SymbolicRFOutputClient",
    "SymbolicRFOutputGroup",
    "SymbolicTemperatureReadoutClient",
    "SymbolicTemperatureReadoutGroup",
    "TemperatureReadback",
    "TemperatureReadoutClient",
    "TemperatureSampleProducts",
    "dc_source",
    "network_sweep",
    "rf_output",
    "temperature_readout",
]
