# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
# pyright: reportPrivateUsage=false
"""Typed live and symbolic clients generated from interface declarations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, overload, override

from scopecat.authoring import (
    EachEntity,
    InstrumentRecorder,
    OneEntity,
    PerEntity,
    ProductBundle,
    ProductRef,
    ResourceRoleInput,
    Symbolic,
)
from scopecat.kernel.quantity import Quantity
from scopecat.program.measurement_types import MeasurementArrayData
from scopecat.records.measurement import MeasurementAcquisitionValue
from scopecat.sdk.instruments import (
    ApplyReceipt,
    CollectReceipt,
    InterfaceRef,
    InvokeReceipt,
)

from scopecat_instruments._client_runtime import (
    ClientAcquisition,
    ClientAcquisitionAxis,
    ClientAcquisitionResult,
    ClientStateField,
    ClientStateSchema,
    DeclaredStateClientBase,
    InstrumentClientBase,
    InstrumentMemberClient,
    client_property_value_type,
)
from scopecat_instruments._family_runtime import InstrumentFamily
from scopecat_instruments._symbolic_runtime import (
    DeclaredStateSymbolicClientBase,
    DeclaredStateSymbolicGroupBase,
    SymbolicInstrumentClientBase,
    SymbolicInstrumentGroupBase,
)
from scopecat_instruments.interface_declarations import (
    DCBiasState,
    DCMonitorState,
    DCSourceState,
    NetworkSweepState,
    RFOutputState,
    TemperatureReadoutState,
)
from scopecat_instruments.states import (
    DCBiasGroupTarget,
    DCBiasPatch,
    DCBiasTarget,
    DCMonitorGroupTarget,
    DCMonitorPatch,
    DCMonitorTarget,
    DCSourceGroupTarget,
    DCSourcePatch,
    DCSourceTarget,
    NetworkSweepGroupTarget,
    NetworkSweepPatch,
    NetworkSweepTarget,
    RFOutputGroupTarget,
    RFOutputPatch,
    RFOutputTarget,
)

_TEMPERATURE_READOUT_REF = InterfaceRef("scopecat.temperature_readout/v1")

_RF_OUTPUT_REF = InterfaceRef("scopecat.rf_output/v1")

_DC_BIAS_REF = InterfaceRef("scopecat.dc_bias/v1")

_DC_SOURCE_REF = InterfaceRef("scopecat.dc_source/v3")

_DC_MONITOR_REF = InterfaceRef("scopecat.dc_monitor/v4")

_NETWORK_SWEEP_REF = InterfaceRef("scopecat.network_sweep/v1")

_TEMPERATURE_READOUT_STATE_SCHEMA = ClientStateSchema(
    TemperatureReadoutState,
    fields=(
        ClientStateField(
            "scan_channel",
            InterfaceRef("scopecat.temperature_readout/v1").property("scan_channel"),
            client_property_value_type(
                '{"type":"int","minimum":1,"maximum":9007199254740991}'
            ),
        ),
        ClientStateField(
            "autoscan_enabled",
            InterfaceRef("scopecat.temperature_readout/v1").property(
                "autoscan_enabled"
            ),
            client_property_value_type('{"type":"bool"}'),
        ),
    ),
)

_TEMPERATURE_READOUT_SAMPLE_DECLARATION = ClientAcquisition(
    ref=_TEMPERATURE_READOUT_REF.acquisition("sample"),
    result_fields=(
        ClientAcquisitionResult(
            "temperature",
            _TEMPERATURE_READOUT_REF.acquisition("sample").result("temperature"),
            dtype="float64",
            unit="K",
            role="observable",
            axes=(),
        ),
        ClientAcquisitionResult(
            "resistance",
            _TEMPERATURE_READOUT_REF.acquisition("sample").result("resistance"),
            dtype="float64",
            unit="Ohm",
            role="observable",
            axes=(),
        ),
    ),
)

_RF_OUTPUT_STATE_SCHEMA = ClientStateSchema(
    RFOutputState,
    fields=(
        ClientStateField(
            "frequency",
            InterfaceRef("scopecat.rf_output/v1").property("frequency"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"Hz","minimum":null,"maxi'
                'mum":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "power",
            InterfaceRef("scopecat.rf_output/v1").property("power"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"dBm","minimum":null,"max'
                'imum":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "output_enabled",
            InterfaceRef("scopecat.rf_output/v1").property("output_enabled"),
            client_property_value_type('{"type":"bool"}'),
        ),
        ClientStateField(
            "reference_source",
            InterfaceRef("scopecat.rf_output/v1").property("reference_source"),
            client_property_value_type(
                '{"type":"string","choices":["internal","external"]}'
            ),
        ),
    ),
)

_DC_BIAS_STATE_SCHEMA = ClientStateSchema(
    DCBiasState,
    fields=(
        ClientStateField(
            "target_voltage",
            InterfaceRef("scopecat.dc_bias/v1").property("target_voltage"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"V","minimum":null,"maxim'
                'um":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "ramp_duration",
            InterfaceRef("scopecat.dc_bias/v1").property("ramp_duration"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"s","minimum":0.0,"maximu'
                'm":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "settle_tolerance",
            InterfaceRef("scopecat.dc_bias/v1").property("settle_tolerance"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"V","minimum":0.0,"maximu'
                'm":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "actual_voltage",
            InterfaceRef("scopecat.dc_bias/v1").property("actual_voltage"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"V","minimum":null,"maxim'
                'um":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "settled",
            InterfaceRef("scopecat.dc_bias/v1").property("settled"),
            client_property_value_type('{"type":"bool"}'),
        ),
    ),
)

_DC_BIAS_READBACK_DECLARATION = ClientAcquisition(
    ref=_DC_BIAS_REF.acquisition("readback"),
    result_fields=(
        ClientAcquisitionResult(
            "actual_voltage",
            _DC_BIAS_REF.acquisition("readback").result("actual_voltage"),
            dtype="float64",
            unit="V",
            role="observable",
            axes=(),
        ),
        ClientAcquisitionResult(
            "settled",
            _DC_BIAS_REF.acquisition("readback").result("settled"),
            dtype="bool",
            unit=None,
            role="observable",
            axes=(),
        ),
    ),
)

_DC_SOURCE_STATE_SCHEMA = ClientStateSchema(
    DCSourceState,
    fields=(
        ClientStateField(
            "voltage_protection",
            InterfaceRef("scopecat.dc_source/v3").property("voltage_protection"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"V","minimum":null,"maxim'
                'um":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "current_protection",
            InterfaceRef("scopecat.dc_source/v3").property("current_protection"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"A","minimum":null,"maxim'
                'um":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "output_enabled",
            InterfaceRef("scopecat.dc_source/v3").property("output_enabled"),
            client_property_value_type('{"type":"bool"}'),
        ),
        ClientStateField(
            "source_mode",
            InterfaceRef("scopecat.dc_source/v3").property("source_mode"),
            client_property_value_type(
                '{"type":"string","choices":["voltage","current"]}'
            ),
        ),
    ),
)

_DC_SOURCE_SOURCE_VOLTAGE_DECLARATION = _DC_SOURCE_REF.operation("source_voltage")

_DC_SOURCE_SOURCE_CURRENT_DECLARATION = _DC_SOURCE_REF.operation("source_current")

_DC_MONITOR_STATE_SCHEMA = ClientStateSchema(
    DCMonitorState,
    fields=(
        ClientStateField(
            "measurement_enabled",
            InterfaceRef("scopecat.dc_monitor/v4").property("measurement_enabled"),
            client_property_value_type('{"type":"bool"}'),
        ),
        ClientStateField(
            "integration_cycles",
            InterfaceRef("scopecat.dc_monitor/v4").property("integration_cycles"),
            client_property_value_type(
                '{"type":"int","minimum":1,"maximum":9007199254740991}'
            ),
        ),
        ClientStateField(
            "measurement_delay",
            InterfaceRef("scopecat.dc_monitor/v4").property("measurement_delay"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"s","minimum":0.0,"maximu'
                'm":null,"finite":true}'
            ),
        ),
    ),
)

_DC_MONITOR_MEASURE_CURRENT_DECLARATION = ClientAcquisition(
    ref=_DC_MONITOR_REF.acquisition("measure_current"),
    result_fields=(
        ClientAcquisitionResult(
            "current",
            _DC_MONITOR_REF.acquisition("measure_current").result("monitored_current"),
            dtype="float64",
            unit="A",
            role="observable",
            axes=(),
        ),
    ),
)

_DC_MONITOR_MEASURE_VOLTAGE_DECLARATION = ClientAcquisition(
    ref=_DC_MONITOR_REF.acquisition("measure_voltage"),
    result_fields=(
        ClientAcquisitionResult(
            "voltage",
            _DC_MONITOR_REF.acquisition("measure_voltage").result("monitored_voltage"),
            dtype="float64",
            unit="V",
            role="observable",
            axes=(),
        ),
    ),
)

_NETWORK_SWEEP_STATE_SCHEMA = ClientStateSchema(
    NetworkSweepState,
    fields=(
        ClientStateField(
            "start_frequency",
            InterfaceRef("scopecat.network_sweep/v1").property("start_frequency"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"Hz","minimum":null,"maxi'
                'mum":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "stop_frequency",
            InterfaceRef("scopecat.network_sweep/v1").property("stop_frequency"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"Hz","minimum":null,"maxi'
                'mum":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "points",
            InterfaceRef("scopecat.network_sweep/v1").property("points"),
            client_property_value_type(
                '{"type":"int","minimum":2,"maximum":9007199254740991}'
            ),
        ),
        ClientStateField(
            "if_bandwidth",
            InterfaceRef("scopecat.network_sweep/v1").property("if_bandwidth"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"Hz","minimum":null,"maxi'
                'mum":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "source_power",
            InterfaceRef("scopecat.network_sweep/v1").property("source_power"),
            client_property_value_type(
                '{"type":"quantity","dimension":nul'
                'l,"unit":"dBm","minimum":null,"max'
                'imum":null,"finite":true}'
            ),
        ),
        ClientStateField(
            "s_parameter",
            InterfaceRef("scopecat.network_sweep/v1").property("s_parameter"),
            client_property_value_type(
                '{"type":"string","choices":["S11","S21","S12","S22"]}'
            ),
        ),
    ),
)

_NETWORK_SWEEP_SWEEP_DECLARATION = ClientAcquisition(
    ref=_NETWORK_SWEEP_REF.acquisition("sweep"),
    result_fields=(
        ClientAcquisitionResult(
            "frequency",
            _NETWORK_SWEEP_REF.acquisition("sweep").result("frequency"),
            dtype="float64",
            unit="Hz",
            role="coordinate",
            axes=(
                ClientAcquisitionAxis(
                    id="frequency",
                    size=InterfaceRef("scopecat.network_sweep/v1").property("points"),
                    kind="frequency",
                    unit="Hz",
                ),
            ),
        ),
        ClientAcquisitionResult(
            "s_parameter",
            _NETWORK_SWEEP_REF.acquisition("sweep").result("s_parameter"),
            dtype="complex128",
            unit="ratio",
            role="observable",
            axes=(
                ClientAcquisitionAxis(
                    id="frequency",
                    size=InterfaceRef("scopecat.network_sweep/v1").property("points"),
                    kind="frequency",
                    unit="Hz",
                ),
            ),
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class TemperatureReadback:
    """Named sample results plus their effect receipt."""

    temperature: MeasurementAcquisitionValue
    resistance: MeasurementAcquisitionValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class TemperatureSampleProducts(ProductBundle):
    """Typed logical products produced by sample."""

    temperature: ProductRef[float]
    resistance: ProductRef[float]


class TemperatureReadoutClient(InstrumentClientBase):
    @property
    def scan_channel(self) -> InstrumentMemberClient[int]:
        return self._member(
            ClientStateField(
                "scan_channel",
                _TEMPERATURE_READOUT_REF.property("scan_channel"),
                client_property_value_type(
                    '{"type":"int","minimum":1,"maximum":9007199254740991}'
                ),
            ),
            writable=False,
        )

    @property
    def autoscan_enabled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "autoscan_enabled",
                _TEMPERATURE_READOUT_REF.property("autoscan_enabled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=False,
        )

    def state(self) -> TemperatureReadoutState:
        snapshot = self._session.observed_state(self.instrument_id)
        return _TEMPERATURE_READOUT_STATE_SCHEMA.decode(snapshot)

    def refresh_state(self) -> TemperatureReadoutState:
        snapshot = self._session.read_state(self.instrument_id)
        return _TEMPERATURE_READOUT_STATE_SCHEMA.decode(snapshot)

    def sample(self) -> TemperatureReadback:
        return self._collect(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureReadback,
        )


class SymbolicTemperatureReadoutClient(SymbolicInstrumentClientBase):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_TEMPERATURE_READOUT_REF,),
            for_=for_,
            role=role,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> TemperatureSampleProducts:
        return self._acquire(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureSampleProducts,
            id=id,
        )


class SymbolicTemperatureReadoutGroup(
    SymbolicInstrumentGroupBase[SymbolicTemperatureReadoutClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicTemperatureReadoutClient,
            role=role,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[TemperatureSampleProducts]:
        return self._clients.map(lambda client: client.sample(id=id))


temperature_readout: InstrumentFamily[
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
] = InstrumentFamily(
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
    name="temperature_readout",
    requires=(_TEMPERATURE_READOUT_REF,),
)


class RFOutputClient(DeclaredStateClientBase[RFOutputPatch]):
    @property
    def frequency(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "frequency",
                _RF_OUTPUT_REF.property("frequency"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"Hz","minimum":null,"'
                    'maximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def power(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "power",
                _RF_OUTPUT_REF.property("power"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"dBm","minimum":null,'
                    '"maximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def output_enabled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "output_enabled",
                _RF_OUTPUT_REF.property("output_enabled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=True,
        )

    @property
    def reference_source(
        self,
    ) -> InstrumentMemberClient[Literal["internal", "external"]]:
        return self._member(
            ClientStateField(
                "reference_source",
                _RF_OUTPUT_REF.property("reference_source"),
                client_property_value_type(
                    '{"type":"string","choices":["internal","external"]}'
                ),
            ),
            writable=True,
        )

    @overload
    def apply(
        self,
        patch: RFOutputPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        frequency: Quantity = ...,
        power: Quantity = ...,
        output_enabled: bool = ...,
        reference_source: Literal["internal", "external"] = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: RFOutputPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            RFOutputPatch,
            fields,
        )

    def state(self) -> RFOutputState:
        snapshot = self._session.observed_state(self.instrument_id)
        return _RF_OUTPUT_STATE_SCHEMA.decode(snapshot)

    def refresh_state(self) -> RFOutputState:
        snapshot = self._session.read_state(self.instrument_id)
        return _RF_OUTPUT_STATE_SCHEMA.decode(snapshot)


class SymbolicRFOutputClient(DeclaredStateSymbolicClientBase[RFOutputTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_RF_OUTPUT_REF,),
            for_=for_,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: RFOutputTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        frequency: Symbolic[Quantity] = ...,
        power: Symbolic[Quantity] = ...,
        output_enabled: Symbolic[bool] = ...,
        reference_source: Symbolic[Literal["internal", "external"]] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: RFOutputTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            RFOutputTarget,
            fields,
        )


class SymbolicRFOutputGroup(
    DeclaredStateSymbolicGroupBase[
        RFOutputTarget, RFOutputGroupTarget, SymbolicRFOutputClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicRFOutputClient,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: RFOutputGroupTarget | PerEntity[RFOutputTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        power: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        output_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = ...,
        reference_source: (
            Symbolic[Literal["internal", "external"]]
            | PerEntity[Symbolic[Literal["internal", "external"]]]
        ) = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: RFOutputGroupTarget | PerEntity[RFOutputTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            RFOutputGroupTarget,
            fields,
        )


rf_output: InstrumentFamily[
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
] = InstrumentFamily(
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
    name="rf_output",
    requires=(_RF_OUTPUT_REF,),
)


@dataclass(frozen=True, slots=True)
class DCBiasReadbackReadback:
    """Named readback results plus their effect receipt."""

    actual_voltage: MeasurementAcquisitionValue
    settled: MeasurementAcquisitionValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class DCBiasReadbackProducts(ProductBundle):
    """Typed logical products produced by readback."""

    actual_voltage: ProductRef[float]
    settled: ProductRef[bool]


class DCBiasClient(DeclaredStateClientBase[DCBiasPatch]):
    @property
    def target_voltage(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "target_voltage",
                _DC_BIAS_REF.property("target_voltage"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"V","minimum":null,"m'
                    'aximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def ramp_duration(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "ramp_duration",
                _DC_BIAS_REF.property("ramp_duration"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"s","minimum":0.0,"ma'
                    'ximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def settle_tolerance(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "settle_tolerance",
                _DC_BIAS_REF.property("settle_tolerance"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"V","minimum":0.0,"ma'
                    'ximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def actual_voltage(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "actual_voltage",
                _DC_BIAS_REF.property("actual_voltage"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"V","minimum":null,"m'
                    'aximum":null,"finite":true}'
                ),
            ),
            writable=False,
        )

    @property
    def settled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "settled",
                _DC_BIAS_REF.property("settled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=False,
        )

    @overload
    def apply(
        self,
        patch: DCBiasPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        target_voltage: Quantity = ...,
        ramp_duration: Quantity = ...,
        settle_tolerance: Quantity = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: DCBiasPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            DCBiasPatch,
            fields,
        )

    def state(self) -> DCBiasState:
        snapshot = self._session.observed_state(self.instrument_id)
        return _DC_BIAS_STATE_SCHEMA.decode(snapshot)

    def refresh_state(self) -> DCBiasState:
        snapshot = self._session.read_state(self.instrument_id)
        return _DC_BIAS_STATE_SCHEMA.decode(snapshot)

    def readback(self) -> DCBiasReadbackReadback:
        return self._collect(
            _DC_BIAS_READBACK_DECLARATION,
            DCBiasReadbackReadback,
        )


class SymbolicDCBiasClient(DeclaredStateSymbolicClientBase[DCBiasTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_DC_BIAS_REF,),
            for_=for_,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: DCBiasTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        target_voltage: Symbolic[Quantity] = ...,
        ramp_duration: Symbolic[Quantity] = ...,
        settle_tolerance: Symbolic[Quantity] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCBiasTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCBiasTarget,
            fields,
        )

    def readback(
        self,
        *,
        id: str | None = None,
    ) -> DCBiasReadbackProducts:
        return self._acquire(
            _DC_BIAS_READBACK_DECLARATION,
            DCBiasReadbackProducts,
            id=id,
        )


class SymbolicDCBiasGroup(
    DeclaredStateSymbolicGroupBase[
        DCBiasTarget, DCBiasGroupTarget, SymbolicDCBiasClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicDCBiasClient,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: DCBiasGroupTarget | PerEntity[DCBiasTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        target_voltage: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        ramp_duration: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        settle_tolerance: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCBiasGroupTarget | PerEntity[DCBiasTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCBiasGroupTarget,
            fields,
        )

    def readback(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCBiasReadbackProducts]:
        return self._clients.map(lambda client: client.readback(id=id))


dc_bias: InstrumentFamily[
    DCBiasClient,
    SymbolicDCBiasClient,
    SymbolicDCBiasGroup,
] = InstrumentFamily(
    DCBiasClient,
    SymbolicDCBiasClient,
    SymbolicDCBiasGroup,
    name="dc_bias",
    requires=(_DC_BIAS_REF,),
)


class DCSourceClient(DeclaredStateClientBase[DCSourcePatch]):
    @property
    def voltage_protection(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "voltage_protection",
                _DC_SOURCE_REF.property("voltage_protection"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"V","minimum":null,"m'
                    'aximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def current_protection(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "current_protection",
                _DC_SOURCE_REF.property("current_protection"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"A","minimum":null,"m'
                    'aximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def output_enabled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "output_enabled",
                _DC_SOURCE_REF.property("output_enabled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=True,
        )

    @property
    def source_mode(self) -> InstrumentMemberClient[Literal["voltage", "current"]]:
        return self._member(
            ClientStateField(
                "source_mode",
                _DC_SOURCE_REF.property("source_mode"),
                client_property_value_type(
                    '{"type":"string","choices":["voltage","current"]}'
                ),
            ),
            writable=False,
        )

    @overload
    def apply(
        self,
        patch: DCSourcePatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        voltage_protection: Quantity = ...,
        current_protection: Quantity = ...,
        output_enabled: bool = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: DCSourcePatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            DCSourcePatch,
            fields,
        )

    def state(self) -> DCSourceState:
        snapshot = self._session.observed_state(self.instrument_id)
        return _DC_SOURCE_STATE_SCHEMA.decode(snapshot)

    def refresh_state(self) -> DCSourceState:
        snapshot = self._session.read_state(self.instrument_id)
        return _DC_SOURCE_STATE_SCHEMA.decode(snapshot)

    def source_voltage(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )


class SymbolicDCSourceClient(DeclaredStateSymbolicClientBase[DCSourceTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_DC_SOURCE_REF,),
            for_=for_,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: DCSourceTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        voltage_protection: Symbolic[Quantity] = ...,
        current_protection: Symbolic[Quantity] = ...,
        output_enabled: Symbolic[bool] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCSourceTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCSourceTarget,
            fields,
        )

    def source_voltage(
        self,
        *,
        range: Symbolic[Quantity],
        level: Symbolic[Quantity],
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Symbolic[Quantity],
        level: Symbolic[Quantity],
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )


class SymbolicDCSourceGroup(
    DeclaredStateSymbolicGroupBase[
        DCSourceTarget, DCSourceGroupTarget, SymbolicDCSourceClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicDCSourceClient,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: DCSourceGroupTarget | PerEntity[DCSourceTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        voltage_protection: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        current_protection: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        output_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCSourceGroupTarget | PerEntity[DCSourceTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCSourceGroupTarget,
            fields,
        )

    def source_voltage(
        self,
        *,
        range: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        level: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_voltage(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )

    def source_current(
        self,
        *,
        range: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        level: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_current(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )


dc_source: InstrumentFamily[
    DCSourceClient,
    SymbolicDCSourceClient,
    SymbolicDCSourceGroup,
] = InstrumentFamily(
    DCSourceClient,
    SymbolicDCSourceClient,
    SymbolicDCSourceGroup,
    name="dc_source",
    requires=(_DC_SOURCE_REF,),
)


@dataclass(frozen=True, slots=True)
class DCMonitorCurrentReadback:
    """Named measure_current results plus their effect receipt."""

    current: MeasurementAcquisitionValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class DCMonitorCurrentProducts(ProductBundle):
    """Typed logical products produced by measure_current."""

    current: ProductRef[float]


@dataclass(frozen=True, slots=True)
class DCMonitorVoltageReadback:
    """Named measure_voltage results plus their effect receipt."""

    voltage: MeasurementAcquisitionValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class DCMonitorVoltageProducts(ProductBundle):
    """Typed logical products produced by measure_voltage."""

    voltage: ProductRef[float]


class DCMonitorClient(DeclaredStateClientBase[DCMonitorPatch]):
    @property
    def measurement_enabled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "measurement_enabled",
                _DC_MONITOR_REF.property("measurement_enabled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=True,
        )

    @property
    def integration_cycles(self) -> InstrumentMemberClient[int]:
        return self._member(
            ClientStateField(
                "integration_cycles",
                _DC_MONITOR_REF.property("integration_cycles"),
                client_property_value_type(
                    '{"type":"int","minimum":1,"maximum":9007199254740991}'
                ),
            ),
            writable=True,
        )

    @property
    def measurement_delay(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "measurement_delay",
                _DC_MONITOR_REF.property("measurement_delay"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"s","minimum":0.0,"ma'
                    'ximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @overload
    def apply(
        self,
        patch: DCMonitorPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        measurement_enabled: bool = ...,
        integration_cycles: int = ...,
        measurement_delay: Quantity = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: DCMonitorPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            DCMonitorPatch,
            fields,
        )

    def state(self) -> DCMonitorState:
        snapshot = self._session.observed_state(self.instrument_id)
        return _DC_MONITOR_STATE_SCHEMA.decode(snapshot)

    def refresh_state(self) -> DCMonitorState:
        snapshot = self._session.read_state(self.instrument_id)
        return _DC_MONITOR_STATE_SCHEMA.decode(snapshot)

    def measure_current(self) -> DCMonitorCurrentReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentReadback,
        )

    def measure_voltage(self) -> DCMonitorVoltageReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageReadback,
        )


class SymbolicDCMonitorClient(DeclaredStateSymbolicClientBase[DCMonitorTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_DC_MONITOR_REF,),
            for_=for_,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: DCMonitorTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        measurement_enabled: Symbolic[bool] = ...,
        integration_cycles: Symbolic[int] = ...,
        measurement_delay: Symbolic[Quantity] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCMonitorTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCMonitorTarget,
            fields,
        )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorCurrentProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentProducts,
            id=id,
        )

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorVoltageProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageProducts,
            id=id,
        )


class SymbolicDCMonitorGroup(
    DeclaredStateSymbolicGroupBase[
        DCMonitorTarget, DCMonitorGroupTarget, SymbolicDCMonitorClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicDCMonitorClient,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: DCMonitorGroupTarget | PerEntity[DCMonitorTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        measurement_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = ...,
        integration_cycles: Symbolic[int] | PerEntity[Symbolic[int]] = ...,
        measurement_delay: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCMonitorGroupTarget | PerEntity[DCMonitorTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCMonitorGroupTarget,
            fields,
        )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorCurrentProducts]:
        return self._clients.map(lambda client: client.measure_current(id=id))

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorVoltageProducts]:
        return self._clients.map(lambda client: client.measure_voltage(id=id))


dc_monitor: InstrumentFamily[
    DCMonitorClient,
    SymbolicDCMonitorClient,
    SymbolicDCMonitorGroup,
] = InstrumentFamily(
    DCMonitorClient,
    SymbolicDCMonitorClient,
    SymbolicDCMonitorGroup,
    name="dc_monitor",
    requires=(_DC_MONITOR_REF,),
)


@dataclass(frozen=True, slots=True)
class DCSourceMonitorState:
    dc_source: DCSourceState
    dc_monitor: DCMonitorState


type _DCSourceMonitorPatch = DCSourcePatch | DCMonitorPatch


type _DCSourceMonitorTarget = DCSourceTarget | DCMonitorTarget


type _DCSourceMonitorGroupTarget = DCSourceGroupTarget | DCMonitorGroupTarget


class DCSourceMonitorClient(DeclaredStateClientBase[_DCSourceMonitorPatch]):
    @property
    def voltage_protection(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "voltage_protection",
                _DC_SOURCE_REF.property("voltage_protection"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"V","minimum":null,"m'
                    'aximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def current_protection(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "current_protection",
                _DC_SOURCE_REF.property("current_protection"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"A","minimum":null,"m'
                    'aximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def output_enabled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "output_enabled",
                _DC_SOURCE_REF.property("output_enabled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=True,
        )

    @property
    def source_mode(self) -> InstrumentMemberClient[Literal["voltage", "current"]]:
        return self._member(
            ClientStateField(
                "source_mode",
                _DC_SOURCE_REF.property("source_mode"),
                client_property_value_type(
                    '{"type":"string","choices":["voltage","current"]}'
                ),
            ),
            writable=False,
        )

    @property
    def measurement_enabled(self) -> InstrumentMemberClient[bool]:
        return self._member(
            ClientStateField(
                "measurement_enabled",
                _DC_MONITOR_REF.property("measurement_enabled"),
                client_property_value_type('{"type":"bool"}'),
            ),
            writable=True,
        )

    @property
    def integration_cycles(self) -> InstrumentMemberClient[int]:
        return self._member(
            ClientStateField(
                "integration_cycles",
                _DC_MONITOR_REF.property("integration_cycles"),
                client_property_value_type(
                    '{"type":"int","minimum":1,"maximum":9007199254740991}'
                ),
            ),
            writable=True,
        )

    @property
    def measurement_delay(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "measurement_delay",
                _DC_MONITOR_REF.property("measurement_delay"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"s","minimum":0.0,"ma'
                    'ximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    def state(self) -> DCSourceMonitorState:
        snapshot = self._session.observed_state(self.instrument_id)
        return DCSourceMonitorState(
            dc_source=_DC_SOURCE_STATE_SCHEMA.decode(snapshot),
            dc_monitor=_DC_MONITOR_STATE_SCHEMA.decode(snapshot),
        )

    def refresh_state(self) -> DCSourceMonitorState:
        snapshot = self._session.read_state(self.instrument_id)
        return DCSourceMonitorState(
            dc_source=_DC_SOURCE_STATE_SCHEMA.decode(snapshot),
            dc_monitor=_DC_MONITOR_STATE_SCHEMA.decode(snapshot),
        )

    def source_voltage(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )

    def measure_current(self) -> DCMonitorCurrentReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentReadback,
        )

    def measure_voltage(self) -> DCMonitorVoltageReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageReadback,
        )


class SymbolicDCSourceMonitorClient(
    DeclaredStateSymbolicClientBase[_DCSourceMonitorTarget]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_DC_SOURCE_REF, _DC_MONITOR_REF),
            for_=for_,
            role=role,
        )

    def source_voltage(
        self,
        *,
        range: Symbolic[Quantity],
        level: Symbolic[Quantity],
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Symbolic[Quantity],
        level: Symbolic[Quantity],
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorCurrentProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentProducts,
            id=id,
        )

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorVoltageProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageProducts,
            id=id,
        )


class SymbolicDCSourceMonitorGroup(
    DeclaredStateSymbolicGroupBase[
        _DCSourceMonitorTarget,
        _DCSourceMonitorGroupTarget,
        SymbolicDCSourceMonitorClient,
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicDCSourceMonitorClient,
            role=role,
        )

    def source_voltage(
        self,
        *,
        range: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        level: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_voltage(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )

    def source_current(
        self,
        *,
        range: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        level: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_current(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorCurrentProducts]:
        return self._clients.map(lambda client: client.measure_current(id=id))

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorVoltageProducts]:
        return self._clients.map(lambda client: client.measure_voltage(id=id))


dc_source_monitor: InstrumentFamily[
    DCSourceMonitorClient,
    SymbolicDCSourceMonitorClient,
    SymbolicDCSourceMonitorGroup,
] = InstrumentFamily(
    DCSourceMonitorClient,
    SymbolicDCSourceMonitorClient,
    SymbolicDCSourceMonitorGroup,
    name="dc_source_monitor",
    requires=(_DC_SOURCE_REF, _DC_MONITOR_REF),
)


@dataclass(frozen=True, slots=True)
class NetworkSweepReadback:
    """Named sweep results plus their effect receipt."""

    frequency: MeasurementAcquisitionValue
    s_parameter: MeasurementAcquisitionValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class NetworkSweepProducts(ProductBundle):
    """Typed logical products produced by sweep."""

    frequency: ProductRef[MeasurementArrayData]
    s_parameter: ProductRef[MeasurementArrayData]


class NetworkSweepClient(DeclaredStateClientBase[NetworkSweepPatch]):
    @property
    def start_frequency(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "start_frequency",
                _NETWORK_SWEEP_REF.property("start_frequency"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"Hz","minimum":null,"'
                    'maximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def stop_frequency(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "stop_frequency",
                _NETWORK_SWEEP_REF.property("stop_frequency"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"Hz","minimum":null,"'
                    'maximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def points(self) -> InstrumentMemberClient[int]:
        return self._member(
            ClientStateField(
                "points",
                _NETWORK_SWEEP_REF.property("points"),
                client_property_value_type(
                    '{"type":"int","minimum":2,"maximum":9007199254740991}'
                ),
            ),
            writable=True,
        )

    @property
    def if_bandwidth(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "if_bandwidth",
                _NETWORK_SWEEP_REF.property("if_bandwidth"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"Hz","minimum":null,"'
                    'maximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def source_power(self) -> InstrumentMemberClient[Quantity]:
        return self._member(
            ClientStateField(
                "source_power",
                _NETWORK_SWEEP_REF.property("source_power"),
                client_property_value_type(
                    '{"type":"quantity","dimension":n'
                    'ull,"unit":"dBm","minimum":null,'
                    '"maximum":null,"finite":true}'
                ),
            ),
            writable=True,
        )

    @property
    def s_parameter(
        self,
    ) -> InstrumentMemberClient[Literal["S11", "S21", "S12", "S22"]]:
        return self._member(
            ClientStateField(
                "s_parameter",
                _NETWORK_SWEEP_REF.property("s_parameter"),
                client_property_value_type(
                    '{"type":"string","choices":["S11","S21","S12","S22"]}'
                ),
            ),
            writable=True,
        )

    @overload
    def apply(
        self,
        patch: NetworkSweepPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        start_frequency: Quantity = ...,
        stop_frequency: Quantity = ...,
        points: int = ...,
        if_bandwidth: Quantity = ...,
        source_power: Quantity = ...,
        s_parameter: Literal["S11", "S21", "S12", "S22"] = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: NetworkSweepPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            NetworkSweepPatch,
            fields,
        )

    def state(self) -> NetworkSweepState:
        snapshot = self._session.observed_state(self.instrument_id)
        return _NETWORK_SWEEP_STATE_SCHEMA.decode(snapshot)

    def refresh_state(self) -> NetworkSweepState:
        snapshot = self._session.read_state(self.instrument_id)
        return _NETWORK_SWEEP_STATE_SCHEMA.decode(snapshot)

    def sweep(self) -> NetworkSweepReadback:
        return self._collect(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepReadback,
        )


class SymbolicNetworkSweepClient(DeclaredStateSymbolicClientBase[NetworkSweepTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: OneEntity | None = None,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            requires=(_NETWORK_SWEEP_REF,),
            for_=for_,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: NetworkSweepTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        start_frequency: Symbolic[Quantity] = ...,
        stop_frequency: Symbolic[Quantity] = ...,
        points: Symbolic[int] = ...,
        if_bandwidth: Symbolic[Quantity] = ...,
        source_power: Symbolic[Quantity] = ...,
        s_parameter: Symbolic[Literal["S11", "S21", "S12", "S22"]] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: NetworkSweepTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            NetworkSweepTarget,
            fields,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> NetworkSweepProducts:
        return self._acquire(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepProducts,
            id=id,
        )


class SymbolicNetworkSweepGroup(
    DeclaredStateSymbolicGroupBase[
        NetworkSweepTarget, NetworkSweepGroupTarget, SymbolicNetworkSweepClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: InstrumentRecorder,
        resource_id: str,
        *,
        namespace_hint: str,
        for_: EachEntity,
        role: ResourceRoleInput = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            namespace_hint=namespace_hint,
            for_=for_,
            client_factory=SymbolicNetworkSweepClient,
            role=role,
        )

    @overload
    def ensure(
        self,
        state: NetworkSweepGroupTarget | PerEntity[NetworkSweepTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        start_frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        stop_frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        points: Symbolic[int] | PerEntity[Symbolic[int]] = ...,
        if_bandwidth: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        source_power: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = ...,
        s_parameter: (
            Symbolic[Literal["S11", "S21", "S12", "S22"]]
            | PerEntity[Symbolic[Literal["S11", "S21", "S12", "S22"]]]
        ) = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: NetworkSweepGroupTarget | PerEntity[NetworkSweepTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            NetworkSweepGroupTarget,
            fields,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[NetworkSweepProducts]:
        return self._clients.map(lambda client: client.sweep(id=id))


network_sweep: InstrumentFamily[
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
] = InstrumentFamily(
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
    name="network_sweep",
    requires=(_NETWORK_SWEEP_REF,),
)

__all__ = [
    "DCBiasClient",
    "DCBiasReadbackProducts",
    "DCBiasReadbackReadback",
    "DCMonitorClient",
    "DCMonitorCurrentProducts",
    "DCMonitorCurrentReadback",
    "DCMonitorVoltageProducts",
    "DCMonitorVoltageReadback",
    "DCSourceClient",
    "DCSourceMonitorClient",
    "DCSourceMonitorState",
    "NetworkSweepClient",
    "NetworkSweepProducts",
    "NetworkSweepReadback",
    "RFOutputClient",
    "SymbolicDCBiasClient",
    "SymbolicDCBiasGroup",
    "SymbolicDCMonitorClient",
    "SymbolicDCMonitorGroup",
    "SymbolicDCSourceClient",
    "SymbolicDCSourceGroup",
    "SymbolicDCSourceMonitorClient",
    "SymbolicDCSourceMonitorGroup",
    "SymbolicNetworkSweepClient",
    "SymbolicNetworkSweepGroup",
    "SymbolicRFOutputClient",
    "SymbolicRFOutputGroup",
    "SymbolicTemperatureReadoutClient",
    "SymbolicTemperatureReadoutGroup",
    "TemperatureReadback",
    "TemperatureReadoutClient",
    "TemperatureSampleProducts",
    "dc_bias",
    "dc_monitor",
    "dc_source",
    "dc_source_monitor",
    "network_sweep",
    "rf_output",
    "temperature_readout",
]
