# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed live and symbolic clients generated from interface declarations."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal, overload, override

from scopecat.authoring import EachEntity, OneEntity, PerEntity, ProductRef, ValueRef
from scopecat.kernel.quantity import Quantity
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import (
    ApplyReceipt,
    CollectReceipt,
    InterfaceRef,
    InvokeReceipt,
)

from scopecat_instruments._client_runtime import (
    ClientAcquisition,
    ClientAcquisitionAxis,
    ClientAcquisitionLayout,
    ClientAcquisitionResult,
    ClientObservedField,
    ClientObservedState,
    DeclaredStateClientBase,
    InstrumentClientBase,
    client_property_value_type,
)
from scopecat_instruments._family_runtime import InstrumentFamily
from scopecat_instruments._symbolic_runtime import (
    DeclaredStateSymbolicClientBase,
    DeclaredStateSymbolicGroupBase,
    SymbolicInstrumentClientBase,
    SymbolicInstrumentGroupBase,
    SymbolicInstrumentRecorder,
)
from scopecat_instruments.interface_declarations import (
    DCSourceObservation,
    TemperatureReadoutObservation,
)
from scopecat_instruments.states import (
    DCMonitorGroupTarget,
    DCMonitorPatch,
    DCMonitorTarget,
    DCSourceGroupTarget,
    DCSourcePatch,
    DCSourceTarget,
    NetworkSweepGroupTarget,
    NetworkSweepPatch,
    NetworkSweepTarget,
    RFOutputGroupTarget,
    RFOutputPatch,
    RFOutputTarget,
)

_TEMPERATURE_READOUT_REF = InterfaceRef("scopecat.temperature_readout/v1")

_RF_OUTPUT_REF = InterfaceRef("scopecat.rf_output/v1")

_DC_SOURCE_REF = InterfaceRef("scopecat.dc_source/v3")

_DC_MONITOR_REF = InterfaceRef("scopecat.dc_monitor/v4")

_NETWORK_SWEEP_REF = InterfaceRef("scopecat.network_sweep/v1")

_TEMPERATURE_READOUT_OBSERVATION_DECLARATION = ClientObservedState(
    TemperatureReadoutObservation,
    fields=(
        ClientObservedField(
            "scan_channel",
            InterfaceRef("scopecat.temperature_readout/v1").property("scan_channel"),
            client_property_value_type(
                '{"type":"int","minimum":1,"maximum":9007199254740991}'
            ),
        ),
        ClientObservedField(
            "autoscan_enabled",
            InterfaceRef("scopecat.temperature_readout/v1").property(
                "autoscan_enabled"
            ),
            client_property_value_type('{"type":"bool"}'),
        ),
    ),
)

_TEMPERATURE_READOUT_SAMPLE_DECLARATION = ClientAcquisition(
    ref=_TEMPERATURE_READOUT_REF.acquisition("sample"),
    discriminator=None,
    layouts=(
        ClientAcquisitionLayout(
            case_value=None,
            fields=(
                ClientAcquisitionResult(
                    "temperature",
                    _TEMPERATURE_READOUT_REF.acquisition("sample").result(
                        "temperature"
                    ),
                    dtype="float64",
                    unit="K",
                    axes=(),
                ),
                ClientAcquisitionResult(
                    "resistance",
                    _TEMPERATURE_READOUT_REF.acquisition("sample").result("resistance"),
                    dtype="float64",
                    unit="Ohm",
                    axes=(),
                ),
            ),
        ),
    ),
)

_DC_SOURCE_OBSERVATION_DECLARATION = ClientObservedState(
    DCSourceObservation,
    fields=(
        ClientObservedField(
            "source_mode",
            InterfaceRef("scopecat.dc_source/v3").property("source_mode"),
            client_property_value_type(
                '{"type":"string","choices":["voltage","current"]}'
            ),
        ),
    ),
)

_DC_SOURCE_SOURCE_VOLTAGE_DECLARATION = _DC_SOURCE_REF.operation("source_voltage")

_DC_SOURCE_SOURCE_CURRENT_DECLARATION = _DC_SOURCE_REF.operation("source_current")

_DC_MONITOR_MEASURE_CURRENT_DECLARATION = ClientAcquisition(
    ref=_DC_MONITOR_REF.acquisition("measure_current"),
    discriminator=None,
    layouts=(
        ClientAcquisitionLayout(
            case_value=None,
            fields=(
                ClientAcquisitionResult(
                    "current",
                    _DC_MONITOR_REF.acquisition("measure_current").result(
                        "monitored_current"
                    ),
                    dtype="float64",
                    unit="A",
                    axes=(),
                ),
            ),
        ),
    ),
)

_DC_MONITOR_MEASURE_VOLTAGE_DECLARATION = ClientAcquisition(
    ref=_DC_MONITOR_REF.acquisition("measure_voltage"),
    discriminator=None,
    layouts=(
        ClientAcquisitionLayout(
            case_value=None,
            fields=(
                ClientAcquisitionResult(
                    "voltage",
                    _DC_MONITOR_REF.acquisition("measure_voltage").result(
                        "monitored_voltage"
                    ),
                    dtype="float64",
                    unit="V",
                    axes=(),
                ),
            ),
        ),
    ),
)

_NETWORK_SWEEP_SWEEP_DECLARATION = ClientAcquisition(
    ref=_NETWORK_SWEEP_REF.acquisition("sweep"),
    discriminator=None,
    layouts=(
        ClientAcquisitionLayout(
            case_value=None,
            fields=(
                ClientAcquisitionResult(
                    "frequency",
                    _NETWORK_SWEEP_REF.acquisition("sweep").result("frequency"),
                    dtype="float64",
                    unit="Hz",
                    axes=(
                        ClientAcquisitionAxis(
                            id="frequency",
                            size=InterfaceRef("scopecat.network_sweep/v1").property(
                                "points"
                            ),
                            kind="frequency",
                            unit="Hz",
                        ),
                    ),
                ),
                ClientAcquisitionResult(
                    "s_parameter",
                    _NETWORK_SWEEP_REF.acquisition("sweep").result("s_parameter"),
                    dtype="complex128",
                    unit="ratio",
                    axes=(
                        ClientAcquisitionAxis(
                            id="frequency",
                            size=InterfaceRef("scopecat.network_sweep/v1").property(
                                "points"
                            ),
                            kind="frequency",
                            unit="Hz",
                        ),
                    ),
                ),
            ),
        ),
    ),
)


@dataclass(frozen=True, slots=True)
class TemperatureReadback:
    """Named sample results plus their effect receipt."""

    temperature: MeasurementValue
    resistance: MeasurementValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class TemperatureSampleProducts:
    """Typed logical products produced by sample."""

    temperature: ProductRef
    resistance: ProductRef


class TemperatureReadoutClient(InstrumentClientBase):
    def observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.observed_state(self.instrument_id)
        )

    def refresh_observation(self) -> TemperatureReadoutObservation:
        return _TEMPERATURE_READOUT_OBSERVATION_DECLARATION.decode(
            self._session.read_state(self.instrument_id)
        )

    def sample(self) -> TemperatureReadback:
        return self._collect(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureReadback,
        )


class SymbolicTemperatureReadoutClient(SymbolicInstrumentClientBase):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_TEMPERATURE_READOUT_REF,),
            for_=for_,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> TemperatureSampleProducts:
        return self._acquire(
            _TEMPERATURE_READOUT_SAMPLE_DECLARATION,
            TemperatureSampleProducts,
            id=id,
        )


class SymbolicTemperatureReadoutGroup(
    SymbolicInstrumentGroupBase[SymbolicTemperatureReadoutClient]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicTemperatureReadoutClient,
        )

    def sample(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[TemperatureSampleProducts]:
        return self._clients.map(lambda client: client.sample(id=id))


temperature_readout: InstrumentFamily[
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
] = InstrumentFamily(
    TemperatureReadoutClient,
    SymbolicTemperatureReadoutClient,
    SymbolicTemperatureReadoutGroup,
    requires=(_TEMPERATURE_READOUT_REF,),
)


class RFOutputClient(DeclaredStateClientBase[RFOutputPatch]):
    @overload
    def apply(
        self,
        patch: RFOutputPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        frequency: Quantity = ...,
        power: Quantity = ...,
        output_enabled: bool = ...,
        reference_source: Literal["internal", "external"] = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: RFOutputPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            RFOutputPatch,
            fields,
        )


class SymbolicRFOutputClient(DeclaredStateSymbolicClientBase[RFOutputTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_RF_OUTPUT_REF,),
            for_=for_,
        )

    @overload
    def ensure(
        self,
        state: RFOutputTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        frequency: Quantity | ValueRef = ...,
        power: Quantity | ValueRef = ...,
        output_enabled: bool | ValueRef = ...,
        reference_source: Literal["internal", "external"] | ValueRef = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: RFOutputTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            RFOutputTarget,
            fields,
        )


class SymbolicRFOutputGroup(
    DeclaredStateSymbolicGroupBase[
        RFOutputTarget, RFOutputGroupTarget, SymbolicRFOutputClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicRFOutputClient,
        )

    @overload
    def ensure(
        self,
        state: RFOutputGroupTarget | PerEntity[RFOutputTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = ...,
        reference_source: (
            Literal["internal", "external"]
            | ValueRef
            | PerEntity[Literal["internal", "external"] | ValueRef]
        ) = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: RFOutputGroupTarget | PerEntity[RFOutputTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            RFOutputGroupTarget,
            fields,
        )


rf_output: InstrumentFamily[
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
] = InstrumentFamily(
    RFOutputClient,
    SymbolicRFOutputClient,
    SymbolicRFOutputGroup,
    requires=(_RF_OUTPUT_REF,),
)


class DCSourceClient(DeclaredStateClientBase[DCSourcePatch]):
    @overload
    def apply(
        self,
        patch: DCSourcePatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        voltage_protection: Quantity = ...,
        current_protection: Quantity = ...,
        output_enabled: bool = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: DCSourcePatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            DCSourcePatch,
            fields,
        )

    def observation(self) -> DCSourceObservation:
        return _DC_SOURCE_OBSERVATION_DECLARATION.decode(
            self._session.observed_state(self.instrument_id)
        )

    def refresh_observation(self) -> DCSourceObservation:
        return _DC_SOURCE_OBSERVATION_DECLARATION.decode(
            self._session.read_state(self.instrument_id)
        )

    def source_voltage(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )


class SymbolicDCSourceClient(DeclaredStateSymbolicClientBase[DCSourceTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_DC_SOURCE_REF,),
            for_=for_,
        )

    @overload
    def ensure(
        self,
        state: DCSourceTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        voltage_protection: Quantity | ValueRef = ...,
        current_protection: Quantity | ValueRef = ...,
        output_enabled: bool | ValueRef = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCSourceTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCSourceTarget,
            fields,
        )

    def source_voltage(
        self,
        *,
        range: Quantity | ValueRef,
        level: Quantity | ValueRef,
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Quantity | ValueRef,
        level: Quantity | ValueRef,
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )


class SymbolicDCSourceGroup(
    DeclaredStateSymbolicGroupBase[
        DCSourceTarget, DCSourceGroupTarget, SymbolicDCSourceClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicDCSourceClient,
        )

    @overload
    def ensure(
        self,
        state: DCSourceGroupTarget | PerEntity[DCSourceTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        voltage_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        current_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCSourceGroupTarget | PerEntity[DCSourceTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCSourceGroupTarget,
            fields,
        )

    def source_voltage(
        self,
        *,
        range: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        level: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_voltage(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )

    def source_current(
        self,
        *,
        range: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        level: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_current(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )


dc_source: InstrumentFamily[
    DCSourceClient,
    SymbolicDCSourceClient,
    SymbolicDCSourceGroup,
] = InstrumentFamily(
    DCSourceClient,
    SymbolicDCSourceClient,
    SymbolicDCSourceGroup,
    requires=(_DC_SOURCE_REF,),
)


@dataclass(frozen=True, slots=True)
class DCMonitorCurrentReadback:
    """Named measure_current results plus their effect receipt."""

    current: MeasurementValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class DCMonitorCurrentProducts:
    """Typed logical products produced by measure_current."""

    current: ProductRef


@dataclass(frozen=True, slots=True)
class DCMonitorVoltageReadback:
    """Named measure_voltage results plus their effect receipt."""

    voltage: MeasurementValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class DCMonitorVoltageProducts:
    """Typed logical products produced by measure_voltage."""

    voltage: ProductRef


class DCMonitorClient(DeclaredStateClientBase[DCMonitorPatch]):
    @overload
    def apply(
        self,
        patch: DCMonitorPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        measurement_enabled: bool = ...,
        integration_cycles: int = ...,
        measurement_delay: Quantity = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: DCMonitorPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            DCMonitorPatch,
            fields,
        )

    def measure_current(self) -> DCMonitorCurrentReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentReadback,
        )

    def measure_voltage(self) -> DCMonitorVoltageReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageReadback,
        )


class SymbolicDCMonitorClient(DeclaredStateSymbolicClientBase[DCMonitorTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_DC_MONITOR_REF,),
            for_=for_,
        )

    @overload
    def ensure(
        self,
        state: DCMonitorTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        measurement_enabled: bool | ValueRef = ...,
        integration_cycles: int | ValueRef = ...,
        measurement_delay: Quantity | ValueRef = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCMonitorTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCMonitorTarget,
            fields,
        )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorCurrentProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentProducts,
            id=id,
        )

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorVoltageProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageProducts,
            id=id,
        )


class SymbolicDCMonitorGroup(
    DeclaredStateSymbolicGroupBase[
        DCMonitorTarget, DCMonitorGroupTarget, SymbolicDCMonitorClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicDCMonitorClient,
        )

    @overload
    def ensure(
        self,
        state: DCMonitorGroupTarget | PerEntity[DCMonitorTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        measurement_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = ...,
        integration_cycles: int | ValueRef | PerEntity[int | ValueRef] = ...,
        measurement_delay: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: DCMonitorGroupTarget | PerEntity[DCMonitorTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            DCMonitorGroupTarget,
            fields,
        )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorCurrentProducts]:
        return self._clients.map(lambda client: client.measure_current(id=id))

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorVoltageProducts]:
        return self._clients.map(lambda client: client.measure_voltage(id=id))


dc_monitor: InstrumentFamily[
    DCMonitorClient,
    SymbolicDCMonitorClient,
    SymbolicDCMonitorGroup,
] = InstrumentFamily(
    DCMonitorClient,
    SymbolicDCMonitorClient,
    SymbolicDCMonitorGroup,
    requires=(_DC_MONITOR_REF,),
)


type _DCSourceMonitorPatch = DCSourcePatch | DCMonitorPatch


type _DCSourceMonitorTarget = DCSourceTarget | DCMonitorTarget


type _DCSourceMonitorGroupTarget = DCSourceGroupTarget | DCMonitorGroupTarget


class DCSourceMonitorClient(DeclaredStateClientBase[_DCSourceMonitorPatch]):
    def observation(self) -> DCSourceObservation:
        return _DC_SOURCE_OBSERVATION_DECLARATION.decode(
            self._session.observed_state(self.instrument_id)
        )

    def refresh_observation(self) -> DCSourceObservation:
        return _DC_SOURCE_OBSERVATION_DECLARATION.decode(
            self._session.read_state(self.instrument_id)
        )

    def source_voltage(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> InvokeReceipt:
        return self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )

    def measure_current(self) -> DCMonitorCurrentReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentReadback,
        )

    def measure_voltage(self) -> DCMonitorVoltageReadback:
        return self._collect(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageReadback,
        )


class SymbolicDCSourceMonitorClient(
    DeclaredStateSymbolicClientBase[_DCSourceMonitorTarget]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_DC_SOURCE_REF, _DC_MONITOR_REF),
            for_=for_,
        )

    def source_voltage(
        self,
        *,
        range: Quantity | ValueRef,
        level: Quantity | ValueRef,
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_VOLTAGE_DECLARATION.argument("level"): level,
            },
        )

    def source_current(
        self,
        *,
        range: Quantity | ValueRef,
        level: Quantity | ValueRef,
        effect_id: str | None = None,
    ) -> None:
        self._invoke(
            _DC_SOURCE_SOURCE_CURRENT_DECLARATION,
            effect_id,
            {
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("range"): range,
                _DC_SOURCE_SOURCE_CURRENT_DECLARATION.argument("level"): level,
            },
        )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorCurrentProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_CURRENT_DECLARATION,
            DCMonitorCurrentProducts,
            id=id,
        )

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> DCMonitorVoltageProducts:
        return self._acquire(
            _DC_MONITOR_MEASURE_VOLTAGE_DECLARATION,
            DCMonitorVoltageProducts,
            id=id,
        )


class SymbolicDCSourceMonitorGroup(
    DeclaredStateSymbolicGroupBase[
        _DCSourceMonitorTarget,
        _DCSourceMonitorGroupTarget,
        SymbolicDCSourceMonitorClient,
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicDCSourceMonitorClient,
        )

    def source_voltage(
        self,
        *,
        range: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        level: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_voltage(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )

    def source_current(
        self,
        *,
        range: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        level: Quantity | ValueRef | PerEntity[Quantity | ValueRef],
        effect_id: str | None = None,
    ) -> None:
        _range_by_entity = self._align(range)
        _level_by_entity = self._align(level)
        for entity in self._entities:
            self._clients[entity].source_current(
                range=_range_by_entity[entity],
                level=_level_by_entity[entity],
                effect_id=effect_id,
            )

    def measure_current(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorCurrentProducts]:
        return self._clients.map(lambda client: client.measure_current(id=id))

    def measure_voltage(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[DCMonitorVoltageProducts]:
        return self._clients.map(lambda client: client.measure_voltage(id=id))


dc_source_monitor: InstrumentFamily[
    DCSourceMonitorClient,
    SymbolicDCSourceMonitorClient,
    SymbolicDCSourceMonitorGroup,
] = InstrumentFamily(
    DCSourceMonitorClient,
    SymbolicDCSourceMonitorClient,
    SymbolicDCSourceMonitorGroup,
    requires=(_DC_SOURCE_REF, _DC_MONITOR_REF),
)


@dataclass(frozen=True, slots=True)
class NetworkSweepReadback:
    """Named sweep results plus their effect receipt."""

    frequency: MeasurementValue
    s_parameter: MeasurementValue
    receipt: CollectReceipt = field(repr=False)


@dataclass(frozen=True, slots=True)
class NetworkSweepProducts:
    """Typed logical products produced by sweep."""

    frequency: ProductRef
    s_parameter: ProductRef


class NetworkSweepClient(DeclaredStateClientBase[NetworkSweepPatch]):
    @overload
    def apply(
        self,
        patch: NetworkSweepPatch,
    ) -> ApplyReceipt: ...

    @overload
    def apply(
        self,
        *,
        start_frequency: Quantity = ...,
        stop_frequency: Quantity = ...,
        points: int = ...,
        if_bandwidth: Quantity = ...,
        source_power: Quantity = ...,
        s_parameter: Literal["S11", "S21", "S12", "S22"] = ...,
    ) -> ApplyReceipt: ...

    @override
    def apply(
        self,
        patch: NetworkSweepPatch | None = None,
        **fields: object,
    ) -> ApplyReceipt:
        return self._apply_projected(
            patch,
            NetworkSweepPatch,
            fields,
        )

    def sweep(self) -> NetworkSweepReadback:
        return self._collect(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepReadback,
        )


class SymbolicNetworkSweepClient(DeclaredStateSymbolicClientBase[NetworkSweepTarget]):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: OneEntity | None = None,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            requires=(_NETWORK_SWEEP_REF,),
            for_=for_,
        )

    @overload
    def ensure(
        self,
        state: NetworkSweepTarget,
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        start_frequency: Quantity | ValueRef = ...,
        stop_frequency: Quantity | ValueRef = ...,
        points: int | ValueRef = ...,
        if_bandwidth: Quantity | ValueRef = ...,
        source_power: Quantity | ValueRef = ...,
        s_parameter: Literal["S11", "S21", "S12", "S22"] | ValueRef = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: NetworkSweepTarget | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            NetworkSweepTarget,
            fields,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> NetworkSweepProducts:
        return self._acquire(
            _NETWORK_SWEEP_SWEEP_DECLARATION,
            NetworkSweepProducts,
            id=id,
        )


class SymbolicNetworkSweepGroup(
    DeclaredStateSymbolicGroupBase[
        NetworkSweepTarget, NetworkSweepGroupTarget, SymbolicNetworkSweepClient
    ]
):
    __slots__ = ()

    def __init__(
        self,
        recorder: SymbolicInstrumentRecorder,
        resource_id: str,
        *,
        for_: EachEntity,
    ) -> None:
        super().__init__(
            recorder,
            resource_id,
            for_=for_,
            client_factory=SymbolicNetworkSweepClient,
        )

    @overload
    def ensure(
        self,
        state: NetworkSweepGroupTarget | PerEntity[NetworkSweepTarget],
    ) -> None: ...

    @overload
    def ensure(
        self,
        *,
        start_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        stop_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        points: int | ValueRef | PerEntity[int | ValueRef] = ...,
        if_bandwidth: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        source_power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = ...,
        s_parameter: (
            Literal["S11", "S21", "S12", "S22"]
            | ValueRef
            | PerEntity[Literal["S11", "S21", "S12", "S22"] | ValueRef]
        ) = ...,
    ) -> None: ...

    @override
    def ensure(
        self,
        state: NetworkSweepGroupTarget | PerEntity[NetworkSweepTarget] | None = None,
        **fields: object,
    ) -> None:
        self._ensure_projected(
            state,
            NetworkSweepGroupTarget,
            fields,
        )

    def sweep(
        self,
        *,
        id: str | None = None,
    ) -> PerEntity[NetworkSweepProducts]:
        return self._clients.map(lambda client: client.sweep(id=id))


network_sweep: InstrumentFamily[
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
] = InstrumentFamily(
    NetworkSweepClient,
    SymbolicNetworkSweepClient,
    SymbolicNetworkSweepGroup,
    requires=(_NETWORK_SWEEP_REF,),
)

__all__ = [
    "DCMonitorClient",
    "DCMonitorCurrentProducts",
    "DCMonitorCurrentReadback",
    "DCMonitorVoltageProducts",
    "DCMonitorVoltageReadback",
    "DCSourceClient",
    "DCSourceMonitorClient",
    "NetworkSweepClient",
    "NetworkSweepProducts",
    "NetworkSweepReadback",
    "RFOutputClient",
    "SymbolicDCMonitorClient",
    "SymbolicDCMonitorGroup",
    "SymbolicDCSourceClient",
    "SymbolicDCSourceGroup",
    "SymbolicDCSourceMonitorClient",
    "SymbolicDCSourceMonitorGroup",
    "SymbolicInstrumentRecorder",
    "SymbolicNetworkSweepClient",
    "SymbolicNetworkSweepGroup",
    "SymbolicRFOutputClient",
    "SymbolicRFOutputGroup",
    "SymbolicTemperatureReadoutClient",
    "SymbolicTemperatureReadoutGroup",
    "TemperatureReadback",
    "TemperatureReadoutClient",
    "TemperatureSampleProducts",
    "dc_monitor",
    "dc_source",
    "dc_source_monitor",
    "network_sweep",
    "rf_output",
    "temperature_readout",
]
