# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Measurement-valued observations generated for instrument drivers."""

from __future__ import annotations

from dataclasses import dataclass, field

from pydantic import JsonValue
from scopecat.records.measurement import MeasurementAcquisitionValue


@dataclass(frozen=True, slots=True)
class TemperatureSampleObservation:
    """Measurement-valued acquisition observation."""

    temperature: MeasurementAcquisitionValue
    resistance: MeasurementAcquisitionValue
    evidence: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DCMonitorCurrentObservation:
    """Measurement-valued acquisition observation."""

    current: MeasurementAcquisitionValue
    evidence: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DCMonitorVoltageObservation:
    """Measurement-valued acquisition observation."""

    voltage: MeasurementAcquisitionValue
    evidence: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class NetworkSweepObservation:
    """Measurement-valued acquisition observation."""

    frequency: MeasurementAcquisitionValue
    s_parameter: MeasurementAcquisitionValue
    evidence: dict[str, JsonValue] = field(default_factory=dict)


__all__ = [
    "DCMonitorCurrentObservation",
    "DCMonitorVoltageObservation",
    "NetworkSweepObservation",
    "TemperatureSampleObservation",
]
