# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver state codecs generated from instrument interfaces."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Literal, TypedDict, cast

from pydantic import JsonValue
from scopecat.kernel.quantity import Quantity
from scopecat.sdk.instruments import (
    DriverScalar,
    DriverState,
    DriverStatePatch,
    PropertyRef,
)

from scopecat_instruments.interface_declarations import (
    DCBiasState,
    DCMonitorState,
    DCSourceState,
    NetworkSweepState,
    RFOutputState,
    TemperatureReadoutState,
)
from scopecat_instruments.members import (
    DC_BIAS_ACTUAL_VOLTAGE,
    DC_BIAS_RAMP_DURATION,
    DC_BIAS_SETTLE_TOLERANCE,
    DC_BIAS_SETTLED,
    DC_BIAS_TARGET_VOLTAGE,
    DC_MONITOR_INTEGRATION_CYCLES,
    DC_MONITOR_MEASUREMENT_DELAY,
    DC_MONITOR_MEASUREMENT_ENABLED,
    DC_SOURCE_CURRENT_PROTECTION,
    DC_SOURCE_MODE,
    DC_SOURCE_OUTPUT_ENABLED,
    DC_SOURCE_VOLTAGE_PROTECTION,
    NETWORK_SWEEP_IF_BANDWIDTH,
    NETWORK_SWEEP_POINTS,
    NETWORK_SWEEP_S_PARAMETER,
    NETWORK_SWEEP_SOURCE_POWER,
    NETWORK_SWEEP_START_FREQUENCY,
    NETWORK_SWEEP_STOP_FREQUENCY,
    RF_OUTPUT_ENABLED,
    RF_OUTPUT_FREQUENCY,
    RF_OUTPUT_POWER,
    RF_OUTPUT_REFERENCE_SOURCE,
    TEMPERATURE_READOUT_AUTOSCAN_ENABLED,
    TEMPERATURE_READOUT_SCAN_CHANNEL,
)


def encode_temperature_readout_state(
    state: TemperatureReadoutState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        TEMPERATURE_READOUT_SCAN_CHANNEL: state.scan_channel,
        TEMPERATURE_READOUT_AUTOSCAN_ENABLED: state.autoscan_enabled,
    }


class RFOutputDriverPatch(TypedDict, total=False):
    frequency: Quantity
    power: Quantity
    output_enabled: bool
    reference_source: Literal["internal", "external"]


def decode_rf_output_patch(request: DriverStatePatch, /) -> RFOutputDriverPatch:
    decoded: RFOutputDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if RF_OUTPUT_FREQUENCY in values:
        decoded["frequency"] = cast(
            "Quantity",
            values[RF_OUTPUT_FREQUENCY],
        )
    if RF_OUTPUT_POWER in values:
        decoded["power"] = cast(
            "Quantity",
            values[RF_OUTPUT_POWER],
        )
    if RF_OUTPUT_ENABLED in values:
        decoded["output_enabled"] = cast(
            "bool",
            values[RF_OUTPUT_ENABLED],
        )
    if RF_OUTPUT_REFERENCE_SOURCE in values:
        decoded["reference_source"] = cast(
            'Literal["internal", "external"]',
            values[RF_OUTPUT_REFERENCE_SOURCE],
        )
    return decoded


def encode_rf_output_state(state: RFOutputState, /) -> dict[PropertyRef, DriverScalar]:
    return {
        RF_OUTPUT_FREQUENCY: state.frequency,
        RF_OUTPUT_POWER: state.power,
        RF_OUTPUT_ENABLED: state.output_enabled,
        RF_OUTPUT_REFERENCE_SOURCE: state.reference_source,
    }


class DCBiasDriverPatch(TypedDict, total=False):
    target_voltage: Quantity
    ramp_duration: Quantity
    settle_tolerance: Quantity


def decode_dc_bias_patch(request: DriverStatePatch, /) -> DCBiasDriverPatch:
    decoded: DCBiasDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if DC_BIAS_TARGET_VOLTAGE in values:
        decoded["target_voltage"] = cast(
            "Quantity",
            values[DC_BIAS_TARGET_VOLTAGE],
        )
    if DC_BIAS_RAMP_DURATION in values:
        decoded["ramp_duration"] = cast(
            "Quantity",
            values[DC_BIAS_RAMP_DURATION],
        )
    if DC_BIAS_SETTLE_TOLERANCE in values:
        decoded["settle_tolerance"] = cast(
            "Quantity",
            values[DC_BIAS_SETTLE_TOLERANCE],
        )
    return decoded


def encode_dc_bias_state(state: DCBiasState, /) -> dict[PropertyRef, DriverScalar]:
    return {
        DC_BIAS_TARGET_VOLTAGE: state.target_voltage,
        DC_BIAS_RAMP_DURATION: state.ramp_duration,
        DC_BIAS_SETTLE_TOLERANCE: state.settle_tolerance,
        DC_BIAS_ACTUAL_VOLTAGE: state.actual_voltage,
        DC_BIAS_SETTLED: state.settled,
    }


class DCSourceDriverPatch(TypedDict, total=False):
    voltage_protection: Quantity
    current_protection: Quantity
    output_enabled: bool


def decode_dc_source_patch(request: DriverStatePatch, /) -> DCSourceDriverPatch:
    decoded: DCSourceDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if DC_SOURCE_VOLTAGE_PROTECTION in values:
        decoded["voltage_protection"] = cast(
            "Quantity",
            values[DC_SOURCE_VOLTAGE_PROTECTION],
        )
    if DC_SOURCE_CURRENT_PROTECTION in values:
        decoded["current_protection"] = cast(
            "Quantity",
            values[DC_SOURCE_CURRENT_PROTECTION],
        )
    if DC_SOURCE_OUTPUT_ENABLED in values:
        decoded["output_enabled"] = cast(
            "bool",
            values[DC_SOURCE_OUTPUT_ENABLED],
        )
    return decoded


def encode_dc_source_state(state: DCSourceState, /) -> dict[PropertyRef, DriverScalar]:
    return {
        DC_SOURCE_VOLTAGE_PROTECTION: state.voltage_protection,
        DC_SOURCE_CURRENT_PROTECTION: state.current_protection,
        DC_SOURCE_OUTPUT_ENABLED: state.output_enabled,
        DC_SOURCE_MODE: state.source_mode,
    }


class DCMonitorDriverPatch(TypedDict, total=False):
    measurement_enabled: bool
    integration_cycles: int
    measurement_delay: Quantity


def decode_dc_monitor_patch(request: DriverStatePatch, /) -> DCMonitorDriverPatch:
    decoded: DCMonitorDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if DC_MONITOR_MEASUREMENT_ENABLED in values:
        decoded["measurement_enabled"] = cast(
            "bool",
            values[DC_MONITOR_MEASUREMENT_ENABLED],
        )
    if DC_MONITOR_INTEGRATION_CYCLES in values:
        decoded["integration_cycles"] = cast(
            "int",
            values[DC_MONITOR_INTEGRATION_CYCLES],
        )
    if DC_MONITOR_MEASUREMENT_DELAY in values:
        decoded["measurement_delay"] = cast(
            "Quantity",
            values[DC_MONITOR_MEASUREMENT_DELAY],
        )
    return decoded


def encode_dc_monitor_state(
    state: DCMonitorState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        DC_MONITOR_MEASUREMENT_ENABLED: state.measurement_enabled,
        DC_MONITOR_INTEGRATION_CYCLES: state.integration_cycles,
        DC_MONITOR_MEASUREMENT_DELAY: state.measurement_delay,
    }


class NetworkSweepDriverPatch(TypedDict, total=False):
    start_frequency: Quantity
    stop_frequency: Quantity
    points: int
    if_bandwidth: Quantity
    source_power: Quantity
    s_parameter: Literal["S11", "S21", "S12", "S22"]


def decode_network_sweep_patch(request: DriverStatePatch, /) -> NetworkSweepDriverPatch:
    decoded: NetworkSweepDriverPatch = {}
    values = {entry.target: entry.value for entry in request.entries}
    if NETWORK_SWEEP_START_FREQUENCY in values:
        decoded["start_frequency"] = cast(
            "Quantity",
            values[NETWORK_SWEEP_START_FREQUENCY],
        )
    if NETWORK_SWEEP_STOP_FREQUENCY in values:
        decoded["stop_frequency"] = cast(
            "Quantity",
            values[NETWORK_SWEEP_STOP_FREQUENCY],
        )
    if NETWORK_SWEEP_POINTS in values:
        decoded["points"] = cast(
            "int",
            values[NETWORK_SWEEP_POINTS],
        )
    if NETWORK_SWEEP_IF_BANDWIDTH in values:
        decoded["if_bandwidth"] = cast(
            "Quantity",
            values[NETWORK_SWEEP_IF_BANDWIDTH],
        )
    if NETWORK_SWEEP_SOURCE_POWER in values:
        decoded["source_power"] = cast(
            "Quantity",
            values[NETWORK_SWEEP_SOURCE_POWER],
        )
    if NETWORK_SWEEP_S_PARAMETER in values:
        decoded["s_parameter"] = cast(
            'Literal["S11", "S21", "S12", "S22"]',
            values[NETWORK_SWEEP_S_PARAMETER],
        )
    return decoded


def encode_network_sweep_state(
    state: NetworkSweepState, /
) -> dict[PropertyRef, DriverScalar]:
    return {
        NETWORK_SWEEP_START_FREQUENCY: state.start_frequency,
        NETWORK_SWEEP_STOP_FREQUENCY: state.stop_frequency,
        NETWORK_SWEEP_POINTS: state.points,
        NETWORK_SWEEP_IF_BANDWIDTH: state.if_bandwidth,
        NETWORK_SWEEP_SOURCE_POWER: state.source_power,
        NETWORK_SWEEP_S_PARAMETER: state.s_parameter,
    }


def encode_driver_state(
    *states: Mapping[PropertyRef, DriverScalar],
    metadata: dict[str, JsonValue] | None = None,
) -> DriverState:
    values: dict[PropertyRef, DriverScalar] = {}
    for state in states:
        values.update(state)
    return DriverState(
        values=values,
        metadata={} if metadata is None else metadata,
    )


__all__ = [
    "DCBiasDriverPatch",
    "DCMonitorDriverPatch",
    "DCSourceDriverPatch",
    "NetworkSweepDriverPatch",
    "RFOutputDriverPatch",
    "decode_dc_bias_patch",
    "decode_dc_monitor_patch",
    "decode_dc_source_patch",
    "decode_network_sweep_patch",
    "decode_rf_output_patch",
    "encode_dc_bias_state",
    "encode_dc_monitor_state",
    "encode_dc_source_state",
    "encode_driver_state",
    "encode_network_sweep_state",
    "encode_rf_output_state",
    "encode_temperature_readout_state",
]
