# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver adapters generated from instrument interfaces."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Literal, TypedDict

from pydantic import JsonValue
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import (
    AcquisitionResultRef,
    DriverAcquisition,
    DriverOperation,
    DriverOutcome,
    DriverReadback,
    DriverRejected,
    DriverScalar,
    DriverState,
    DriverStatePatch,
    DriverSuccess,
    PropertyRef,
)
from scopecat.sdk.problems import ProblemPhase, model_location, problem

from scopecat_instruments.driver_states import (
    DCMonitorDriverPatch,
    DCSourceDriverPatch,
    NetworkSweepDriverPatch,
    RFOutputDriverPatch,
    decode_dc_monitor_patch,
    decode_dc_source_patch,
    decode_network_sweep_patch,
    decode_rf_output_patch,
    encode_dc_monitor_state,
    encode_dc_source_current_state,
    encode_dc_source_voltage_state,
    encode_driver_state,
    encode_network_sweep_state,
    encode_rf_output_state,
    encode_temperature_readout_observation,
)
from scopecat_instruments.interface_declarations import (
    DCMonitorState,
    DCSourceState,
    DCSourceVoltageState,
    NetworkSweepState,
    RFOutputState,
    TemperatureReadoutObservation,
)
from scopecat_instruments.members import (
    DC_MONITOR_ACQUISITION,
    DC_MONITOR_CURRENT_RESULT,
    DC_MONITOR_VOLTAGE_RESULT,
    NETWORK_SWEEP_ACQUISITION,
    NETWORK_SWEEP_FREQUENCY_RESULT,
    NETWORK_SWEEP_S_PARAMETER_RESULT,
    TEMPERATURE_READOUT_RESISTANCE_RESULT,
    TEMPERATURE_READOUT_SAMPLE,
    TEMPERATURE_READOUT_TEMPERATURE_RESULT,
)


def _unsupported_driver_request(
    instrument_id: str,
    kind: str,
    member_id: str,
) -> DriverRejected:
    return DriverRejected(
        problems=(
            problem(
                f"instrument_{kind}_not_implemented",
                f"{instrument_id} does not implement {member_id}",
                phase=ProblemPhase.EXECUTION,
                location=model_location(f"driver_{kind}", member_id),
            ),
        )
    )


type TemperatureReadoutSampleDriverResultName = Literal["temperature", "resistance"]


class TemperatureReadoutSampleDriverValues(TypedDict, total=False):
    temperature: MeasurementValue
    resistance: MeasurementValue


@dataclass(frozen=True, slots=True)
class TemperatureReadoutSampleDriverReadback:
    values: TemperatureReadoutSampleDriverValues
    metadata: dict[str, JsonValue] = field(default_factory=dict)


type DCMonitorMonitorDriverResultName = Literal["current", "voltage"]


class DCMonitorMonitorDriverValues(TypedDict, total=False):
    current: MeasurementValue
    voltage: MeasurementValue


@dataclass(frozen=True, slots=True)
class DCMonitorMonitorDriverReadback:
    values: DCMonitorMonitorDriverValues
    metadata: dict[str, JsonValue] = field(default_factory=dict)


type NetworkSweepSweepDriverResultName = Literal["frequency", "s_parameter"]


class NetworkSweepSweepDriverValues(TypedDict, total=False):
    frequency: MeasurementValue
    s_parameter: MeasurementValue


@dataclass(frozen=True, slots=True)
class NetworkSweepSweepDriverReadback:
    values: NetworkSweepSweepDriverValues
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True, kw_only=True)
class TemperatureReadoutDriverSnapshot:
    observation: TemperatureReadoutObservation
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class TemperatureReadoutDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_temperature_readout_state(self) -> TemperatureReadoutDriverSnapshot: ...

    @abstractmethod
    def handle_sample(
        self,
        requested: frozenset[TemperatureReadoutSampleDriverResultName],
        /,
    ) -> DriverOutcome[TemperatureReadoutSampleDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_temperature_readout_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_temperature_readout_observation(snapshot.observation))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        del request
        return _unsupported_driver_request(self.instrument_id, "state", "state")

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == TEMPERATURE_READOUT_SAMPLE:
            requested: set[TemperatureReadoutSampleDriverResultName] = set()
            for result in request.results:
                if result == TEMPERATURE_READOUT_TEMPERATURE_RESULT:
                    requested.add("temperature")
                elif result == TEMPERATURE_READOUT_RESISTANCE_RESULT:
                    requested.add("resistance")
                else:
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome = self.handle_sample(frozenset(requested))
            if not isinstance(outcome, DriverSuccess):
                return outcome
            readback = outcome.value
            values: dict[AcquisitionResultRef, MeasurementValue] = {}
            if "temperature" in readback.values:
                values[TEMPERATURE_READOUT_TEMPERATURE_RESULT] = readback.values[
                    "temperature"
                ]
            if "resistance" in readback.values:
                values[TEMPERATURE_READOUT_RESISTANCE_RESULT] = readback.values[
                    "resistance"
                ]
            return DriverSuccess(
                DriverReadback(
                    values=values,
                    metadata=readback.metadata,
                ),
                metadata=outcome.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class RFOutputDriverSnapshot:
    state: RFOutputState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class RFOutputDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_rf_output_state(self) -> RFOutputDriverSnapshot: ...

    @abstractmethod
    def apply_rf_output_state(
        self,
        patch: RFOutputDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_rf_output_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_rf_output_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        rf_output_patch = decode_rf_output_patch(request)
        outcome = self.apply_rf_output_state(rf_output_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class DCSourceDriverSnapshot:
    state: DCSourceState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class DCSourceDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_dc_source_state(self) -> DCSourceDriverSnapshot: ...

    @abstractmethod
    def apply_dc_source_state(
        self,
        patch: DCSourceDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_dc_source_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        if isinstance(snapshot.state, DCSourceVoltageState):
            encoded.append(encode_dc_source_voltage_state(snapshot.state))
        else:
            encoded.append(encode_dc_source_current_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        dc_source_patch = decode_dc_source_patch(request)
        outcome = self.apply_dc_source_state(dc_source_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class DCSourceMonitorDriverSnapshot:
    dc_source: DCSourceState
    dc_monitor: DCMonitorState | None
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DCSourceMonitorDriverPatch:
    dc_source: DCSourceDriverPatch
    dc_monitor: DCMonitorDriverPatch


class DCSourceMonitorDriverAdapter(ABC):
    instrument_id: str

    def __init__(self, *, monitor: bool) -> None:
        self._driver_monitor_enabled = monitor

    @abstractmethod
    def read_dc_source_monitor_state(self) -> DCSourceMonitorDriverSnapshot: ...

    @abstractmethod
    def apply_dc_source_monitor_state(
        self,
        patch: DCSourceMonitorDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_monitor(
        self,
        requested: frozenset[DCMonitorMonitorDriverResultName],
        /,
    ) -> DriverOutcome[DCMonitorMonitorDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_dc_source_monitor_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        if isinstance(snapshot.dc_source, DCSourceVoltageState):
            encoded.append(encode_dc_source_voltage_state(snapshot.dc_source))
        else:
            encoded.append(encode_dc_source_current_state(snapshot.dc_source))
        if self._driver_monitor_enabled and snapshot.dc_monitor is not None:
            encoded.append(encode_dc_monitor_state(snapshot.dc_monitor))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        dc_source_patch = decode_dc_source_patch(request)
        dc_monitor_patch = decode_dc_monitor_patch(request)
        if dc_monitor_patch and not self._driver_monitor_enabled:
            return _unsupported_driver_request(
                self.instrument_id, "state", "scopecat.dc_monitor/v3"
            )
        outcome = self.apply_dc_source_monitor_state(
            DCSourceMonitorDriverPatch(
                dc_source=dc_source_patch,
                dc_monitor=dc_monitor_patch,
            )
        )
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == DC_MONITOR_ACQUISITION and self._driver_monitor_enabled:
            requested: set[DCMonitorMonitorDriverResultName] = set()
            for result in request.results:
                if result == DC_MONITOR_CURRENT_RESULT:
                    requested.add("current")
                elif result == DC_MONITOR_VOLTAGE_RESULT:
                    requested.add("voltage")
                else:
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome = self.handle_monitor(frozenset(requested))
            if not isinstance(outcome, DriverSuccess):
                return outcome
            readback = outcome.value
            values: dict[AcquisitionResultRef, MeasurementValue] = {}
            if "current" in readback.values:
                values[DC_MONITOR_CURRENT_RESULT] = readback.values["current"]
            if "voltage" in readback.values:
                values[DC_MONITOR_VOLTAGE_RESULT] = readback.values["voltage"]
            return DriverSuccess(
                DriverReadback(
                    values=values,
                    metadata=readback.metadata,
                ),
                metadata=outcome.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class NetworkSweepDriverSnapshot:
    state: NetworkSweepState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class NetworkSweepDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_network_sweep_state(self) -> NetworkSweepDriverSnapshot: ...

    @abstractmethod
    def apply_network_sweep_state(
        self,
        patch: NetworkSweepDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_sweep(
        self,
        requested: frozenset[NetworkSweepSweepDriverResultName],
        /,
    ) -> DriverOutcome[NetworkSweepSweepDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_network_sweep_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_network_sweep_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        network_sweep_patch = decode_network_sweep_patch(request)
        outcome = self.apply_network_sweep_state(network_sweep_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == NETWORK_SWEEP_ACQUISITION:
            requested: set[NetworkSweepSweepDriverResultName] = set()
            for result in request.results:
                if result == NETWORK_SWEEP_FREQUENCY_RESULT:
                    requested.add("frequency")
                elif result == NETWORK_SWEEP_S_PARAMETER_RESULT:
                    requested.add("s_parameter")
                else:
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome = self.handle_sweep(frozenset(requested))
            if not isinstance(outcome, DriverSuccess):
                return outcome
            readback = outcome.value
            values: dict[AcquisitionResultRef, MeasurementValue] = {}
            if "frequency" in readback.values:
                values[NETWORK_SWEEP_FREQUENCY_RESULT] = readback.values["frequency"]
            if "s_parameter" in readback.values:
                values[NETWORK_SWEEP_S_PARAMETER_RESULT] = readback.values[
                    "s_parameter"
                ]
            return DriverSuccess(
                DriverReadback(
                    values=values,
                    metadata=readback.metadata,
                ),
                metadata=outcome.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


__all__ = [
    "DCMonitorMonitorDriverReadback",
    "DCMonitorMonitorDriverResultName",
    "DCMonitorMonitorDriverValues",
    "DCSourceDriverAdapter",
    "DCSourceDriverSnapshot",
    "DCSourceMonitorDriverAdapter",
    "DCSourceMonitorDriverPatch",
    "DCSourceMonitorDriverSnapshot",
    "NetworkSweepDriverAdapter",
    "NetworkSweepDriverSnapshot",
    "NetworkSweepSweepDriverReadback",
    "NetworkSweepSweepDriverResultName",
    "NetworkSweepSweepDriverValues",
    "RFOutputDriverAdapter",
    "RFOutputDriverSnapshot",
    "TemperatureReadoutDriverAdapter",
    "TemperatureReadoutDriverSnapshot",
    "TemperatureReadoutSampleDriverReadback",
    "TemperatureReadoutSampleDriverResultName",
    "TemperatureReadoutSampleDriverValues",
]
