# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed driver adapters generated from instrument interfaces."""

from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import cast

from pydantic import JsonValue
from scopecat.kernel.quantity import Quantity
from scopecat.records.measurement import MeasurementValue
from scopecat.sdk.instruments import (
    AcquisitionResultRef,
    DriverAcquisition,
    DriverOperation,
    DriverOutcome,
    DriverReadback,
    DriverRejected,
    DriverScalar,
    DriverState,
    DriverStatePatch,
    DriverSuccess,
    PropertyRef,
)
from scopecat.sdk.problems import ProblemPhase, model_location, problem

from scopecat_instruments.driver_states import (
    DCMonitorDriverPatch,
    DCSourceDriverPatch,
    NetworkSweepDriverPatch,
    RFOutputDriverPatch,
    decode_dc_monitor_patch,
    decode_dc_source_patch,
    decode_network_sweep_patch,
    decode_rf_output_patch,
    encode_dc_monitor_state,
    encode_dc_source_observation,
    encode_dc_source_state,
    encode_driver_state,
    encode_network_sweep_state,
    encode_rf_output_state,
    encode_temperature_readout_observation,
)
from scopecat_instruments.interface_declarations import (
    DCMonitorState,
    DCSourceObservation,
    DCSourceState,
    NetworkSweepState,
    RFOutputState,
    TemperatureReadoutObservation,
)
from scopecat_instruments.members import (
    DC_MONITOR_CURRENT_RESULT,
    DC_MONITOR_MEASURE_CURRENT,
    DC_MONITOR_MEASURE_VOLTAGE,
    DC_MONITOR_VOLTAGE_RESULT,
    DC_SOURCE_CURRENT,
    DC_SOURCE_VOLTAGE,
    NETWORK_SWEEP_ACQUISITION,
    NETWORK_SWEEP_FREQUENCY_RESULT,
    NETWORK_SWEEP_S_PARAMETER_RESULT,
    TEMPERATURE_READOUT_RESISTANCE_RESULT,
    TEMPERATURE_READOUT_SAMPLE,
    TEMPERATURE_READOUT_TEMPERATURE_RESULT,
)


def _unsupported_driver_request(
    instrument_id: str,
    kind: str,
    member_id: str,
) -> DriverRejected:
    return DriverRejected(
        problems=(
            problem(
                f"instrument_{kind}_not_implemented",
                f"{instrument_id} does not implement {member_id}",
                phase=ProblemPhase.EXECUTION,
                location=model_location(f"driver_{kind}", member_id),
            ),
        )
    )


@dataclass(frozen=True, slots=True)
class TemperatureReadoutSampleDriverReadback:
    temperature: MeasurementValue
    resistance: MeasurementValue
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DCMonitorMeasureCurrentDriverReadback:
    current: MeasurementValue
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DCMonitorMeasureVoltageDriverReadback:
    voltage: MeasurementValue
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class NetworkSweepSweepDriverReadback:
    frequency: MeasurementValue
    s_parameter: MeasurementValue
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True, kw_only=True)
class TemperatureReadoutDriverSnapshot:
    observation: TemperatureReadoutObservation
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class TemperatureReadoutDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_temperature_readout_state(self) -> TemperatureReadoutDriverSnapshot: ...

    @abstractmethod
    def handle_sample(
        self,
    ) -> DriverOutcome[TemperatureReadoutSampleDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_temperature_readout_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_temperature_readout_observation(snapshot.observation))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        del request
        return _unsupported_driver_request(self.instrument_id, "state", "state")

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == TEMPERATURE_READOUT_SAMPLE:
            for result in request.results:
                if result not in (
                    TEMPERATURE_READOUT_TEMPERATURE_RESULT,
                    TEMPERATURE_READOUT_RESISTANCE_RESULT,
                ):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_sample = self.handle_sample()
            if not isinstance(outcome_sample, DriverSuccess):
                return outcome_sample
            readback_sample = outcome_sample.value
            values_sample: dict[AcquisitionResultRef, MeasurementValue] = {}
            if TEMPERATURE_READOUT_TEMPERATURE_RESULT in request.results:
                values_sample[TEMPERATURE_READOUT_TEMPERATURE_RESULT] = (
                    readback_sample.temperature
                )
            if TEMPERATURE_READOUT_RESISTANCE_RESULT in request.results:
                values_sample[TEMPERATURE_READOUT_RESISTANCE_RESULT] = (
                    readback_sample.resistance
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_sample,
                    metadata=readback_sample.metadata,
                ),
                metadata=outcome_sample.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class RFOutputDriverSnapshot:
    state: RFOutputState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class RFOutputDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_rf_output_state(self) -> RFOutputDriverSnapshot: ...

    @abstractmethod
    def apply_rf_output_state(
        self,
        patch: RFOutputDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_rf_output_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_rf_output_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        rf_output_patch = decode_rf_output_patch(request)
        outcome = self.apply_rf_output_state(rf_output_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class DCSourceDriverSnapshot:
    state: DCSourceState
    observation: DCSourceObservation
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class DCSourceDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_dc_source_state(self) -> DCSourceDriverSnapshot: ...

    @abstractmethod
    def apply_dc_source_state(
        self,
        patch: DCSourceDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_source_voltage(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_source_current(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> DriverOutcome[None]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_dc_source_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_dc_source_state(snapshot.state))
        encoded.append(encode_dc_source_observation(snapshot.observation))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        dc_source_patch = decode_dc_source_patch(request)
        outcome = self.apply_dc_source_state(dc_source_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        if request.target == DC_SOURCE_VOLTAGE:
            arguments = request.arguments
            outcome = self.handle_source_voltage(
                range=cast("Quantity", arguments["range"]),
                level=cast("Quantity", arguments["level"]),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        if request.target == DC_SOURCE_CURRENT:
            arguments = request.arguments
            outcome = self.handle_source_current(
                range=cast("Quantity", arguments["range"]),
                level=cast("Quantity", arguments["level"]),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class DCMonitorDriverSnapshot:
    state: DCMonitorState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class DCMonitorDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_dc_monitor_state(self) -> DCMonitorDriverSnapshot: ...

    @abstractmethod
    def apply_dc_monitor_state(
        self,
        patch: DCMonitorDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_measure_current(
        self,
    ) -> DriverOutcome[DCMonitorMeasureCurrentDriverReadback]: ...

    @abstractmethod
    def handle_measure_voltage(
        self,
    ) -> DriverOutcome[DCMonitorMeasureVoltageDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_dc_monitor_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_dc_monitor_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        dc_monitor_patch = decode_dc_monitor_patch(request)
        outcome = self.apply_dc_monitor_state(dc_monitor_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == DC_MONITOR_MEASURE_CURRENT:
            for result in request.results:
                if result not in (DC_MONITOR_CURRENT_RESULT,):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_measure_current = self.handle_measure_current()
            if not isinstance(outcome_measure_current, DriverSuccess):
                return outcome_measure_current
            readback_measure_current = outcome_measure_current.value
            values_measure_current: dict[AcquisitionResultRef, MeasurementValue] = {}
            if DC_MONITOR_CURRENT_RESULT in request.results:
                values_measure_current[DC_MONITOR_CURRENT_RESULT] = (
                    readback_measure_current.current
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_measure_current,
                    metadata=readback_measure_current.metadata,
                ),
                metadata=outcome_measure_current.metadata,
            )
        if request.target == DC_MONITOR_MEASURE_VOLTAGE:
            for result in request.results:
                if result not in (DC_MONITOR_VOLTAGE_RESULT,):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_measure_voltage = self.handle_measure_voltage()
            if not isinstance(outcome_measure_voltage, DriverSuccess):
                return outcome_measure_voltage
            readback_measure_voltage = outcome_measure_voltage.value
            values_measure_voltage: dict[AcquisitionResultRef, MeasurementValue] = {}
            if DC_MONITOR_VOLTAGE_RESULT in request.results:
                values_measure_voltage[DC_MONITOR_VOLTAGE_RESULT] = (
                    readback_measure_voltage.voltage
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_measure_voltage,
                    metadata=readback_measure_voltage.metadata,
                ),
                metadata=outcome_measure_voltage.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class DCSourceMonitorDriverSnapshot:
    dc_source: DCSourceState
    dc_source_observation: DCSourceObservation
    dc_monitor: DCMonitorState | None
    metadata: dict[str, JsonValue] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class DCSourceMonitorDriverPatch:
    dc_source: DCSourceDriverPatch
    dc_monitor: DCMonitorDriverPatch


class DCSourceMonitorDriverAdapter(ABC):
    instrument_id: str

    def __init__(self, *, monitor: bool) -> None:
        self._driver_monitor_enabled = monitor

    @abstractmethod
    def read_dc_source_monitor_state(self) -> DCSourceMonitorDriverSnapshot: ...

    @abstractmethod
    def apply_dc_source_monitor_state(
        self,
        patch: DCSourceMonitorDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_source_voltage(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_source_current(
        self,
        *,
        range: Quantity,
        level: Quantity,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_measure_current(
        self,
    ) -> DriverOutcome[DCMonitorMeasureCurrentDriverReadback]: ...

    @abstractmethod
    def handle_measure_voltage(
        self,
    ) -> DriverOutcome[DCMonitorMeasureVoltageDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_dc_source_monitor_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_dc_source_state(snapshot.dc_source))
        encoded.append(encode_dc_source_observation(snapshot.dc_source_observation))
        if self._driver_monitor_enabled and snapshot.dc_monitor is not None:
            encoded.append(encode_dc_monitor_state(snapshot.dc_monitor))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        dc_source_patch = decode_dc_source_patch(request)
        dc_monitor_patch = decode_dc_monitor_patch(request)
        if dc_monitor_patch and not self._driver_monitor_enabled:
            return _unsupported_driver_request(
                self.instrument_id, "state", "scopecat.dc_monitor/v4"
            )
        outcome = self.apply_dc_source_monitor_state(
            DCSourceMonitorDriverPatch(
                dc_source=dc_source_patch,
                dc_monitor=dc_monitor_patch,
            )
        )
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        if request.target == DC_SOURCE_VOLTAGE:
            arguments = request.arguments
            outcome = self.handle_source_voltage(
                range=cast("Quantity", arguments["range"]),
                level=cast("Quantity", arguments["level"]),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        if request.target == DC_SOURCE_CURRENT:
            arguments = request.arguments
            outcome = self.handle_source_current(
                range=cast("Quantity", arguments["range"]),
                level=cast("Quantity", arguments["level"]),
            )
            if isinstance(outcome, DriverSuccess):
                return DriverSuccess(None, metadata=outcome.metadata)
            return outcome
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == DC_MONITOR_MEASURE_CURRENT:
            for result in request.results:
                if result not in (DC_MONITOR_CURRENT_RESULT,):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_measure_current = self.handle_measure_current()
            if not isinstance(outcome_measure_current, DriverSuccess):
                return outcome_measure_current
            readback_measure_current = outcome_measure_current.value
            values_measure_current: dict[AcquisitionResultRef, MeasurementValue] = {}
            if DC_MONITOR_CURRENT_RESULT in request.results:
                values_measure_current[DC_MONITOR_CURRENT_RESULT] = (
                    readback_measure_current.current
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_measure_current,
                    metadata=readback_measure_current.metadata,
                ),
                metadata=outcome_measure_current.metadata,
            )
        if request.target == DC_MONITOR_MEASURE_VOLTAGE:
            for result in request.results:
                if result not in (DC_MONITOR_VOLTAGE_RESULT,):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_measure_voltage = self.handle_measure_voltage()
            if not isinstance(outcome_measure_voltage, DriverSuccess):
                return outcome_measure_voltage
            readback_measure_voltage = outcome_measure_voltage.value
            values_measure_voltage: dict[AcquisitionResultRef, MeasurementValue] = {}
            if DC_MONITOR_VOLTAGE_RESULT in request.results:
                values_measure_voltage[DC_MONITOR_VOLTAGE_RESULT] = (
                    readback_measure_voltage.voltage
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_measure_voltage,
                    metadata=readback_measure_voltage.metadata,
                ),
                metadata=outcome_measure_voltage.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


@dataclass(frozen=True, slots=True, kw_only=True)
class NetworkSweepDriverSnapshot:
    state: NetworkSweepState
    metadata: dict[str, JsonValue] = field(default_factory=dict)


class NetworkSweepDriverAdapter(ABC):
    instrument_id: str

    @abstractmethod
    def read_network_sweep_state(self) -> NetworkSweepDriverSnapshot: ...

    @abstractmethod
    def apply_network_sweep_state(
        self,
        patch: NetworkSweepDriverPatch,
        /,
    ) -> DriverOutcome[None]: ...

    @abstractmethod
    def handle_sweep(
        self,
    ) -> DriverOutcome[NetworkSweepSweepDriverReadback]: ...

    def read_state(self) -> DriverState:
        snapshot = self.read_network_sweep_state()
        encoded: list[Mapping[PropertyRef, DriverScalar]] = []
        encoded.append(encode_network_sweep_state(snapshot.state))
        return encode_driver_state(*encoded, metadata=snapshot.metadata)

    def apply_state(
        self,
        request: DriverStatePatch,
    ) -> DriverOutcome[DriverState | None]:
        network_sweep_patch = decode_network_sweep_patch(request)
        outcome = self.apply_network_sweep_state(network_sweep_patch)
        if isinstance(outcome, DriverSuccess):
            return DriverSuccess(None, metadata=outcome.metadata)
        return outcome

    def invoke(
        self,
        request: DriverOperation,
    ) -> DriverOutcome[DriverState | None]:
        return _unsupported_driver_request(
            self.instrument_id,
            "operation",
            request.target.operation_id,
        )

    def collect(
        self,
        request: DriverAcquisition,
    ) -> DriverOutcome[DriverReadback]:
        if request.target == NETWORK_SWEEP_ACQUISITION:
            for result in request.results:
                if result not in (
                    NETWORK_SWEEP_FREQUENCY_RESULT,
                    NETWORK_SWEEP_S_PARAMETER_RESULT,
                ):
                    return _unsupported_driver_request(
                        self.instrument_id,
                        "acquisition_result",
                        result.result_id,
                    )
            outcome_sweep = self.handle_sweep()
            if not isinstance(outcome_sweep, DriverSuccess):
                return outcome_sweep
            readback_sweep = outcome_sweep.value
            values_sweep: dict[AcquisitionResultRef, MeasurementValue] = {}
            if NETWORK_SWEEP_FREQUENCY_RESULT in request.results:
                values_sweep[NETWORK_SWEEP_FREQUENCY_RESULT] = readback_sweep.frequency
            if NETWORK_SWEEP_S_PARAMETER_RESULT in request.results:
                values_sweep[NETWORK_SWEEP_S_PARAMETER_RESULT] = (
                    readback_sweep.s_parameter
                )
            return DriverSuccess(
                DriverReadback(
                    values=values_sweep,
                    metadata=readback_sweep.metadata,
                ),
                metadata=outcome_sweep.metadata,
            )
        return _unsupported_driver_request(
            self.instrument_id,
            "acquisition",
            request.target.acquisition_id,
        )


__all__ = [
    "DCMonitorDriverAdapter",
    "DCMonitorDriverSnapshot",
    "DCMonitorMeasureCurrentDriverReadback",
    "DCMonitorMeasureVoltageDriverReadback",
    "DCSourceDriverAdapter",
    "DCSourceDriverSnapshot",
    "DCSourceMonitorDriverAdapter",
    "DCSourceMonitorDriverPatch",
    "DCSourceMonitorDriverSnapshot",
    "NetworkSweepDriverAdapter",
    "NetworkSweepDriverSnapshot",
    "NetworkSweepSweepDriverReadback",
    "RFOutputDriverAdapter",
    "RFOutputDriverSnapshot",
    "TemperatureReadoutDriverAdapter",
    "TemperatureReadoutDriverSnapshot",
    "TemperatureReadoutSampleDriverReadback",
]
