# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Vendor-neutral interface factories generated from Python declarations."""

from __future__ import annotations

from scopecat.sdk.instruments import InterfaceSpec

_TEMPERATURE_READOUT_SPEC_JSON = (
    '{"id":"scopecat.temperature_readout/v1",'
    '"label":"Temperature readout","descripti'
    'on":"Read-only scanner state and settled'
    " temperature or resistance acquisition. "
    "Heater control belongs to a separate int"
    'erface.","properties":[{"id":"scan_chann'
    'el","label":"Scan channel","description"'
    ':"Sensor input currently selected by the'
    ' scanner.","access":"read_only","capture'
    '":true,"restore":false,"value_type":{"ty'
    'pe":"int","minimum":1,"maximum":90071992'
    '54740991}},{"id":"autoscan_enabled","lab'
    'el":"Autoscan","description":"Whether th'
    "e input scanner is advancing automatical"
    'ly.","access":"read_only","capture":true'
    ',"restore":false,"value_type":{"type":"b'
    'ool"}}],"operations":[],"acquisitions":['
    '{"id":"sample","label":"Sample sensor","'
    'description":"Read a settled sample from'
    ' one coherent scan channel.","preconditi'
    'ons":[],"results":[{"id":"temperature","'
    'label":"Temperature","description":"Curr'
    'ent scan-channel temperature.","role":"o'
    'bservable","dtype":"float64","unit":"K",'
    '"axes":[]},{"id":"resistance","label":"R'
    'esistance","description":"Current scan-c'
    'hannel sensor resistance.","role":"obser'
    'vable","dtype":"float64","unit":"Ohm","a'
    'xes":[]}]}],"components":[]}'
)


def temperature_readout_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_TEMPERATURE_READOUT_SPEC_JSON)


_RF_OUTPUT_SPEC_JSON = (
    '{"id":"scopecat.rf_output/v1","label":"R'
    'F output","description":"Continuous-wave'
    " RF source controls independent of vendo"
    'r syntax.","properties":[{"id":"frequenc'
    'y","label":"CW frequency","description":'
    '"Continuous-wave carrier frequency.","ac'
    'cess":"read_write","capture":true,"resto'
    're":true,"value_type":{"type":"quantity"'
    ',"dimension":null,"unit":"Hz","minimum":'
    'null,"maximum":null,"finite":true}},{"id'
    '":"power","label":"Output power","descri'
    'ption":"Configured RF output level at th'
    'e source connector.","access":"read_writ'
    'e","capture":true,"restore":true,"value_'
    'type":{"type":"quantity","dimension":nul'
    'l,"unit":"dBm","minimum":null,"maximum":'
    'null,"finite":true}},{"id":"output_enabl'
    'ed","label":"RF output","description":"W'
    "hether the RF output connector is enable"
    'd.","access":"read_write","capture":true'
    ',"restore":true,"value_type":{"type":"bo'
    'ol"}},{"id":"reference_source","label":"'
    'Reference source","description":"Referen'
    "ce oscillator source; external frequency"
    ' is not set.","access":"read_write","cap'
    'ture":true,"restore":true,"value_type":{'
    '"type":"string","choices":["internal","e'
    'xternal"]}}],"operations":[],"acquisitio'
    'ns":[],"components":[]}'
)


def rf_output_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_RF_OUTPUT_SPEC_JSON)


_DC_BIAS_SPEC_JSON = (
    '{"id":"scopecat.dc_bias/v1","label":"DC '
    'bias ramp","description":"Settled voltag'
    "e transitions that a multi-channel devic"
    'e may apply as one coherent batch.","pro'
    'perties":[{"id":"target_voltage","label"'
    ':"Target voltage","description":"Request'
    "ed final voltage for this routed channel"
    '.","access":"read_write","capture":true,'
    '"restore":true,"value_type":{"type":"qua'
    'ntity","dimension":null,"unit":"V","mini'
    'mum":null,"maximum":null,"finite":true}}'
    ',{"id":"ramp_duration","label":"Ramp dur'
    'ation","description":"Minimum duration f'
    "or the transition to the target voltage."
    '","access":"read_write","capture":true,"'
    'restore":true,"value_type":{"type":"quan'
    'tity","dimension":null,"unit":"s","minim'
    'um":0.0,"maximum":null,"finite":true}},{'
    '"id":"settle_tolerance","label":"Settle '
    'tolerance","description":"Maximum readba'
    "ck error accepted before the batch compl"
    'etes.","access":"read_write","capture":t'
    'rue,"restore":true,"value_type":{"type":'
    '"quantity","dimension":null,"unit":"V","'
    'minimum":0.0,"maximum":null,"finite":tru'
    'e}},{"id":"actual_voltage","label":"Actu'
    'al voltage","description":"Voltage read '
    'back after the most recent transition.",'
    '"access":"read_only","capture":true,"res'
    'tore":false,"value_type":{"type":"quanti'
    'ty","dimension":null,"unit":"V","minimum'
    '":null,"maximum":null,"finite":true}},{"'
    'id":"settled","label":"Settled","descrip'
    'tion":"Whether readback is within the re'
    'quested tolerance.","access":"read_only"'
    ',"capture":true,"restore":false,"value_t'
    'ype":{"type":"bool"}}],"operations":[],"'
    'acquisitions":[{"id":"readback","label":'
    '"Read back bias","description":"Read the'
    " settled voltage status for one routed c"
    'hannel.","preconditions":[],"results":[{'
    '"id":"actual_voltage","label":"Actual vo'
    'ltage","description":"Voltage read back '
    'from this routed channel.","role":"obser'
    'vable","dtype":"float64","unit":"V","axe'
    's":[]},{"id":"settled","label":"Settled"'
    ',"description":"Whether the readback is '
    'within the requested tolerance.","role":'
    '"observable","dtype":"bool","unit":null,'
    '"axes":[]}]}],"components":[]}'
)


def dc_bias_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_BIAS_SPEC_JSON)


_DC_SOURCE_SPEC_JSON = (
    '{"id":"scopecat.dc_source/v3","label":"D'
    'C source","description":"DC voltage/curr'
    "ent source transitions, protection, and "
    'output control.","properties":[{"id":"vo'
    'ltage_protection","label":"Voltage prote'
    'ction","description":"Absolute voltage l'
    'imiter level.","access":"read_write","ca'
    'pture":true,"restore":true,"value_type":'
    '{"type":"quantity","dimension":null,"uni'
    't":"V","minimum":null,"maximum":null,"fi'
    'nite":true}},{"id":"current_protection",'
    '"label":"Current protection","descriptio'
    'n":"Absolute current limiter level.","ac'
    'cess":"read_write","capture":true,"resto'
    're":true,"value_type":{"type":"quantity"'
    ',"dimension":null,"unit":"A","minimum":n'
    'ull,"maximum":null,"finite":true}},{"id"'
    ':"output_enabled","label":"DC output","d'
    'escription":"Whether the source output i'
    's enabled.","access":"read_write","captu'
    're":true,"restore":true,"value_type":{"t'
    'ype":"bool"}},{"id":"source_mode","label'
    '":"Source mode","description":"Whether t'
    "he instrument is currently sourcing volt"
    'age or current.","access":"read_only","c'
    'apture":true,"restore":false,"value_type'
    '":{"type":"string","choices":["voltage",'
    '"current"]}}],"operations":[{"id":"sourc'
    'e_voltage","label":"Source voltage","des'
    'cription":"Select voltage-source mode an'
    'd set its range and level.","arguments":'
    '[{"id":"range","label":null,"description'
    '":null,"value_type":{"type":"quantity","'
    'dimension":null,"unit":"V","minimum":nul'
    'l,"maximum":null,"finite":true}},{"id":"'
    'level","label":null,"description":null,"'
    'value_type":{"type":"quantity","dimensio'
    'n":null,"unit":"V","minimum":null,"maxim'
    'um":null,"finite":true}}],"invalidates":'
    '[]},{"id":"source_current","label":"Sour'
    'ce current","description":"Select curren'
    "t-source mode and set its range and leve"
    'l.","arguments":[{"id":"range","label":n'
    'ull,"description":null,"value_type":{"ty'
    'pe":"quantity","dimension":null,"unit":"'
    'A","minimum":null,"maximum":null,"finite'
    '":true}},{"id":"level","label":null,"des'
    'cription":null,"value_type":{"type":"qua'
    'ntity","dimension":null,"unit":"A","mini'
    'mum":null,"maximum":null,"finite":true}}'
    '],"invalidates":[]}],"acquisitions":[],"'
    'components":[]}'
)


def dc_source_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_SOURCE_SPEC_JSON)


_DC_MONITOR_SPEC_JSON = (
    '{"id":"scopecat.dc_monitor/v4","label":"'
    'DC monitor","description":"Independent c'
    "urrent and voltage measurements for a DC"
    ' source.","properties":[{"id":"measureme'
    'nt_enabled","label":"Measurement","descr'
    'iption":"Whether monitor measurements ar'
    'e enabled.","access":"read_write","captu'
    're":true,"restore":true,"value_type":{"t'
    'ype":"bool"}},{"id":"integration_cycles"'
    ',"label":"Integration cycles","descripti'
    'on":"Power-line cycles integrated for ea'
    'ch measurement.","access":"read_write","'
    'capture":true,"restore":true,"value_type'
    '":{"type":"int","minimum":1,"maximum":90'
    '07199254740991}},{"id":"measurement_dela'
    'y","label":"Measurement delay","descript'
    'ion":"Delay between measurement trigger '
    'and sampling.","access":"read_write","ca'
    'pture":true,"restore":true,"value_type":'
    '{"type":"quantity","dimension":null,"uni'
    't":"s","minimum":0.0,"maximum":null,"fin'
    'ite":true}}],"operations":[],"acquisitio'
    'ns":[{"id":"measure_current","label":"Me'
    'asure current","description":"Measure cu'
    "rrent while the source is operating in v"
    'oltage mode.","preconditions":[],"result'
    's":[{"id":"monitored_current","label":"M'
    'onitored current","description":"One mea'
    'surement while sourcing voltage.","role"'
    ':"observable","dtype":"float64","unit":"'
    'A","axes":[]}]},{"id":"measure_voltage",'
    '"label":"Measure voltage","description":'
    '"Measure voltage while the source is ope'
    'rating in current mode.","preconditions"'
    ':[],"results":[{"id":"monitored_voltage"'
    ',"label":"Monitored voltage","descriptio'
    'n":"One measurement while sourcing curre'
    'nt.","role":"observable","dtype":"float6'
    '4","unit":"V","axes":[]}]}],"components"'
    ":[]}"
)


def dc_monitor_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_MONITOR_SPEC_JSON)


_NETWORK_SWEEP_SPEC_JSON = (
    '{"id":"scopecat.network_sweep/v1","label'
    '":"Network sweep","description":"Linear,'
    " single-trigger complex S-parameter swee"
    'p.","properties":[{"id":"start_frequency'
    '","label":"Start frequency","description'
    '":"First stimulus frequency in the linea'
    'r sweep.","access":"read_write","capture'
    '":true,"restore":true,"value_type":{"typ'
    'e":"quantity","dimension":null,"unit":"H'
    'z","minimum":null,"maximum":null,"finite'
    '":true}},{"id":"stop_frequency","label":'
    '"Stop frequency","description":"Last sti'
    'mulus frequency in the linear sweep.","a'
    'ccess":"read_write","capture":true,"rest'
    'ore":true,"value_type":{"type":"quantity'
    '","dimension":null,"unit":"Hz","minimum"'
    ':null,"maximum":null,"finite":true}},{"i'
    'd":"points","label":"Sweep points","desc'
    'ription":"Number of equally spaced frequ'
    'ency points.","access":"read_write","cap'
    'ture":true,"restore":true,"value_type":{'
    '"type":"int","minimum":2,"maximum":90071'
    '99254740991}},{"id":"if_bandwidth","labe'
    'l":"IF bandwidth","description":"Receive'
    'r intermediate-frequency bandwidth.","ac'
    'cess":"read_write","capture":true,"resto'
    're":true,"value_type":{"type":"quantity"'
    ',"dimension":null,"unit":"Hz","minimum":'
    'null,"maximum":null,"finite":true}},{"id'
    '":"source_power","label":"Source power",'
    '"description":"Stimulus power for the se'
    'lected analyzer channel.","access":"read'
    '_write","capture":true,"restore":true,"v'
    'alue_type":{"type":"quantity","dimension'
    '":null,"unit":"dBm","minimum":null,"maxi'
    'mum":null,"finite":true}},{"id":"s_param'
    'eter","label":"S-parameter","description'
    '":"Two-port S-parameter measured by the '
    'selected trace.","access":"read_write","'
    'capture":true,"restore":true,"value_type'
    '":{"type":"string","choices":["S11","S21'
    '","S12","S22"]}}],"operations":[],"acqui'
    'sitions":[{"id":"sweep","label":"Acquire'
    ' sweep","description":"Trigger and read '
    'the configured network sweep.","precondi'
    'tions":[],"results":[{"id":"frequency","'
    'label":"Frequency","description":"Stimul'
    "us frequency values for the acquired tra"
    'ce.","role":"coordinate","dtype":"float6'
    '4","unit":"Hz","axes":[{"id":"frequency"'
    ',"label":"Frequency","description":"Line'
    'ar VNA stimulus frequency.","kind":"freq'
    'uency","size":{"interface_id":"scopecat.'
    'network_sweep/v1","component_path":[],"p'
    'roperty_id":"points"},"unit":"Hz"}]},{"i'
    'd":"s_parameter","label":"Complex S-para'
    'meter","description":"Complex response v'
    'alues for the configured S-parameter.","'
    'role":"observable","dtype":"complex128",'
    '"unit":"ratio","axes":[{"id":"frequency"'
    ',"label":"Frequency","description":"Line'
    'ar VNA stimulus frequency.","kind":"freq'
    'uency","size":{"interface_id":"scopecat.'
    'network_sweep/v1","component_path":[],"p'
    'roperty_id":"points"},"unit":"Hz"}]}]}],'
    '"components":[]}'
)


def network_sweep_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_NETWORK_SWEEP_SPEC_JSON)


__all__ = [
    "dc_bias_interface",
    "dc_monitor_interface",
    "dc_source_interface",
    "network_sweep_interface",
    "rf_output_interface",
    "temperature_readout_interface",
]
