# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Vendor-neutral interface factories generated from Python declarations."""

from __future__ import annotations

from scopecat.sdk.instruments import InterfaceSpec

_TEMPERATURE_READOUT_SPEC_JSON = (
    '{"id":"scopecat.temperature_readout/v1",'
    '"label":"Temperature readout","descripti'
    'on":"Read-only scanner state and settled'
    " temperature or resistance acquisition. "
    "Heater control belongs to a separate int"
    'erface.","properties":[{"id":"scan_chann'
    'el","label":"Scan channel","description"'
    ':"Sensor input currently selected by the'
    ' scanner.","access":"read_only","value_t'
    'ype":{"type":"int","minimum":1,"maximum"'
    ':9007199254740991}},{"id":"autoscan_enab'
    'led","label":"Autoscan","description":"W'
    "hether the input scanner is advancing au"
    'tomatically.","access":"read_only","valu'
    'e_type":{"type":"bool"}}],"operations":['
    '],"acquisitions":[{"id":"sample","label"'
    ':"Sample sensor","description":"Read a s'
    "ettled sample from one coherent scan cha"
    'nnel.","preconditions":[],"results":[{"i'
    'd":"temperature","label":"Temperature","'
    'description":"Current scan-channel tempe'
    'rature.","dtype":"float64","unit":"K","a'
    'xes":[]},{"id":"resistance","label":"Res'
    'istance","description":"Current scan-cha'
    'nnel sensor resistance.","dtype":"float6'
    '4","unit":"Ohm","axes":[]}]}],"component'
    's":[]}'
)


def temperature_readout_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_TEMPERATURE_READOUT_SPEC_JSON)


_RF_OUTPUT_SPEC_JSON = (
    '{"id":"scopecat.rf_output/v1","label":"R'
    'F output","description":"Continuous-wave'
    " RF source controls independent of vendo"
    'r syntax.","properties":[{"id":"frequenc'
    'y","label":"CW frequency","description":'
    '"Continuous-wave carrier frequency.","ac'
    'cess":"read_write","value_type":{"type":'
    '"quantity","dimension":null,"unit":"Hz",'
    '"minimum":null,"maximum":null,"finite":t'
    'rue}},{"id":"power","label":"Output powe'
    'r","description":"Configured RF output l'
    'evel at the source connector.","access":'
    '"read_write","value_type":{"type":"quant'
    'ity","dimension":null,"unit":"dBm","mini'
    'mum":null,"maximum":null,"finite":true}}'
    ',{"id":"output_enabled","label":"RF outp'
    'ut","description":"Whether the RF output'
    ' connector is enabled.","access":"read_w'
    'rite","value_type":{"type":"bool"}},{"id'
    '":"reference_source","label":"Reference '
    'source","description":"Reference oscilla'
    "tor source; external frequency is not se"
    't.","access":"read_write","value_type":{'
    '"type":"string","choices":["internal","e'
    'xternal"]}}],"operations":[],"acquisitio'
    'ns":[],"components":[]}'
)


def rf_output_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_RF_OUTPUT_SPEC_JSON)


_DC_SOURCE_SPEC_JSON = (
    '{"id":"scopecat.dc_source/v3","label":"D'
    'C source","description":"DC voltage/curr'
    "ent source transitions, protection, and "
    'output control.","properties":[{"id":"vo'
    'ltage_protection","label":"Voltage prote'
    'ction","description":"Absolute voltage l'
    'imiter level.","access":"read_write","va'
    'lue_type":{"type":"quantity","dimension"'
    ':null,"unit":"V","minimum":null,"maximum'
    '":null,"finite":true}},{"id":"current_pr'
    'otection","label":"Current protection","'
    'description":"Absolute current limiter l'
    'evel.","access":"read_write","value_type'
    '":{"type":"quantity","dimension":null,"u'
    'nit":"A","minimum":null,"maximum":null,"'
    'finite":true}},{"id":"output_enabled","l'
    'abel":"DC output","description":"Whether'
    ' the source output is enabled.","access"'
    ':"read_write","value_type":{"type":"bool'
    '"}},{"id":"source_mode","label":"Source '
    'mode","description":"Whether the instrum'
    "ent is currently sourcing voltage or cur"
    'rent.","access":"read_only","value_type"'
    ':{"type":"string","choices":["voltage","'
    'current"]}}],"operations":[{"id":"source'
    '_voltage","label":"Source voltage","desc'
    'ription":"Select voltage-source mode and'
    ' set its range and level.","arguments":['
    '{"id":"range","label":null,"description"'
    ':null,"value_type":{"type":"quantity","d'
    'imension":null,"unit":"V","minimum":null'
    ',"maximum":null,"finite":true}},{"id":"l'
    'evel","label":null,"description":null,"v'
    'alue_type":{"type":"quantity","dimension'
    '":null,"unit":"V","minimum":null,"maximu'
    'm":null,"finite":true}}]},{"id":"source_'
    'current","label":"Source current","descr'
    'iption":"Select current-source mode and '
    'set its range and level.","arguments":[{'
    '"id":"range","label":null,"description":'
    'null,"value_type":{"type":"quantity","di'
    'mension":null,"unit":"A","minimum":null,'
    '"maximum":null,"finite":true}},{"id":"le'
    'vel","label":null,"description":null,"va'
    'lue_type":{"type":"quantity","dimension"'
    ':null,"unit":"A","minimum":null,"maximum'
    '":null,"finite":true}}]}],"acquisitions"'
    ':[],"components":[]}'
)


def dc_source_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_SOURCE_SPEC_JSON)


_DC_MONITOR_SPEC_JSON = (
    '{"id":"scopecat.dc_monitor/v4","label":"'
    'DC monitor","description":"Independent c'
    "urrent and voltage measurements for a DC"
    ' source.","properties":[{"id":"measureme'
    'nt_enabled","label":"Measurement","descr'
    'iption":"Whether monitor measurements ar'
    'e enabled.","access":"read_write","value'
    '_type":{"type":"bool"}},{"id":"integrati'
    'on_cycles","label":"Integration cycles",'
    '"description":"Power-line cycles integra'
    'ted for each measurement.","access":"rea'
    'd_write","value_type":{"type":"int","min'
    'imum":1,"maximum":9007199254740991}},{"i'
    'd":"measurement_delay","label":"Measurem'
    'ent delay","description":"Delay between '
    'measurement trigger and sampling.","acce'
    'ss":"read_write","value_type":{"type":"q'
    'uantity","dimension":null,"unit":"s","mi'
    'nimum":0.0,"maximum":null,"finite":true}'
    '}],"operations":[],"acquisitions":[{"id"'
    ':"measure_current","label":"Measure curr'
    'ent","description":"Measure current whil'
    "e the source is operating in voltage mod"
    'e.","preconditions":[],"results":[{"id":'
    '"monitored_current","label":"Monitored c'
    'urrent","description":"One measurement w'
    'hile sourcing voltage.","dtype":"float64'
    '","unit":"A","axes":[]}]},{"id":"measure'
    '_voltage","label":"Measure voltage","des'
    'cription":"Measure voltage while the sou'
    'rce is operating in current mode.","prec'
    'onditions":[],"results":[{"id":"monitore'
    'd_voltage","label":"Monitored voltage","'
    'description":"One measurement while sour'
    'cing current.","dtype":"float64","unit":'
    '"V","axes":[]}]}],"components":[]}'
)


def dc_monitor_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_MONITOR_SPEC_JSON)


_NETWORK_SWEEP_SPEC_JSON = (
    '{"id":"scopecat.network_sweep/v1","label'
    '":"Network sweep","description":"Linear,'
    " single-trigger complex S-parameter swee"
    'p.","properties":[{"id":"start_frequency'
    '","label":"Start frequency","description'
    '":"First stimulus frequency in the linea'
    'r sweep.","access":"read_write","value_t'
    'ype":{"type":"quantity","dimension":null'
    ',"unit":"Hz","minimum":null,"maximum":nu'
    'll,"finite":true}},{"id":"stop_frequency'
    '","label":"Stop frequency","description"'
    ':"Last stimulus frequency in the linear '
    'sweep.","access":"read_write","value_typ'
    'e":{"type":"quantity","dimension":null,"'
    'unit":"Hz","minimum":null,"maximum":null'
    ',"finite":true}},{"id":"points","label":'
    '"Sweep points","description":"Number of '
    'equally spaced frequency points.","acces'
    's":"read_write","value_type":{"type":"in'
    't","minimum":2,"maximum":900719925474099'
    '1}},{"id":"if_bandwidth","label":"IF ban'
    'dwidth","description":"Receiver intermed'
    'iate-frequency bandwidth.","access":"rea'
    'd_write","value_type":{"type":"quantity"'
    ',"dimension":null,"unit":"Hz","minimum":'
    'null,"maximum":null,"finite":true}},{"id'
    '":"source_power","label":"Source power",'
    '"description":"Stimulus power for the se'
    'lected analyzer channel.","access":"read'
    '_write","value_type":{"type":"quantity",'
    '"dimension":null,"unit":"dBm","minimum":'
    'null,"maximum":null,"finite":true}},{"id'
    '":"s_parameter","label":"S-parameter","d'
    'escription":"Two-port S-parameter measur'
    'ed by the selected trace.","access":"rea'
    'd_write","value_type":{"type":"string","'
    'choices":["S11","S21","S12","S22"]}}],"o'
    'perations":[],"acquisitions":[{"id":"swe'
    'ep","label":"Acquire sweep","description'
    '":"Trigger and read the configured netwo'
    'rk sweep.","preconditions":[],"results":'
    '[{"id":"frequency","label":"Frequency","'
    'description":"Stimulus frequency values '
    'for the acquired trace.","dtype":"float6'
    '4","unit":"Hz","axes":[{"id":"frequency"'
    ',"label":"Frequency","description":"Line'
    'ar VNA stimulus frequency.","kind":"freq'
    'uency","size":{"interface_id":"scopecat.'
    'network_sweep/v1","component_path":[],"p'
    'roperty_id":"points"},"unit":"Hz"}]},{"i'
    'd":"s_parameter","label":"Complex S-para'
    'meter","description":"Complex response v'
    'alues for the configured S-parameter.","'
    'dtype":"complex128","unit":"ratio","axes'
    '":[{"id":"frequency","label":"Frequency"'
    ',"description":"Linear VNA stimulus freq'
    'uency.","kind":"frequency","size":{"inte'
    'rface_id":"scopecat.network_sweep/v1","c'
    'omponent_path":[],"property_id":"points"'
    '},"unit":"Hz"}]}]}],"components":[]}'
)


def network_sweep_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_NETWORK_SWEEP_SPEC_JSON)


__all__ = [
    "dc_monitor_interface",
    "dc_source_interface",
    "network_sweep_interface",
    "rf_output_interface",
    "temperature_readout_interface",
]
