# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Vendor-neutral interface factories generated from Python declarations."""

from __future__ import annotations

from scopecat.sdk.instruments import InterfaceSpec

_TEMPERATURE_READOUT_SPEC_JSON = (
    '{"id":"scopecat.temperature_readout/v1",'
    '"label":"Temperature readout","descripti'
    'on":"Read-only scanner state and settled'
    " temperature or resistance acquisition. "
    "Heater control belongs to a separate int"
    'erface.","properties":[{"id":"scan_chann'
    'el","label":"Scan channel","description"'
    ':"Sensor input currently selected by the'
    ' scanner.","access":"read_only","value_t'
    'ype":{"type":"int","minimum":1,"maximum"'
    ':9007199254740991}},{"id":"autoscan_enab'
    'led","label":"Autoscan","description":"W'
    "hether the input scanner is advancing au"
    'tomatically.","access":"read_only","valu'
    'e_type":{"type":"bool"}}],"state":null,"'
    'operations":[],"acquisitions":[{"id":"sa'
    'mple","label":"Sample sensor","descripti'
    'on":"Read a settled sample from one cohe'
    'rent scan channel.","preconditions":[],"'
    'kind":"fixed","results":[{"id":"temperat'
    'ure","label":"Temperature","description"'
    ':"Current scan-channel temperature.","dt'
    'ype":"float64","unit":"K","axes":[]},{"i'
    'd":"resistance","label":"Resistance","de'
    'scription":"Current scan-channel sensor '
    'resistance.","dtype":"float64","unit":"O'
    'hm","axes":[]}]}],"components":[]}'
)


def temperature_readout_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_TEMPERATURE_READOUT_SPEC_JSON)


_RF_OUTPUT_SPEC_JSON = (
    '{"id":"scopecat.rf_output/v1","label":"R'
    'F output","description":"Continuous-wave'
    " RF source controls independent of vendo"
    'r syntax.","properties":[{"id":"frequenc'
    'y","label":"CW frequency","description":'
    '"Continuous-wave carrier frequency.","ac'
    'cess":"read_write","value_type":{"type":'
    '"quantity","dimension":null,"unit":"Hz",'
    '"minimum":null,"maximum":null,"finite":t'
    'rue}},{"id":"power","label":"Output powe'
    'r","description":"Configured RF output l'
    'evel at the source connector.","access":'
    '"read_write","value_type":{"type":"quant'
    'ity","dimension":null,"unit":"dBm","mini'
    'mum":null,"maximum":null,"finite":true}}'
    ',{"id":"output_enabled","label":"RF outp'
    'ut","description":"Whether the RF output'
    ' connector is enabled.","access":"read_w'
    'rite","value_type":{"type":"bool"}},{"id'
    '":"reference_source","label":"Reference '
    'source","description":"Reference oscilla'
    "tor source; external frequency is not se"
    't.","access":"read_write","value_type":{'
    '"type":"string","choices":["internal","e'
    'xternal"]}}],"state":null,"operations":['
    '],"acquisitions":[],"components":[]}'
)


def rf_output_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_RF_OUTPUT_SPEC_JSON)


_DC_SOURCE_SPEC_JSON = (
    '{"id":"scopecat.dc_source/v3","label":"D'
    'C source","description":"DC voltage/curr'
    "ent source transitions, protection, and "
    'output control.","properties":[{"id":"vo'
    'ltage_protection","label":"Voltage prote'
    'ction","description":"Absolute voltage l'
    'imiter level.","access":"read_write","va'
    'lue_type":{"type":"quantity","dimension"'
    ':null,"unit":"V","minimum":null,"maximum'
    '":null,"finite":true}},{"id":"current_pr'
    'otection","label":"Current protection","'
    'description":"Absolute current limiter l'
    'evel.","access":"read_write","value_type'
    '":{"type":"quantity","dimension":null,"u'
    'nit":"A","minimum":null,"maximum":null,"'
    'finite":true}},{"id":"output_enabled","l'
    'abel":"DC output","description":"Whether'
    ' the source output is enabled.","access"'
    ':"read_write","value_type":{"type":"bool'
    '"}},{"id":"source_mode","label":"Source '
    'mode","description":"Whether the instrum'
    "ent is currently sourcing voltage or cur"
    'rent.","access":"read_only","value_type"'
    ':{"type":"string","choices":["voltage","'
    'current"]}}],"state":null,"operations":['
    '{"id":"source_voltage","label":"Source v'
    'oltage","description":"Select voltage-so'
    'urce mode and set its range and level.",'
    '"arguments":[{"id":"range","label":null,'
    '"description":null,"value_type":{"type":'
    '"quantity","dimension":null,"unit":"V","'
    'minimum":null,"maximum":null,"finite":tr'
    'ue}},{"id":"level","label":null,"descrip'
    'tion":null,"value_type":{"type":"quantit'
    'y","dimension":null,"unit":"V","minimum"'
    ':null,"maximum":null,"finite":true}}]},{'
    '"id":"source_current","label":"Source cu'
    'rrent","description":"Select current-sou'
    'rce mode and set its range and level.","'
    'arguments":[{"id":"range","label":null,"'
    'description":null,"value_type":{"type":"'
    'quantity","dimension":null,"unit":"A","m'
    'inimum":null,"maximum":null,"finite":tru'
    'e}},{"id":"level","label":null,"descript'
    'ion":null,"value_type":{"type":"quantity'
    '","dimension":null,"unit":"A","minimum":'
    'null,"maximum":null,"finite":true}}]}],"'
    'acquisitions":[],"components":[]}'
)


def dc_source_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_SOURCE_SPEC_JSON)


_DC_MONITOR_SPEC_JSON = (
    '{"id":"scopecat.dc_monitor/v4","label":"'
    'DC monitor","description":"Independent c'
    "urrent and voltage measurements for a DC"
    ' source.","properties":[{"id":"measureme'
    'nt_enabled","label":"Measurement","descr'
    'iption":"Whether monitor measurements ar'
    'e enabled.","access":"read_write","value'
    '_type":{"type":"bool"}},{"id":"integrati'
    'on_cycles","label":"Integration cycles",'
    '"description":"Power-line cycles integra'
    'ted for each measurement.","access":"rea'
    'd_write","value_type":{"type":"int","min'
    'imum":1,"maximum":9007199254740991}},{"i'
    'd":"measurement_delay","label":"Measurem'
    'ent delay","description":"Delay between '
    'measurement trigger and sampling.","acce'
    'ss":"read_write","value_type":{"type":"q'
    'uantity","dimension":null,"unit":"s","mi'
    'nimum":0.0,"maximum":null,"finite":true}'
    '}],"state":null,"operations":[],"acquisi'
    'tions":[{"id":"measure_current","label":'
    '"Measure current","description":"Measure'
    " current while the source is operating i"
    'n voltage mode.","preconditions":[],"kin'
    'd":"fixed","results":[{"id":"monitored_c'
    'urrent","label":"Monitored current","des'
    'cription":"One measurement while sourcin'
    'g voltage.","dtype":"float64","unit":"A"'
    ',"axes":[]}]},{"id":"measure_voltage","l'
    'abel":"Measure voltage","description":"M'
    "easure voltage while the source is opera"
    'ting in current mode.","preconditions":['
    '],"kind":"fixed","results":[{"id":"monit'
    'ored_voltage","label":"Monitored voltage'
    '","description":"One measurement while s'
    'ourcing current.","dtype":"float64","uni'
    't":"V","axes":[]}]}],"components":[]}'
)


def dc_monitor_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_DC_MONITOR_SPEC_JSON)


_NETWORK_SWEEP_SPEC_JSON = (
    '{"id":"scopecat.network_sweep/v1","label'
    '":"Network sweep","description":"Linear,'
    " single-trigger complex S-parameter swee"
    'p.","properties":[{"id":"start_frequency'
    '","label":"Start frequency","description'
    '":"First stimulus frequency in the linea'
    'r sweep.","access":"read_write","value_t'
    'ype":{"type":"quantity","dimension":null'
    ',"unit":"Hz","minimum":null,"maximum":nu'
    'll,"finite":true}},{"id":"stop_frequency'
    '","label":"Stop frequency","description"'
    ':"Last stimulus frequency in the linear '
    'sweep.","access":"read_write","value_typ'
    'e":{"type":"quantity","dimension":null,"'
    'unit":"Hz","minimum":null,"maximum":null'
    ',"finite":true}},{"id":"points","label":'
    '"Sweep points","description":"Number of '
    'equally spaced frequency points.","acces'
    's":"read_write","value_type":{"type":"in'
    't","minimum":2,"maximum":900719925474099'
    '1}},{"id":"if_bandwidth","label":"IF ban'
    'dwidth","description":"Receiver intermed'
    'iate-frequency bandwidth.","access":"rea'
    'd_write","value_type":{"type":"quantity"'
    ',"dimension":null,"unit":"Hz","minimum":'
    'null,"maximum":null,"finite":true}},{"id'
    '":"source_power","label":"Source power",'
    '"description":"Stimulus power for the se'
    'lected analyzer channel.","access":"read'
    '_write","value_type":{"type":"quantity",'
    '"dimension":null,"unit":"dBm","minimum":'
    'null,"maximum":null,"finite":true}},{"id'
    '":"s_parameter","label":"S-parameter","d'
    'escription":"Two-port S-parameter measur'
    'ed by the selected trace.","access":"rea'
    'd_write","value_type":{"type":"string","'
    'choices":["S11","S21","S12","S22"]}}],"s'
    'tate":null,"operations":[],"acquisitions'
    '":[{"id":"sweep","label":"Acquire sweep"'
    ',"description":"Trigger and read the con'
    'figured network sweep.","preconditions":'
    '[],"kind":"fixed","results":[{"id":"freq'
    'uency","label":"Frequency","description"'
    ':"Stimulus frequency values for the acqu'
    'ired trace.","dtype":"float64","unit":"H'
    'z","axes":[{"id":"frequency","label":"Fr'
    'equency","description":"Linear VNA stimu'
    'lus frequency.","kind":"frequency","size'
    '":{"interface_id":"scopecat.network_swee'
    'p/v1","component_path":[],"property_id":'
    '"points"},"unit":"Hz"}]},{"id":"s_parame'
    'ter","label":"Complex S-parameter","desc'
    'ription":"Complex response values for th'
    'e configured S-parameter.","dtype":"comp'
    'lex128","unit":"ratio","axes":[{"id":"fr'
    'equency","label":"Frequency","descriptio'
    'n":"Linear VNA stimulus frequency.","kin'
    'd":"frequency","size":{"interface_id":"s'
    'copecat.network_sweep/v1","component_pat'
    'h":[],"property_id":"points"},"unit":"Hz'
    '"}]}]}],"components":[]}'
)


def network_sweep_interface() -> InterfaceSpec:
    return InterfaceSpec.model_validate_json(_NETWORK_SWEEP_SPEC_JSON)


__all__ = [
    "dc_monitor_interface",
    "dc_source_interface",
    "network_sweep_interface",
    "rf_output_interface",
    "temperature_readout_interface",
]
