# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed member projections generated from instrument interfaces."""

from __future__ import annotations

from typing import Literal

from scopecat.authoring import PerEntity, Symbolic
from scopecat.kernel.quantity import Quantity
from scopecat.sdk.instruments.declarations import (
    MemberProjectionField,
    MemberProjectionLayout,
    instrument_member_projection,
    member_projection_field,
)

from scopecat_instruments.interface_declarations import (
    DCBiasInterface as DCBiasInterface,
)
from scopecat_instruments.interface_declarations import (
    DCMonitorInterface as DCMonitorInterface,
)
from scopecat_instruments.interface_declarations import (
    DCSourceInterface as DCSourceInterface,
)
from scopecat_instruments.interface_declarations import (
    NetworkSweepInterface as NetworkSweepInterface,
)
from scopecat_instruments.interface_declarations import (
    ReferenceClockInterface as ReferenceClockInterface,
)
from scopecat_instruments.interface_declarations import (
    ReferenceSource as ReferenceSource,
)
from scopecat_instruments.interface_declarations import (
    RFOutputInterface as RFOutputInterface,
)
from scopecat_instruments.interface_declarations import (
    SParameter as SParameter,
)
from scopecat_instruments.interface_declarations import (
    TemperatureReadoutInterface as TemperatureReadoutInterface,
)
from scopecat_instruments.members import (
    DC_BIAS_RAMP_DURATION,
    DC_BIAS_SETTLE_TOLERANCE,
    DC_BIAS_TARGET_VOLTAGE,
    DC_MONITOR_INTEGRATION_CYCLES,
    DC_MONITOR_MEASUREMENT_DELAY,
    DC_MONITOR_MEASUREMENT_ENABLED,
    DC_SOURCE_CURRENT_PROTECTION,
    DC_SOURCE_OUTPUT_ENABLED,
    DC_SOURCE_VOLTAGE_PROTECTION,
    NETWORK_SWEEP_IF_BANDWIDTH,
    NETWORK_SWEEP_POINTS,
    NETWORK_SWEEP_S_PARAMETER,
    NETWORK_SWEEP_SOURCE_POWER,
    NETWORK_SWEEP_START_FREQUENCY,
    NETWORK_SWEEP_STOP_FREQUENCY,
    REFERENCE_CLOCK_REFERENCE_SOURCE,
    RF_OUTPUT_ENABLED,
    RF_OUTPUT_FREQUENCY,
    RF_OUTPUT_POWER,
)

_RF_OUTPUT_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("frequency", RF_OUTPUT_FREQUENCY),
        MemberProjectionField("power", RF_OUTPUT_POWER),
        MemberProjectionField("output_enabled", RF_OUTPUT_ENABLED),
    ),
)


@instrument_member_projection(_RF_OUTPUT_MEMBER_LAYOUT)
class RFOutputPatch:
    frequency: Quantity = member_projection_field()
    power: Quantity = member_projection_field()
    output_enabled: bool = member_projection_field()


@instrument_member_projection(_RF_OUTPUT_MEMBER_LAYOUT)
class RFOutputTarget:
    frequency: Symbolic[Quantity] = member_projection_field()
    power: Symbolic[Quantity] = member_projection_field()
    output_enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_RF_OUTPUT_MEMBER_LAYOUT)
class RFOutputGroupTarget:
    frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    power: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    output_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )


_REFERENCE_CLOCK_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("reference_source", REFERENCE_CLOCK_REFERENCE_SOURCE),
    ),
)


@instrument_member_projection(_REFERENCE_CLOCK_MEMBER_LAYOUT)
class ReferenceClockPatch:
    reference_source: Literal["internal", "external"] = member_projection_field()


@instrument_member_projection(_REFERENCE_CLOCK_MEMBER_LAYOUT)
class ReferenceClockTarget:
    reference_source: Symbolic[Literal["internal", "external"]] = (
        member_projection_field()
    )


@instrument_member_projection(_REFERENCE_CLOCK_MEMBER_LAYOUT)
class ReferenceClockGroupTarget:
    reference_source: (
        Symbolic[Literal["internal", "external"]]
        | PerEntity[Symbolic[Literal["internal", "external"]]]
    ) = member_projection_field()


_DC_BIAS_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("target_voltage", DC_BIAS_TARGET_VOLTAGE),
        MemberProjectionField("ramp_duration", DC_BIAS_RAMP_DURATION),
        MemberProjectionField("settle_tolerance", DC_BIAS_SETTLE_TOLERANCE),
    ),
)


@instrument_member_projection(_DC_BIAS_MEMBER_LAYOUT)
class DCBiasPatch:
    target_voltage: Quantity = member_projection_field()
    ramp_duration: Quantity = member_projection_field()
    settle_tolerance: Quantity = member_projection_field()


@instrument_member_projection(_DC_BIAS_MEMBER_LAYOUT)
class DCBiasTarget:
    target_voltage: Symbolic[Quantity] = member_projection_field()
    ramp_duration: Symbolic[Quantity] = member_projection_field()
    settle_tolerance: Symbolic[Quantity] = member_projection_field()


@instrument_member_projection(_DC_BIAS_MEMBER_LAYOUT)
class DCBiasGroupTarget:
    target_voltage: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    ramp_duration: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    settle_tolerance: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )


_DC_SOURCE_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("voltage_protection", DC_SOURCE_VOLTAGE_PROTECTION),
        MemberProjectionField("current_protection", DC_SOURCE_CURRENT_PROTECTION),
        MemberProjectionField("output_enabled", DC_SOURCE_OUTPUT_ENABLED),
    ),
)


@instrument_member_projection(_DC_SOURCE_MEMBER_LAYOUT)
class DCSourcePatch:
    voltage_protection: Quantity = member_projection_field()
    current_protection: Quantity = member_projection_field()
    output_enabled: bool = member_projection_field()


@instrument_member_projection(_DC_SOURCE_MEMBER_LAYOUT)
class DCSourceTarget:
    voltage_protection: Symbolic[Quantity] = member_projection_field()
    current_protection: Symbolic[Quantity] = member_projection_field()
    output_enabled: Symbolic[bool] = member_projection_field()


@instrument_member_projection(_DC_SOURCE_MEMBER_LAYOUT)
class DCSourceGroupTarget:
    voltage_protection: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    current_protection: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    output_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )


_DC_MONITOR_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("measurement_enabled", DC_MONITOR_MEASUREMENT_ENABLED),
        MemberProjectionField("integration_cycles", DC_MONITOR_INTEGRATION_CYCLES),
        MemberProjectionField("measurement_delay", DC_MONITOR_MEASUREMENT_DELAY),
    ),
)


@instrument_member_projection(_DC_MONITOR_MEMBER_LAYOUT)
class DCMonitorPatch:
    measurement_enabled: bool = member_projection_field()
    integration_cycles: int = member_projection_field()
    measurement_delay: Quantity = member_projection_field()


@instrument_member_projection(_DC_MONITOR_MEMBER_LAYOUT)
class DCMonitorTarget:
    measurement_enabled: Symbolic[bool] = member_projection_field()
    integration_cycles: Symbolic[int] = member_projection_field()
    measurement_delay: Symbolic[Quantity] = member_projection_field()


@instrument_member_projection(_DC_MONITOR_MEMBER_LAYOUT)
class DCMonitorGroupTarget:
    measurement_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )
    integration_cycles: Symbolic[int] | PerEntity[Symbolic[int]] = (
        member_projection_field()
    )
    measurement_delay: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )


_NETWORK_SWEEP_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("start_frequency", NETWORK_SWEEP_START_FREQUENCY),
        MemberProjectionField("stop_frequency", NETWORK_SWEEP_STOP_FREQUENCY),
        MemberProjectionField("points", NETWORK_SWEEP_POINTS),
        MemberProjectionField("if_bandwidth", NETWORK_SWEEP_IF_BANDWIDTH),
        MemberProjectionField("source_power", NETWORK_SWEEP_SOURCE_POWER),
        MemberProjectionField("s_parameter", NETWORK_SWEEP_S_PARAMETER),
    ),
)


@instrument_member_projection(_NETWORK_SWEEP_MEMBER_LAYOUT)
class NetworkSweepPatch:
    start_frequency: Quantity = member_projection_field()
    stop_frequency: Quantity = member_projection_field()
    points: int = member_projection_field()
    if_bandwidth: Quantity = member_projection_field()
    source_power: Quantity = member_projection_field()
    s_parameter: Literal["S11", "S21", "S12", "S22"] = member_projection_field()


@instrument_member_projection(_NETWORK_SWEEP_MEMBER_LAYOUT)
class NetworkSweepTarget:
    start_frequency: Symbolic[Quantity] = member_projection_field()
    stop_frequency: Symbolic[Quantity] = member_projection_field()
    points: Symbolic[int] = member_projection_field()
    if_bandwidth: Symbolic[Quantity] = member_projection_field()
    source_power: Symbolic[Quantity] = member_projection_field()
    s_parameter: Symbolic[Literal["S11", "S21", "S12", "S22"]] = (
        member_projection_field()
    )


@instrument_member_projection(_NETWORK_SWEEP_MEMBER_LAYOUT)
class NetworkSweepGroupTarget:
    start_frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    stop_frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    points: Symbolic[int] | PerEntity[Symbolic[int]] = member_projection_field()
    if_bandwidth: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    source_power: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    s_parameter: (
        Symbolic[Literal["S11", "S21", "S12", "S22"]]
        | PerEntity[Symbolic[Literal["S11", "S21", "S12", "S22"]]]
    ) = member_projection_field()


_RF_SOURCE_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("frequency", RF_OUTPUT_FREQUENCY),
        MemberProjectionField("power", RF_OUTPUT_POWER),
        MemberProjectionField("output_enabled", RF_OUTPUT_ENABLED),
        MemberProjectionField("reference_source", REFERENCE_CLOCK_REFERENCE_SOURCE),
    ),
)


@instrument_member_projection(_RF_SOURCE_MEMBER_LAYOUT)
class RFSourcePatch:
    frequency: Quantity = member_projection_field()
    power: Quantity = member_projection_field()
    output_enabled: bool = member_projection_field()
    reference_source: Literal["internal", "external"] = member_projection_field()


@instrument_member_projection(_RF_SOURCE_MEMBER_LAYOUT)
class RFSourceTarget:
    frequency: Symbolic[Quantity] = member_projection_field()
    power: Symbolic[Quantity] = member_projection_field()
    output_enabled: Symbolic[bool] = member_projection_field()
    reference_source: Symbolic[Literal["internal", "external"]] = (
        member_projection_field()
    )


@instrument_member_projection(_RF_SOURCE_MEMBER_LAYOUT)
class RFSourceGroupTarget:
    frequency: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    power: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    output_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )
    reference_source: (
        Symbolic[Literal["internal", "external"]]
        | PerEntity[Symbolic[Literal["internal", "external"]]]
    ) = member_projection_field()


_DC_SOURCE_MONITOR_MEMBER_LAYOUT = MemberProjectionLayout(
    fields=(
        MemberProjectionField("voltage_protection", DC_SOURCE_VOLTAGE_PROTECTION),
        MemberProjectionField("current_protection", DC_SOURCE_CURRENT_PROTECTION),
        MemberProjectionField("output_enabled", DC_SOURCE_OUTPUT_ENABLED),
        MemberProjectionField("measurement_enabled", DC_MONITOR_MEASUREMENT_ENABLED),
        MemberProjectionField("integration_cycles", DC_MONITOR_INTEGRATION_CYCLES),
        MemberProjectionField("measurement_delay", DC_MONITOR_MEASUREMENT_DELAY),
    ),
)


@instrument_member_projection(_DC_SOURCE_MONITOR_MEMBER_LAYOUT)
class DCSourceMonitorPatch:
    voltage_protection: Quantity = member_projection_field()
    current_protection: Quantity = member_projection_field()
    output_enabled: bool = member_projection_field()
    measurement_enabled: bool = member_projection_field()
    integration_cycles: int = member_projection_field()
    measurement_delay: Quantity = member_projection_field()


@instrument_member_projection(_DC_SOURCE_MONITOR_MEMBER_LAYOUT)
class DCSourceMonitorTarget:
    voltage_protection: Symbolic[Quantity] = member_projection_field()
    current_protection: Symbolic[Quantity] = member_projection_field()
    output_enabled: Symbolic[bool] = member_projection_field()
    measurement_enabled: Symbolic[bool] = member_projection_field()
    integration_cycles: Symbolic[int] = member_projection_field()
    measurement_delay: Symbolic[Quantity] = member_projection_field()


@instrument_member_projection(_DC_SOURCE_MONITOR_MEMBER_LAYOUT)
class DCSourceMonitorGroupTarget:
    voltage_protection: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    current_protection: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )
    output_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )
    measurement_enabled: Symbolic[bool] | PerEntity[Symbolic[bool]] = (
        member_projection_field()
    )
    integration_cycles: Symbolic[int] | PerEntity[Symbolic[int]] = (
        member_projection_field()
    )
    measurement_delay: Symbolic[Quantity] | PerEntity[Symbolic[Quantity]] = (
        member_projection_field()
    )


__all__ = [
    "DCBiasGroupTarget",
    "DCBiasInterface",
    "DCBiasPatch",
    "DCBiasTarget",
    "DCMonitorGroupTarget",
    "DCMonitorInterface",
    "DCMonitorPatch",
    "DCMonitorTarget",
    "DCSourceGroupTarget",
    "DCSourceInterface",
    "DCSourceMonitorGroupTarget",
    "DCSourceMonitorPatch",
    "DCSourceMonitorTarget",
    "DCSourcePatch",
    "DCSourceTarget",
    "NetworkSweepGroupTarget",
    "NetworkSweepInterface",
    "NetworkSweepPatch",
    "NetworkSweepTarget",
    "RFOutputGroupTarget",
    "RFOutputInterface",
    "RFOutputPatch",
    "RFOutputTarget",
    "RFSourceGroupTarget",
    "RFSourcePatch",
    "RFSourceTarget",
    "ReferenceClockGroupTarget",
    "ReferenceClockInterface",
    "ReferenceClockPatch",
    "ReferenceClockTarget",
    "ReferenceSource",
    "SParameter",
    "TemperatureReadoutInterface",
]
