# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed state projections generated from instrument interfaces."""

from __future__ import annotations

from typing import Literal

from scopecat.authoring import PerEntity, ValueRef
from scopecat.kernel.quantity import Quantity
from scopecat.sdk.instruments.declarations import (
    compile_interface,
    declared_interface_layout,
    instrument_state_projection,
    state_projection_field,
)

from scopecat_instruments.interface_declarations import (
    DCMonitorInterface,
    DCSourceInterface,
    NetworkSweepInterface,
    RFOutputInterface,
)
from scopecat_instruments.interface_declarations import (
    ReferenceSource as ReferenceSource,
)
from scopecat_instruments.interface_declarations import (
    SParameter as SParameter,
)
from scopecat_instruments.interface_declarations import (
    TemperatureReadoutObservation as TemperatureReadoutObservation,
)

_RF_OUTPUT_STATE_LAYOUTS = declared_interface_layout(
    compile_interface(RFOutputInterface)
).states


@instrument_state_projection(_RF_OUTPUT_STATE_LAYOUTS[0])
class RFOutputPatch:
    frequency: Quantity = state_projection_field()
    power: Quantity = state_projection_field()
    output_enabled: bool = state_projection_field()
    reference_source: Literal["internal", "external"] = state_projection_field()


@instrument_state_projection(_RF_OUTPUT_STATE_LAYOUTS[0])
class RFOutputTarget:
    frequency: Quantity | ValueRef = state_projection_field()
    power: Quantity | ValueRef = state_projection_field()
    output_enabled: bool | ValueRef = state_projection_field()
    reference_source: Literal["internal", "external"] | ValueRef = (
        state_projection_field()
    )


@instrument_state_projection(_RF_OUTPUT_STATE_LAYOUTS[0])
class RFOutputGroupTarget:
    frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )
    reference_source: (
        Literal["internal", "external"]
        | ValueRef
        | PerEntity[Literal["internal", "external"] | ValueRef]
    ) = state_projection_field()


_DC_SOURCE_STATE_LAYOUTS = declared_interface_layout(
    compile_interface(DCSourceInterface)
).states


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[0])
class DCSourcePatch:
    voltage_protection: Quantity = state_projection_field()
    current_protection: Quantity = state_projection_field()
    output_enabled: bool = state_projection_field()


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[0])
class DCSourceTarget:
    voltage_protection: Quantity | ValueRef = state_projection_field()
    current_protection: Quantity | ValueRef = state_projection_field()
    output_enabled: bool | ValueRef = state_projection_field()


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[0])
class DCSourceGroupTarget:
    voltage_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    current_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[1])
class DCSourceVoltagePatch:
    voltage_protection: Quantity = state_projection_field()
    current_protection: Quantity = state_projection_field()
    output_enabled: bool = state_projection_field()
    range: Quantity
    level: Quantity


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[1])
class DCSourceVoltageTarget:
    voltage_protection: Quantity | ValueRef = state_projection_field()
    current_protection: Quantity | ValueRef = state_projection_field()
    output_enabled: bool | ValueRef = state_projection_field()
    range: Quantity | ValueRef
    level: Quantity | ValueRef


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[1])
class DCSourceVoltageGroupTarget:
    voltage_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    current_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )
    range: Quantity | ValueRef | PerEntity[Quantity | ValueRef]
    level: Quantity | ValueRef | PerEntity[Quantity | ValueRef]


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[2])
class DCSourceCurrentPatch:
    voltage_protection: Quantity = state_projection_field()
    current_protection: Quantity = state_projection_field()
    output_enabled: bool = state_projection_field()
    range: Quantity
    level: Quantity


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[2])
class DCSourceCurrentTarget:
    voltage_protection: Quantity | ValueRef = state_projection_field()
    current_protection: Quantity | ValueRef = state_projection_field()
    output_enabled: bool | ValueRef = state_projection_field()
    range: Quantity | ValueRef
    level: Quantity | ValueRef


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUTS[2])
class DCSourceCurrentGroupTarget:
    voltage_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    current_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )
    range: Quantity | ValueRef | PerEntity[Quantity | ValueRef]
    level: Quantity | ValueRef | PerEntity[Quantity | ValueRef]


_DC_MONITOR_STATE_LAYOUTS = declared_interface_layout(
    compile_interface(DCMonitorInterface)
).states


@instrument_state_projection(_DC_MONITOR_STATE_LAYOUTS[0])
class DCMonitorPatch:
    measurement_enabled: bool = state_projection_field()
    integration_cycles: int = state_projection_field()
    measurement_delay: Quantity = state_projection_field()


@instrument_state_projection(_DC_MONITOR_STATE_LAYOUTS[0])
class DCMonitorTarget:
    measurement_enabled: bool | ValueRef = state_projection_field()
    integration_cycles: int | ValueRef = state_projection_field()
    measurement_delay: Quantity | ValueRef = state_projection_field()


@instrument_state_projection(_DC_MONITOR_STATE_LAYOUTS[0])
class DCMonitorGroupTarget:
    measurement_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )
    integration_cycles: int | ValueRef | PerEntity[int | ValueRef] = (
        state_projection_field()
    )
    measurement_delay: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )


_NETWORK_SWEEP_STATE_LAYOUTS = declared_interface_layout(
    compile_interface(NetworkSweepInterface)
).states


@instrument_state_projection(_NETWORK_SWEEP_STATE_LAYOUTS[0])
class NetworkSweepPatch:
    start_frequency: Quantity = state_projection_field()
    stop_frequency: Quantity = state_projection_field()
    points: int = state_projection_field()
    if_bandwidth: Quantity = state_projection_field()
    source_power: Quantity = state_projection_field()
    s_parameter: Literal["S11", "S21", "S12", "S22"] = state_projection_field()


@instrument_state_projection(_NETWORK_SWEEP_STATE_LAYOUTS[0])
class NetworkSweepTarget:
    start_frequency: Quantity | ValueRef = state_projection_field()
    stop_frequency: Quantity | ValueRef = state_projection_field()
    points: int | ValueRef = state_projection_field()
    if_bandwidth: Quantity | ValueRef = state_projection_field()
    source_power: Quantity | ValueRef = state_projection_field()
    s_parameter: Literal["S11", "S21", "S12", "S22"] | ValueRef = (
        state_projection_field()
    )


@instrument_state_projection(_NETWORK_SWEEP_STATE_LAYOUTS[0])
class NetworkSweepGroupTarget:
    start_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    stop_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    points: int | ValueRef | PerEntity[int | ValueRef] = state_projection_field()
    if_bandwidth: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    source_power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    s_parameter: (
        Literal["S11", "S21", "S12", "S22"]
        | ValueRef
        | PerEntity[Literal["S11", "S21", "S12", "S22"] | ValueRef]
    ) = state_projection_field()


__all__ = [
    "DCMonitorGroupTarget",
    "DCMonitorPatch",
    "DCMonitorTarget",
    "DCSourceCurrentGroupTarget",
    "DCSourceCurrentPatch",
    "DCSourceCurrentTarget",
    "DCSourceGroupTarget",
    "DCSourcePatch",
    "DCSourceTarget",
    "DCSourceVoltageGroupTarget",
    "DCSourceVoltagePatch",
    "DCSourceVoltageTarget",
    "NetworkSweepGroupTarget",
    "NetworkSweepPatch",
    "NetworkSweepTarget",
    "RFOutputGroupTarget",
    "RFOutputPatch",
    "RFOutputTarget",
    "ReferenceSource",
    "SParameter",
    "TemperatureReadoutObservation",
]
