# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed state projections generated from instrument interfaces."""

from __future__ import annotations

from typing import Literal

from scopecat.authoring import PerEntity, ValueRef
from scopecat.kernel.quantity import Quantity
from scopecat.sdk.instruments.declarations import (
    StateProjectionField,
    StateProjectionLayout,
    instrument_state_projection,
    state_projection_field,
)

from scopecat_instruments.interface_declarations import (
    DCMonitorState as DCMonitorState,
)
from scopecat_instruments.interface_declarations import (
    DCSourceState as DCSourceState,
)
from scopecat_instruments.interface_declarations import (
    NetworkSweepState as NetworkSweepState,
)
from scopecat_instruments.interface_declarations import (
    ReferenceSource as ReferenceSource,
)
from scopecat_instruments.interface_declarations import (
    RFOutputState as RFOutputState,
)
from scopecat_instruments.interface_declarations import (
    SParameter as SParameter,
)
from scopecat_instruments.interface_declarations import (
    TemperatureReadoutState as TemperatureReadoutState,
)
from scopecat_instruments.members import (
    DC_MONITOR_INTEGRATION_CYCLES,
    DC_MONITOR_MEASUREMENT_DELAY,
    DC_MONITOR_MEASUREMENT_ENABLED,
    DC_SOURCE_CURRENT_PROTECTION,
    DC_SOURCE_OUTPUT_ENABLED,
    DC_SOURCE_VOLTAGE_PROTECTION,
    NETWORK_SWEEP_IF_BANDWIDTH,
    NETWORK_SWEEP_POINTS,
    NETWORK_SWEEP_S_PARAMETER,
    NETWORK_SWEEP_SOURCE_POWER,
    NETWORK_SWEEP_START_FREQUENCY,
    NETWORK_SWEEP_STOP_FREQUENCY,
    RF_OUTPUT_ENABLED,
    RF_OUTPUT_FREQUENCY,
    RF_OUTPUT_POWER,
    RF_OUTPUT_REFERENCE_SOURCE,
)

_RF_OUTPUT_STATE_LAYOUT = StateProjectionLayout(
    fields=(
        StateProjectionField("frequency", RF_OUTPUT_FREQUENCY),
        StateProjectionField("power", RF_OUTPUT_POWER),
        StateProjectionField("output_enabled", RF_OUTPUT_ENABLED),
        StateProjectionField("reference_source", RF_OUTPUT_REFERENCE_SOURCE),
    ),
)


@instrument_state_projection(_RF_OUTPUT_STATE_LAYOUT)
class RFOutputPatch:
    frequency: Quantity = state_projection_field()
    power: Quantity = state_projection_field()
    output_enabled: bool = state_projection_field()
    reference_source: Literal["internal", "external"] = state_projection_field()


@instrument_state_projection(_RF_OUTPUT_STATE_LAYOUT)
class RFOutputTarget:
    frequency: Quantity | ValueRef = state_projection_field()
    power: Quantity | ValueRef = state_projection_field()
    output_enabled: bool | ValueRef = state_projection_field()
    reference_source: Literal["internal", "external"] | ValueRef = (
        state_projection_field()
    )


@instrument_state_projection(_RF_OUTPUT_STATE_LAYOUT)
class RFOutputGroupTarget:
    frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )
    reference_source: (
        Literal["internal", "external"]
        | ValueRef
        | PerEntity[Literal["internal", "external"] | ValueRef]
    ) = state_projection_field()


_DC_SOURCE_STATE_LAYOUT = StateProjectionLayout(
    fields=(
        StateProjectionField("voltage_protection", DC_SOURCE_VOLTAGE_PROTECTION),
        StateProjectionField("current_protection", DC_SOURCE_CURRENT_PROTECTION),
        StateProjectionField("output_enabled", DC_SOURCE_OUTPUT_ENABLED),
    ),
)


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUT)
class DCSourcePatch:
    voltage_protection: Quantity = state_projection_field()
    current_protection: Quantity = state_projection_field()
    output_enabled: bool = state_projection_field()


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUT)
class DCSourceTarget:
    voltage_protection: Quantity | ValueRef = state_projection_field()
    current_protection: Quantity | ValueRef = state_projection_field()
    output_enabled: bool | ValueRef = state_projection_field()


@instrument_state_projection(_DC_SOURCE_STATE_LAYOUT)
class DCSourceGroupTarget:
    voltage_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    current_protection: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    output_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )


_DC_MONITOR_STATE_LAYOUT = StateProjectionLayout(
    fields=(
        StateProjectionField("measurement_enabled", DC_MONITOR_MEASUREMENT_ENABLED),
        StateProjectionField("integration_cycles", DC_MONITOR_INTEGRATION_CYCLES),
        StateProjectionField("measurement_delay", DC_MONITOR_MEASUREMENT_DELAY),
    ),
)


@instrument_state_projection(_DC_MONITOR_STATE_LAYOUT)
class DCMonitorPatch:
    measurement_enabled: bool = state_projection_field()
    integration_cycles: int = state_projection_field()
    measurement_delay: Quantity = state_projection_field()


@instrument_state_projection(_DC_MONITOR_STATE_LAYOUT)
class DCMonitorTarget:
    measurement_enabled: bool | ValueRef = state_projection_field()
    integration_cycles: int | ValueRef = state_projection_field()
    measurement_delay: Quantity | ValueRef = state_projection_field()


@instrument_state_projection(_DC_MONITOR_STATE_LAYOUT)
class DCMonitorGroupTarget:
    measurement_enabled: bool | ValueRef | PerEntity[bool | ValueRef] = (
        state_projection_field()
    )
    integration_cycles: int | ValueRef | PerEntity[int | ValueRef] = (
        state_projection_field()
    )
    measurement_delay: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )


_NETWORK_SWEEP_STATE_LAYOUT = StateProjectionLayout(
    fields=(
        StateProjectionField("start_frequency", NETWORK_SWEEP_START_FREQUENCY),
        StateProjectionField("stop_frequency", NETWORK_SWEEP_STOP_FREQUENCY),
        StateProjectionField("points", NETWORK_SWEEP_POINTS),
        StateProjectionField("if_bandwidth", NETWORK_SWEEP_IF_BANDWIDTH),
        StateProjectionField("source_power", NETWORK_SWEEP_SOURCE_POWER),
        StateProjectionField("s_parameter", NETWORK_SWEEP_S_PARAMETER),
    ),
)


@instrument_state_projection(_NETWORK_SWEEP_STATE_LAYOUT)
class NetworkSweepPatch:
    start_frequency: Quantity = state_projection_field()
    stop_frequency: Quantity = state_projection_field()
    points: int = state_projection_field()
    if_bandwidth: Quantity = state_projection_field()
    source_power: Quantity = state_projection_field()
    s_parameter: Literal["S11", "S21", "S12", "S22"] = state_projection_field()


@instrument_state_projection(_NETWORK_SWEEP_STATE_LAYOUT)
class NetworkSweepTarget:
    start_frequency: Quantity | ValueRef = state_projection_field()
    stop_frequency: Quantity | ValueRef = state_projection_field()
    points: int | ValueRef = state_projection_field()
    if_bandwidth: Quantity | ValueRef = state_projection_field()
    source_power: Quantity | ValueRef = state_projection_field()
    s_parameter: Literal["S11", "S21", "S12", "S22"] | ValueRef = (
        state_projection_field()
    )


@instrument_state_projection(_NETWORK_SWEEP_STATE_LAYOUT)
class NetworkSweepGroupTarget:
    start_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    stop_frequency: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    points: int | ValueRef | PerEntity[int | ValueRef] = state_projection_field()
    if_bandwidth: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    source_power: Quantity | ValueRef | PerEntity[Quantity | ValueRef] = (
        state_projection_field()
    )
    s_parameter: (
        Literal["S11", "S21", "S12", "S22"]
        | ValueRef
        | PerEntity[Literal["S11", "S21", "S12", "S22"] | ValueRef]
    ) = state_projection_field()


__all__ = [
    "DCMonitorGroupTarget",
    "DCMonitorPatch",
    "DCMonitorState",
    "DCMonitorTarget",
    "DCSourceGroupTarget",
    "DCSourcePatch",
    "DCSourceState",
    "DCSourceTarget",
    "NetworkSweepGroupTarget",
    "NetworkSweepPatch",
    "NetworkSweepState",
    "NetworkSweepTarget",
    "RFOutputGroupTarget",
    "RFOutputPatch",
    "RFOutputState",
    "RFOutputTarget",
    "ReferenceSource",
    "SParameter",
    "TemperatureReadoutState",
]
