# This file was auto-generated by scripts/generate_instrument_clients.py.
# Do not make direct changes to the file.
"""Typed states generated from the declared instrument interfaces."""

from __future__ import annotations

from scopecat_instruments.interface_declarations import (
    DCMonitorState as DCMonitorState,
)
from scopecat_instruments.interface_declarations import (
    DCSourceCurrent as DCSourceCurrent,
)
from scopecat_instruments.interface_declarations import (
    DCSourceState as DCSourceState,
)
from scopecat_instruments.interface_declarations import (
    DCSourceVoltage as DCSourceVoltage,
)
from scopecat_instruments.interface_declarations import (
    Desired as Desired,
)
from scopecat_instruments.interface_declarations import (
    NetworkSweepState as NetworkSweepState,
)
from scopecat_instruments.interface_declarations import (
    ReferenceSource as ReferenceSource,
)
from scopecat_instruments.interface_declarations import (
    RFOutputState as RFOutputState,
)
from scopecat_instruments.interface_declarations import (
    SParameter as SParameter,
)
from scopecat_instruments.interface_declarations import (
    TemperatureReadoutObservation as TemperatureReadoutObservation,
)

__all__ = [
    "DCMonitorState",
    "DCSourceCurrent",
    "DCSourceState",
    "DCSourceVoltage",
    "Desired",
    "NetworkSweepState",
    "RFOutputState",
    "ReferenceSource",
    "SParameter",
    "TemperatureReadoutObservation",
]
