"""Notebook-first public workflow facade.

The facade is intentionally lazy: importing an internal Scopecat module does
not construct the authoring, compiler, session, and storage dependency graph.
"""

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, cast

if TYPE_CHECKING:
    from scopecat.api.workspace import (
        Analysis,
        AnalysisContext,
        AnalysisInput,
        AnalysisOutput,
        AnalysisStep,
        CandidateConfig,
        Data,
        EarlyStopDecision,
        Experiment,
        PreparedExperiment,
        Quantity,
        RunHandle,
        SavedAnalysis,
        Workspace,
        decide_online_convergence,
    )
    from scopecat.authoring import (
        BoolType,
        Compute,
        ComputeInput,
        DomainExecution,
        DomainInputPort,
        DomainProgramDef,
        DomainResourcePort,
        DomainResultPort,
        EntityType,
        ExperimentInvocation,
        ExperimentModule,
        ExperimentTemplate,
        FloatType,
        InputDescription,
        IntType,
        MeasurementTransform,
        MetadataValue,
        ModuleBuilder,
        ModuleInput,
        ModuleInvocation,
        ModuleOutputs,
        ParameterKeyInput,
        PayloadType,
        ProductAxis,
        ProductOutputs,
        ProductRef,
        QuantityType,
        RecordField,
        RecordSelection,
        RecordType,
        ResolvedRoute,
        RouteRef,
        RouteType,
        RuntimeInput,
        ScalarInput,
        ScalarType,
        SeriesType,
        StringType,
        TableColumn,
        TableRow,
        TableType,
        TemplateBuilder,
        ValueRef,
        ValueType,
        compute,
        domain_execution,
        domain_program,
        entity_axis,
        measurement_transform,
        module,
        parameter,
        parameter_lookup,
        point,
        product_axis,
        record_alias,
        record_product,
        route,
        shot_axis,
    )
    from scopecat.authoring import (
        input as input,  # noqa: A004
    )
    from scopecat.authoring.scans import (
        ParameterRow,
        Scan,
        axis,
        cartesian,
        param_axis,
        param_row,
    )
    from scopecat.authoring.scans import zip as zip  # noqa: A004
    from scopecat.composition.local import open_local_workspace as open  # noqa: A004
    from scopecat.config.parameters import (
        delete_parameter_rows,
        insert_parameter_rows,
        replace_scalar_parameter,
        replace_series_parameter,
        replace_table_parameter,
        update_parameter_rows,
    )
    from scopecat.execution.observation import (
        RunFinishedEvent,
        RunStartedEvent,
        RuntimeEvent,
        RuntimeEventSink,
        RuntimePayloadObservation,
        RuntimePayloadObserver,
        RuntimeProgress,
        RuntimeTransitionEvent,
    )
    from scopecat.execution.program import (
        RunDomainJob,
        RunHostBinding,
        RunProgram,
    )
    from scopecat.kernel.problems import (
        ExternalLocation,
        ModelLocation,
        Problem,
        ProblemCategory,
        ProblemImpact,
        ProblemLocation,
        ProblemPhase,
        RuntimeLocation,
        StorageLocation,
        blocking_problem,
        model_location,
    )
    from scopecat.measurements.results import MeasurementDatasetSchema
    from scopecat.measurements.semantics import MeasurementTransformSemanticContract
    from scopecat.planning.check_results import ExperimentCheckResult
    from scopecat.planning.preview_models import ExperimentPreview
    from scopecat.planning.system import ExperimentSystem
    from scopecat.records.entity import EntityRef, entity_ref

    Run = RunHandle


_EXPORTS: dict[str, tuple[str, str]] = {
    "BoolType": ("scopecat.authoring", "BoolType"),
    "Compute": ("scopecat.authoring", "Compute"),
    "ComputeInput": ("scopecat.authoring", "ComputeInput"),
    "DomainExecution": ("scopecat.authoring", "DomainExecution"),
    "DomainInputPort": ("scopecat.authoring", "DomainInputPort"),
    "DomainProgramDef": ("scopecat.authoring", "DomainProgramDef"),
    "DomainResourcePort": ("scopecat.authoring", "DomainResourcePort"),
    "DomainResultPort": ("scopecat.authoring", "DomainResultPort"),
    "EntityType": ("scopecat.authoring", "EntityType"),
    "ExperimentInvocation": ("scopecat.authoring", "ExperimentInvocation"),
    "ExperimentModule": ("scopecat.authoring", "ExperimentModule"),
    "ExperimentTemplate": ("scopecat.authoring", "ExperimentTemplate"),
    "FloatType": ("scopecat.authoring", "FloatType"),
    "InputDescription": ("scopecat.authoring", "InputDescription"),
    "IntType": ("scopecat.authoring", "IntType"),
    "MeasurementTransform": ("scopecat.authoring", "MeasurementTransform"),
    "MetadataValue": ("scopecat.authoring", "MetadataValue"),
    "ModuleBuilder": ("scopecat.authoring", "ModuleBuilder"),
    "ModuleInput": ("scopecat.authoring", "ModuleInput"),
    "ModuleInvocation": ("scopecat.authoring", "ModuleInvocation"),
    "ModuleOutputs": ("scopecat.authoring", "ModuleOutputs"),
    "ParameterKeyInput": ("scopecat.authoring", "ParameterKeyInput"),
    "PayloadType": ("scopecat.authoring", "PayloadType"),
    "ProductOutputs": ("scopecat.authoring", "ProductOutputs"),
    "ProductRef": ("scopecat.authoring", "ProductRef"),
    "QuantityType": ("scopecat.authoring", "QuantityType"),
    "ProductAxis": ("scopecat.authoring", "ProductAxis"),
    "RecordField": ("scopecat.authoring", "RecordField"),
    "RecordSelection": ("scopecat.authoring", "RecordSelection"),
    "RecordType": ("scopecat.authoring", "RecordType"),
    "ResolvedRoute": ("scopecat.authoring", "ResolvedRoute"),
    "RouteRef": ("scopecat.authoring", "RouteRef"),
    "RouteType": ("scopecat.authoring", "RouteType"),
    "RuntimeInput": ("scopecat.authoring", "RuntimeInput"),
    "ScalarInput": ("scopecat.authoring", "ScalarInput"),
    "ScalarType": ("scopecat.authoring", "ScalarType"),
    "SeriesType": ("scopecat.authoring", "SeriesType"),
    "StringType": ("scopecat.authoring", "StringType"),
    "TableColumn": ("scopecat.authoring", "TableColumn"),
    "TableRow": ("scopecat.authoring", "TableRow"),
    "TableType": ("scopecat.authoring", "TableType"),
    "TemplateBuilder": ("scopecat.authoring", "TemplateBuilder"),
    "ValueRef": ("scopecat.authoring", "ValueRef"),
    "ValueType": ("scopecat.authoring", "ValueType"),
    "compute": ("scopecat.authoring", "compute"),
    "domain_execution": ("scopecat.authoring", "domain_execution"),
    "domain_program": ("scopecat.authoring", "domain_program"),
    "entity_axis": ("scopecat.authoring", "entity_axis"),
    "input": ("scopecat.authoring", "input"),
    "measurement_transform": ("scopecat.authoring", "measurement_transform"),
    "module": ("scopecat.authoring", "module"),
    "parameter": ("scopecat.authoring", "parameter"),
    "parameter_lookup": ("scopecat.authoring", "parameter_lookup"),
    "point": ("scopecat.authoring", "point"),
    "record_alias": ("scopecat.authoring", "record_alias"),
    "product_axis": ("scopecat.authoring", "product_axis"),
    "record_product": ("scopecat.authoring", "record_product"),
    "route": ("scopecat.authoring", "route"),
    "shot_axis": ("scopecat.authoring", "shot_axis"),
    "ParameterRow": ("scopecat.authoring.scans", "ParameterRow"),
    "Scan": ("scopecat.authoring.scans", "Scan"),
    "axis": ("scopecat.authoring.scans", "axis"),
    "cartesian": ("scopecat.authoring.scans", "cartesian"),
    "param_axis": ("scopecat.authoring.scans", "param_axis"),
    "param_row": ("scopecat.authoring.scans", "param_row"),
    "zip": ("scopecat.authoring.scans", "zip"),
    "ExperimentCheckResult": (
        "scopecat.planning.check_results",
        "ExperimentCheckResult",
    ),
    "ExperimentSystem": ("scopecat.planning.system", "ExperimentSystem"),
    "RunDomainJob": ("scopecat.execution.program", "RunDomainJob"),
    "RunHostBinding": ("scopecat.execution.program", "RunHostBinding"),
    "RunProgram": ("scopecat.execution.program", "RunProgram"),
    "EntityRef": ("scopecat.records.entity", "EntityRef"),
    "entity_ref": ("scopecat.records.entity", "entity_ref"),
    "delete_parameter_rows": ("scopecat.config.parameters", "delete_parameter_rows"),
    "insert_parameter_rows": ("scopecat.config.parameters", "insert_parameter_rows"),
    "replace_scalar_parameter": (
        "scopecat.config.parameters",
        "replace_scalar_parameter",
    ),
    "replace_series_parameter": (
        "scopecat.config.parameters",
        "replace_series_parameter",
    ),
    "replace_table_parameter": (
        "scopecat.config.parameters",
        "replace_table_parameter",
    ),
    "update_parameter_rows": ("scopecat.config.parameters", "update_parameter_rows"),
    "ExperimentPreview": ("scopecat.planning.preview_models", "ExperimentPreview"),
    "ExternalLocation": ("scopecat.kernel.problems", "ExternalLocation"),
    "ModelLocation": ("scopecat.kernel.problems", "ModelLocation"),
    "Problem": ("scopecat.kernel.problems", "Problem"),
    "ProblemCategory": ("scopecat.kernel.problems", "ProblemCategory"),
    "ProblemImpact": ("scopecat.kernel.problems", "ProblemImpact"),
    "ProblemLocation": ("scopecat.kernel.problems", "ProblemLocation"),
    "ProblemPhase": ("scopecat.kernel.problems", "ProblemPhase"),
    "RuntimeLocation": ("scopecat.kernel.problems", "RuntimeLocation"),
    "StorageLocation": ("scopecat.kernel.problems", "StorageLocation"),
    "blocking_problem": ("scopecat.kernel.problems", "blocking_problem"),
    "model_location": ("scopecat.kernel.problems", "model_location"),
    "MeasurementDatasetSchema": (
        "scopecat.measurements.results",
        "MeasurementDatasetSchema",
    ),
    "MeasurementTransformSemanticContract": (
        "scopecat.measurements.semantics",
        "MeasurementTransformSemanticContract",
    ),
    "RunFinishedEvent": ("scopecat.execution.observation", "RunFinishedEvent"),
    "RunStartedEvent": ("scopecat.execution.observation", "RunStartedEvent"),
    "RuntimeEvent": ("scopecat.execution.observation", "RuntimeEvent"),
    "RuntimeEventSink": ("scopecat.execution.observation", "RuntimeEventSink"),
    "RuntimePayloadObservation": (
        "scopecat.execution.observation",
        "RuntimePayloadObservation",
    ),
    "RuntimePayloadObserver": (
        "scopecat.execution.observation",
        "RuntimePayloadObserver",
    ),
    "RuntimeProgress": ("scopecat.execution.observation", "RuntimeProgress"),
    "RuntimeTransitionEvent": (
        "scopecat.execution.observation",
        "RuntimeTransitionEvent",
    ),
    "Analysis": ("scopecat.api.analysis", "Analysis"),
    "AnalysisContext": ("scopecat.api.analysis", "AnalysisContext"),
    "AnalysisInput": ("scopecat.analysis.service", "AnalysisInput"),
    "AnalysisOutput": ("scopecat.analysis.service", "AnalysisOutput"),
    "AnalysisStep": ("scopecat.api.analysis", "AnalysisStep"),
    "CandidateConfig": ("scopecat.config.candidates", "CandidateConfig"),
    "Data": ("scopecat.api.data", "Data"),
    "EarlyStopDecision": ("scopecat.analysis.online", "EarlyStopDecision"),
    "Experiment": ("scopecat.api.workspace", "Experiment"),
    "PreparedExperiment": ("scopecat.api.workspace", "PreparedExperiment"),
    "Quantity": ("scopecat.records.parameter", "Quantity"),
    "RunHandle": ("scopecat.api.run", "RunHandle"),
    "SavedAnalysis": ("scopecat.analysis.service", "SavedAnalysis"),
    "Workspace": ("scopecat.api.workspace", "Workspace"),
    "decide_online_convergence": (
        "scopecat.analysis.online",
        "decide_online_convergence",
    ),
    "open": ("scopecat.composition.local", "open_local_workspace"),
    "Run": ("scopecat.api.run", "RunHandle"),
}


def __getattr__(name: str) -> object:
    target = _EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    value = cast("object", getattr(import_module(module_name), attribute_name))
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_EXPORTS))


__all__ = [
    "Analysis",
    "AnalysisContext",
    "AnalysisInput",
    "AnalysisOutput",
    "AnalysisStep",
    "BoolType",
    "CandidateConfig",
    "Compute",
    "ComputeInput",
    "Data",
    "DomainExecution",
    "DomainInputPort",
    "DomainProgramDef",
    "DomainResourcePort",
    "DomainResultPort",
    "EarlyStopDecision",
    "EntityRef",
    "EntityType",
    "Experiment",
    "ExperimentCheckResult",
    "ExperimentInvocation",
    "ExperimentModule",
    "ExperimentPreview",
    "ExperimentSystem",
    "ExperimentTemplate",
    "ExternalLocation",
    "FloatType",
    "InputDescription",
    "IntType",
    "MeasurementDatasetSchema",
    "MeasurementTransform",
    "MeasurementTransformSemanticContract",
    "MetadataValue",
    "ModelLocation",
    "ModuleBuilder",
    "ModuleInput",
    "ModuleInvocation",
    "ModuleOutputs",
    "ParameterKeyInput",
    "ParameterRow",
    "PayloadType",
    "PreparedExperiment",
    "Problem",
    "ProblemCategory",
    "ProblemImpact",
    "ProblemLocation",
    "ProblemPhase",
    "ProductAxis",
    "ProductOutputs",
    "ProductRef",
    "Quantity",
    "QuantityType",
    "RecordField",
    "RecordSelection",
    "RecordType",
    "ResolvedRoute",
    "RouteRef",
    "RouteType",
    "Run",
    "RunDomainJob",
    "RunFinishedEvent",
    "RunHandle",
    "RunHostBinding",
    "RunProgram",
    "RunStartedEvent",
    "RuntimeEvent",
    "RuntimeEventSink",
    "RuntimeInput",
    "RuntimeLocation",
    "RuntimePayloadObservation",
    "RuntimePayloadObserver",
    "RuntimeProgress",
    "RuntimeTransitionEvent",
    "SavedAnalysis",
    "ScalarInput",
    "ScalarType",
    "Scan",
    "SeriesType",
    "StorageLocation",
    "StringType",
    "TableColumn",
    "TableRow",
    "TableType",
    "TemplateBuilder",
    "ValueRef",
    "ValueType",
    "Workspace",
    "axis",
    "blocking_problem",
    "cartesian",
    "compute",
    "decide_online_convergence",
    "delete_parameter_rows",
    "domain_execution",
    "domain_program",
    "entity_axis",
    "entity_ref",
    "input",
    "insert_parameter_rows",
    "measurement_transform",
    "model_location",
    "module",
    "open",
    "param_axis",
    "param_row",
    "parameter",
    "parameter_lookup",
    "point",
    "product_axis",
    "record_alias",
    "record_product",
    "replace_scalar_parameter",
    "replace_series_parameter",
    "replace_table_parameter",
    "route",
    "shot_axis",
    "update_parameter_rows",
    "zip",
]
