"""Workspace-local config registry index."""

from scopecat.config_registry.local import (
    ACTIVE_CONFIG_REGISTRY_ENTRY_SELECTOR,
    CandidateConfigRegistrySource,
    CandidateProposalRegistryEvidence,
    ConfigRegistryActivationRecord,
    ConfigRegistryActiveState,
    ConfigRegistryEntry,
    ConfigRegistryEntrySource,
    ConfigRegistryIndex,
    DirectConfigRegistrySource,
    activate_config_registry_entry,
    current_config_registry_generation,
    list_config_registry_entries,
    load_active_config_registry_config,
    load_active_config_registry_entry,
    load_active_config_registry_state,
    load_config_registry_config,
    load_config_registry_entry,
    register_and_activate_candidate_config,
    register_and_activate_config_profile,
    register_candidate_config,
    register_config_profile,
    resolve_config_registry_config_source,
    rollback_config_registry,
)

__all__ = [
    "ACTIVE_CONFIG_REGISTRY_ENTRY_SELECTOR",
    "CandidateConfigRegistrySource",
    "CandidateProposalRegistryEvidence",
    "ConfigRegistryActivationRecord",
    "ConfigRegistryActiveState",
    "ConfigRegistryEntry",
    "ConfigRegistryEntrySource",
    "ConfigRegistryIndex",
    "DirectConfigRegistrySource",
    "activate_config_registry_entry",
    "current_config_registry_generation",
    "list_config_registry_entries",
    "load_active_config_registry_config",
    "load_active_config_registry_entry",
    "load_active_config_registry_state",
    "load_config_registry_config",
    "load_config_registry_entry",
    "register_and_activate_candidate_config",
    "register_and_activate_config_profile",
    "register_candidate_config",
    "register_config_profile",
    "resolve_config_registry_config_source",
    "rollback_config_registry",
]
